// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: types/filter/slam.proto

package filter

import (
	math "github.com/itohio/EasyRobot/types/math"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OccupancyGrid represents an occupancy grid map
type OccupancyGrid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          int32                  `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`                       // Number of rows
	Cols          int32                  `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`                       // Number of columns
	Resolution    float32                `protobuf:"fixed32,3,opt,name=resolution,proto3" json:"resolution,omitempty"`          // Grid cell size in meters
	OriginX       float32                `protobuf:"fixed32,4,opt,name=origin_x,json=originX,proto3" json:"origin_x,omitempty"` // X coordinate of map origin (meters)
	OriginY       float32                `protobuf:"fixed32,5,opt,name=origin_y,json=originY,proto3" json:"origin_y,omitempty"` // Y coordinate of map origin (meters)
	Grid          *math.Tensor           `protobuf:"bytes,6,opt,name=grid,proto3" json:"grid,omitempty"`                        // Occupancy values (0=free, 1=occupied, 0.5=unknown)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OccupancyGrid) Reset() {
	*x = OccupancyGrid{}
	mi := &file_types_filter_slam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OccupancyGrid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OccupancyGrid) ProtoMessage() {}

func (x *OccupancyGrid) ProtoReflect() protoreflect.Message {
	mi := &file_types_filter_slam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OccupancyGrid.ProtoReflect.Descriptor instead.
func (*OccupancyGrid) Descriptor() ([]byte, []int) {
	return file_types_filter_slam_proto_rawDescGZIP(), []int{0}
}

func (x *OccupancyGrid) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *OccupancyGrid) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *OccupancyGrid) GetResolution() float32 {
	if x != nil {
		return x.Resolution
	}
	return 0
}

func (x *OccupancyGrid) GetOriginX() float32 {
	if x != nil {
		return x.OriginX
	}
	return 0
}

func (x *OccupancyGrid) GetOriginY() float32 {
	if x != nil {
		return x.OriginY
	}
	return 0
}

func (x *OccupancyGrid) GetGrid() *math.Tensor {
	if x != nil {
		return x.Grid
	}
	return nil
}

// SLAMPose represents robot pose for SLAM
type SLAMPose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *math.Vector3D         `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`       // [px, py, 0] for 2D, [px, py, pz] for 3D
	Heading       float32                `protobuf:"fixed32,2,opt,name=heading,proto3" json:"heading,omitempty"`       // Heading angle in radians (for 2D)
	Orientation   *math.Quaternion       `protobuf:"bytes,3,opt,name=orientation,proto3" json:"orientation,omitempty"` // Full orientation quaternion (for 3D)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SLAMPose) Reset() {
	*x = SLAMPose{}
	mi := &file_types_filter_slam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SLAMPose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SLAMPose) ProtoMessage() {}

func (x *SLAMPose) ProtoReflect() protoreflect.Message {
	mi := &file_types_filter_slam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SLAMPose.ProtoReflect.Descriptor instead.
func (*SLAMPose) Descriptor() ([]byte, []int) {
	return file_types_filter_slam_proto_rawDescGZIP(), []int{1}
}

func (x *SLAMPose) GetPosition() *math.Vector3D {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *SLAMPose) GetHeading() float32 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *SLAMPose) GetOrientation() *math.Quaternion {
	if x != nil {
		return x.Orientation
	}
	return nil
}

// SLAMConfig represents SLAM filter configuration
type SLAMConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RayAngles           []float32              `protobuf:"fixed32,1,rep,packed,name=ray_angles,json=rayAngles,proto3" json:"ray_angles,omitempty"`                         // Ray angles in radians relative to robot heading
	Map                 *OccupancyGrid         `protobuf:"bytes,2,opt,name=map,proto3" json:"map,omitempty"`                                                               // Occupancy grid map
	MaxRange            float32                `protobuf:"fixed32,3,opt,name=max_range,json=maxRange,proto3" json:"max_range,omitempty"`                                   // Maximum sensor range in meters
	EnableMapping       bool                   `protobuf:"varint,4,opt,name=enable_mapping,json=enableMapping,proto3" json:"enable_mapping,omitempty"`                     // Enable online map building
	UseOptimizedRaycast bool                   `protobuf:"varint,5,opt,name=use_optimized_raycast,json=useOptimizedRaycast,proto3" json:"use_optimized_raycast,omitempty"` // Use optimized ray casting
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SLAMConfig) Reset() {
	*x = SLAMConfig{}
	mi := &file_types_filter_slam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SLAMConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SLAMConfig) ProtoMessage() {}

func (x *SLAMConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_filter_slam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SLAMConfig.ProtoReflect.Descriptor instead.
func (*SLAMConfig) Descriptor() ([]byte, []int) {
	return file_types_filter_slam_proto_rawDescGZIP(), []int{2}
}

func (x *SLAMConfig) GetRayAngles() []float32 {
	if x != nil {
		return x.RayAngles
	}
	return nil
}

func (x *SLAMConfig) GetMap() *OccupancyGrid {
	if x != nil {
		return x.Map
	}
	return nil
}

func (x *SLAMConfig) GetMaxRange() float32 {
	if x != nil {
		return x.MaxRange
	}
	return 0
}

func (x *SLAMConfig) GetEnableMapping() bool {
	if x != nil {
		return x.EnableMapping
	}
	return false
}

func (x *SLAMConfig) GetUseOptimizedRaycast() bool {
	if x != nil {
		return x.UseOptimizedRaycast
	}
	return false
}

// SLAMMeasurement represents distance measurements from ray-based sensors
type SLAMMeasurement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Distances     []float32              `protobuf:"fixed32,1,rep,packed,name=distances,proto3" json:"distances,omitempty"` // Distance measurements for each ray (meters)
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`         // Timestamp in nanoseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SLAMMeasurement) Reset() {
	*x = SLAMMeasurement{}
	mi := &file_types_filter_slam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SLAMMeasurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SLAMMeasurement) ProtoMessage() {}

func (x *SLAMMeasurement) ProtoReflect() protoreflect.Message {
	mi := &file_types_filter_slam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SLAMMeasurement.ProtoReflect.Descriptor instead.
func (*SLAMMeasurement) Descriptor() ([]byte, []int) {
	return file_types_filter_slam_proto_rawDescGZIP(), []int{3}
}

func (x *SLAMMeasurement) GetDistances() []float32 {
	if x != nil {
		return x.Distances
	}
	return nil
}

func (x *SLAMMeasurement) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// SLAMState represents SLAM filter state
type SLAMState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pose          *SLAMPose              `protobuf:"bytes,1,opt,name=pose,proto3" json:"pose,omitempty"`             // Estimated robot pose
	Covariance    *math.Tensor           `protobuf:"bytes,2,opt,name=covariance,proto3" json:"covariance,omitempty"` // Pose covariance matrix
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`  // Timestamp in nanoseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SLAMState) Reset() {
	*x = SLAMState{}
	mi := &file_types_filter_slam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SLAMState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SLAMState) ProtoMessage() {}

func (x *SLAMState) ProtoReflect() protoreflect.Message {
	mi := &file_types_filter_slam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SLAMState.ProtoReflect.Descriptor instead.
func (*SLAMState) Descriptor() ([]byte, []int) {
	return file_types_filter_slam_proto_rawDescGZIP(), []int{4}
}

func (x *SLAMState) GetPose() *SLAMPose {
	if x != nil {
		return x.Pose
	}
	return nil
}

func (x *SLAMState) GetCovariance() *math.Tensor {
	if x != nil {
		return x.Covariance
	}
	return nil
}

func (x *SLAMState) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_types_filter_slam_proto protoreflect.FileDescriptor

const file_types_filter_slam_proto_rawDesc = "" +
	"\n" +
	"\x17types/filter/slam.proto\x12\ftypes.filter\x1a\x17types/math/tensor.proto\x1a\x18types/math/vectors.proto\"\xb5\x01\n" +
	"\rOccupancyGrid\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\x05R\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\x05R\x04cols\x12\x1e\n" +
	"\n" +
	"resolution\x18\x03 \x01(\x02R\n" +
	"resolution\x12\x19\n" +
	"\borigin_x\x18\x04 \x01(\x02R\aoriginX\x12\x19\n" +
	"\borigin_y\x18\x05 \x01(\x02R\aoriginY\x12&\n" +
	"\x04grid\x18\x06 \x01(\v2\x12.types.math.TensorR\x04grid\"\x90\x01\n" +
	"\bSLAMPose\x120\n" +
	"\bposition\x18\x01 \x01(\v2\x14.types.math.Vector3DR\bposition\x12\x18\n" +
	"\aheading\x18\x02 \x01(\x02R\aheading\x128\n" +
	"\vorientation\x18\x03 \x01(\v2\x16.types.math.QuaternionR\vorientation\"\xd2\x01\n" +
	"\n" +
	"SLAMConfig\x12\x1d\n" +
	"\n" +
	"ray_angles\x18\x01 \x03(\x02R\trayAngles\x12-\n" +
	"\x03map\x18\x02 \x01(\v2\x1b.types.filter.OccupancyGridR\x03map\x12\x1b\n" +
	"\tmax_range\x18\x03 \x01(\x02R\bmaxRange\x12%\n" +
	"\x0eenable_mapping\x18\x04 \x01(\bR\renableMapping\x122\n" +
	"\x15use_optimized_raycast\x18\x05 \x01(\bR\x13useOptimizedRaycast\"M\n" +
	"\x0fSLAMMeasurement\x12\x1c\n" +
	"\tdistances\x18\x01 \x03(\x02R\tdistances\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\x89\x01\n" +
	"\tSLAMState\x12*\n" +
	"\x04pose\x18\x01 \x01(\v2\x16.types.filter.SLAMPoseR\x04pose\x122\n" +
	"\n" +
	"covariance\x18\x02 \x01(\v2\x12.types.math.TensorR\n" +
	"covariance\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestampB\x98\x01\n" +
	"\x10com.types.filterB\tSlamProtoP\x01Z(github.com/itohio/EasyRobot/types/filter\xa2\x02\x03TFX\xaa\x02\fTypes.Filter\xca\x02\fTypes\\Filter\xe2\x02\x18Types\\Filter\\GPBMetadata\xea\x02\rTypes::Filterb\x06proto3"

var (
	file_types_filter_slam_proto_rawDescOnce sync.Once
	file_types_filter_slam_proto_rawDescData []byte
)

func file_types_filter_slam_proto_rawDescGZIP() []byte {
	file_types_filter_slam_proto_rawDescOnce.Do(func() {
		file_types_filter_slam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_filter_slam_proto_rawDesc), len(file_types_filter_slam_proto_rawDesc)))
	})
	return file_types_filter_slam_proto_rawDescData
}

var file_types_filter_slam_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_types_filter_slam_proto_goTypes = []any{
	(*OccupancyGrid)(nil),   // 0: types.filter.OccupancyGrid
	(*SLAMPose)(nil),        // 1: types.filter.SLAMPose
	(*SLAMConfig)(nil),      // 2: types.filter.SLAMConfig
	(*SLAMMeasurement)(nil), // 3: types.filter.SLAMMeasurement
	(*SLAMState)(nil),       // 4: types.filter.SLAMState
	(*math.Tensor)(nil),     // 5: types.math.Tensor
	(*math.Vector3D)(nil),   // 6: types.math.Vector3D
	(*math.Quaternion)(nil), // 7: types.math.Quaternion
}
var file_types_filter_slam_proto_depIdxs = []int32{
	5, // 0: types.filter.OccupancyGrid.grid:type_name -> types.math.Tensor
	6, // 1: types.filter.SLAMPose.position:type_name -> types.math.Vector3D
	7, // 2: types.filter.SLAMPose.orientation:type_name -> types.math.Quaternion
	0, // 3: types.filter.SLAMConfig.map:type_name -> types.filter.OccupancyGrid
	1, // 4: types.filter.SLAMState.pose:type_name -> types.filter.SLAMPose
	5, // 5: types.filter.SLAMState.covariance:type_name -> types.math.Tensor
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_types_filter_slam_proto_init() }
func file_types_filter_slam_proto_init() {
	if File_types_filter_slam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_filter_slam_proto_rawDesc), len(file_types_filter_slam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_filter_slam_proto_goTypes,
		DependencyIndexes: file_types_filter_slam_proto_depIdxs,
		MessageInfos:      file_types_filter_slam_proto_msgTypes,
	}.Build()
	File_types_filter_slam_proto = out.File
	file_types_filter_slam_proto_goTypes = nil
	file_types_filter_slam_proto_depIdxs = nil
}
