// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: types/spectrometer/measurement.proto

package spectrometer

import (
	math "github.com/itohio/EasyRobot/types/math"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MeasurementMode enumerates measurement capture modes
type MeasurementMode int32

const (
	MeasurementMode_MODE_UNSPECIFIED MeasurementMode = 0
	MeasurementMode_MODE_SINGLE      MeasurementMode = 1 // Single-shot measurement
	MeasurementMode_MODE_AVERAGED    MeasurementMode = 2 // Averaged over multiple frames
	MeasurementMode_MODE_TRANSIENT   MeasurementMode = 3 // Time-series capture
	MeasurementMode_MODE_CONTINUOUS  MeasurementMode = 4 // Continuous streaming
)

// Enum value maps for MeasurementMode.
var (
	MeasurementMode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_SINGLE",
		2: "MODE_AVERAGED",
		3: "MODE_TRANSIENT",
		4: "MODE_CONTINUOUS",
	}
	MeasurementMode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"MODE_SINGLE":      1,
		"MODE_AVERAGED":    2,
		"MODE_TRANSIENT":   3,
		"MODE_CONTINUOUS":  4,
	}
)

func (x MeasurementMode) Enum() *MeasurementMode {
	p := new(MeasurementMode)
	*p = x
	return p
}

func (x MeasurementMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MeasurementMode) Descriptor() protoreflect.EnumDescriptor {
	return file_types_spectrometer_measurement_proto_enumTypes[0].Descriptor()
}

func (MeasurementMode) Type() protoreflect.EnumType {
	return &file_types_spectrometer_measurement_proto_enumTypes[0]
}

func (x MeasurementMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MeasurementMode.Descriptor instead.
func (MeasurementMode) EnumDescriptor() ([]byte, []int) {
	return file_types_spectrometer_measurement_proto_rawDescGZIP(), []int{0}
}

// MeasurementType enumerates different measurement types
type MeasurementType int32

const (
	MeasurementType_MEASUREMENT_TYPE_UNSPECIFIED  MeasurementType = 0
	MeasurementType_MEASUREMENT_TYPE_EMISSIVITY   MeasurementType = 1 // Self-emitting source
	MeasurementType_MEASUREMENT_TYPE_TRANSMISSION MeasurementType = 2 // Transmission through sample
	MeasurementType_MEASUREMENT_TYPE_REFLECTANCE  MeasurementType = 3 // Reflection from sample
	MeasurementType_MEASUREMENT_TYPE_RAMAN        MeasurementType = 4 // Raman scattering
	MeasurementType_MEASUREMENT_TYPE_FLUORESCENCE MeasurementType = 5 // Fluorescence/luminescence
)

// Enum value maps for MeasurementType.
var (
	MeasurementType_name = map[int32]string{
		0: "MEASUREMENT_TYPE_UNSPECIFIED",
		1: "MEASUREMENT_TYPE_EMISSIVITY",
		2: "MEASUREMENT_TYPE_TRANSMISSION",
		3: "MEASUREMENT_TYPE_REFLECTANCE",
		4: "MEASUREMENT_TYPE_RAMAN",
		5: "MEASUREMENT_TYPE_FLUORESCENCE",
	}
	MeasurementType_value = map[string]int32{
		"MEASUREMENT_TYPE_UNSPECIFIED":  0,
		"MEASUREMENT_TYPE_EMISSIVITY":   1,
		"MEASUREMENT_TYPE_TRANSMISSION": 2,
		"MEASUREMENT_TYPE_REFLECTANCE":  3,
		"MEASUREMENT_TYPE_RAMAN":        4,
		"MEASUREMENT_TYPE_FLUORESCENCE": 5,
	}
)

func (x MeasurementType) Enum() *MeasurementType {
	p := new(MeasurementType)
	*p = x
	return p
}

func (x MeasurementType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MeasurementType) Descriptor() protoreflect.EnumDescriptor {
	return file_types_spectrometer_measurement_proto_enumTypes[1].Descriptor()
}

func (MeasurementType) Type() protoreflect.EnumType {
	return &file_types_spectrometer_measurement_proto_enumTypes[1]
}

func (x MeasurementType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MeasurementType.Descriptor instead.
func (MeasurementType) EnumDescriptor() ([]byte, []int) {
	return file_types_spectrometer_measurement_proto_rawDescGZIP(), []int{1}
}

// SpectrumMeasurement represents a complete spectrum measurement with metadata
type SpectrumMeasurement struct {
	state             protoimpl.MessageState     `protogen:"open.v1"`
	Config            *SpectrometerConfiguration `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`                                                                                         // Configuration used for this measurement
	Metadata          *MeasurementMetadata       `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`                                                                                     // Measurement metadata
	Spectrum          *math.Matrix               `protobuf:"bytes,3,opt,name=spectrum,proto3" json:"spectrum,omitempty"`                                                                                     // Spectrum matrix (row 0: wavelengths, row 1: intensities)
	Colorimetry       *ColorimetryData           `protobuf:"bytes,4,opt,name=colorimetry,proto3,oneof" json:"colorimetry,omitempty"`                                                                         // Colorimetry data (if computed)
	MeasurementType   *MeasurementType           `protobuf:"varint,5,opt,name=measurement_type,json=measurementType,proto3,enum=types.spectrometer.MeasurementType,oneof" json:"measurement_type,omitempty"` // Type of measurement (emissivity, transmission, etc.)
	Illuminant        *IlluminantType            `protobuf:"varint,6,opt,name=illuminant,proto3,enum=types.spectrometer.IlluminantType,oneof" json:"illuminant,omitempty"`                                   // Illuminant used for this measurement
	DarkSpectrum      *math.Matrix               `protobuf:"bytes,7,opt,name=dark_spectrum,json=darkSpectrum,proto3,oneof" json:"dark_spectrum,omitempty"`                                                   // Dark measurement spectrum (always included if dark correction enabled)
	ReferenceSpectrum *math.Matrix               `protobuf:"bytes,8,opt,name=reference_spectrum,json=referenceSpectrum,proto3,oneof" json:"reference_spectrum,omitempty"`                                    // Reference/calibration spectrum (for transmission/reflectance)
	FluorescenceDecay *FluorescenceDecayData     `protobuf:"bytes,9,opt,name=fluorescence_decay,json=fluorescenceDecay,proto3,oneof" json:"fluorescence_decay,omitempty"`                                    // Decay data (for fluorescence measurements only)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SpectrumMeasurement) Reset() {
	*x = SpectrumMeasurement{}
	mi := &file_types_spectrometer_measurement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpectrumMeasurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpectrumMeasurement) ProtoMessage() {}

func (x *SpectrumMeasurement) ProtoReflect() protoreflect.Message {
	mi := &file_types_spectrometer_measurement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpectrumMeasurement.ProtoReflect.Descriptor instead.
func (*SpectrumMeasurement) Descriptor() ([]byte, []int) {
	return file_types_spectrometer_measurement_proto_rawDescGZIP(), []int{0}
}

func (x *SpectrumMeasurement) GetConfig() *SpectrometerConfiguration {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *SpectrumMeasurement) GetMetadata() *MeasurementMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SpectrumMeasurement) GetSpectrum() *math.Matrix {
	if x != nil {
		return x.Spectrum
	}
	return nil
}

func (x *SpectrumMeasurement) GetColorimetry() *ColorimetryData {
	if x != nil {
		return x.Colorimetry
	}
	return nil
}

func (x *SpectrumMeasurement) GetMeasurementType() MeasurementType {
	if x != nil && x.MeasurementType != nil {
		return *x.MeasurementType
	}
	return MeasurementType_MEASUREMENT_TYPE_UNSPECIFIED
}

func (x *SpectrumMeasurement) GetIlluminant() IlluminantType {
	if x != nil && x.Illuminant != nil {
		return *x.Illuminant
	}
	return IlluminantType_ILLUMINANT_NONE
}

func (x *SpectrumMeasurement) GetDarkSpectrum() *math.Matrix {
	if x != nil {
		return x.DarkSpectrum
	}
	return nil
}

func (x *SpectrumMeasurement) GetReferenceSpectrum() *math.Matrix {
	if x != nil {
		return x.ReferenceSpectrum
	}
	return nil
}

func (x *SpectrumMeasurement) GetFluorescenceDecay() *FluorescenceDecayData {
	if x != nil {
		return x.FluorescenceDecay
	}
	return nil
}

// MeasurementMetadata contains metadata about the measurement
type MeasurementMetadata struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Timestamp  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                     // Measurement timestamp
	SourceType string                 `protobuf:"bytes,2,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"` // Source type: "camera" or "sensor" (e.g., "as734x")
	// Types that are valid to be assigned to SourceId:
	//
	//	*MeasurementMetadata_CameraId
	//	*MeasurementMetadata_SensorId
	SourceId      isMeasurementMetadata_SourceId `protobuf_oneof:"source_id"`
	ConfigFile    string                         `protobuf:"bytes,5,opt,name=config_file,json=configFile,proto3" json:"config_file,omitempty"`            // Path to configuration file used
	Mode          MeasurementMode                `protobuf:"varint,6,opt,name=mode,proto3,enum=types.spectrometer.MeasurementMode" json:"mode,omitempty"` // Measurement mode
	FrameCount    int32                          `protobuf:"varint,7,opt,name=frame_count,json=frameCount,proto3" json:"frame_count,omitempty"`           // Number of frames averaged (for averaged measurements)
	ExposureUs    float64                        `protobuf:"fixed64,8,opt,name=exposure_us,json=exposureUs,proto3" json:"exposure_us,omitempty"`          // Exposure time used (microseconds)
	Gain          float64                        `protobuf:"fixed64,9,opt,name=gain,proto3" json:"gain,omitempty"`                                        // Gain setting used
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeasurementMetadata) Reset() {
	*x = MeasurementMetadata{}
	mi := &file_types_spectrometer_measurement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasurementMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasurementMetadata) ProtoMessage() {}

func (x *MeasurementMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_types_spectrometer_measurement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasurementMetadata.ProtoReflect.Descriptor instead.
func (*MeasurementMetadata) Descriptor() ([]byte, []int) {
	return file_types_spectrometer_measurement_proto_rawDescGZIP(), []int{1}
}

func (x *MeasurementMetadata) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MeasurementMetadata) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *MeasurementMetadata) GetSourceId() isMeasurementMetadata_SourceId {
	if x != nil {
		return x.SourceId
	}
	return nil
}

func (x *MeasurementMetadata) GetCameraId() string {
	if x != nil {
		if x, ok := x.SourceId.(*MeasurementMetadata_CameraId); ok {
			return x.CameraId
		}
	}
	return ""
}

func (x *MeasurementMetadata) GetSensorId() string {
	if x != nil {
		if x, ok := x.SourceId.(*MeasurementMetadata_SensorId); ok {
			return x.SensorId
		}
	}
	return ""
}

func (x *MeasurementMetadata) GetConfigFile() string {
	if x != nil {
		return x.ConfigFile
	}
	return ""
}

func (x *MeasurementMetadata) GetMode() MeasurementMode {
	if x != nil {
		return x.Mode
	}
	return MeasurementMode_MODE_UNSPECIFIED
}

func (x *MeasurementMetadata) GetFrameCount() int32 {
	if x != nil {
		return x.FrameCount
	}
	return 0
}

func (x *MeasurementMetadata) GetExposureUs() float64 {
	if x != nil {
		return x.ExposureUs
	}
	return 0
}

func (x *MeasurementMetadata) GetGain() float64 {
	if x != nil {
		return x.Gain
	}
	return 0
}

type isMeasurementMetadata_SourceId interface {
	isMeasurementMetadata_SourceId()
}

type MeasurementMetadata_CameraId struct {
	CameraId string `protobuf:"bytes,3,opt,name=camera_id,json=cameraId,proto3,oneof"` // Camera identifier (if source_type == "camera", e.g., "0", "/dev/video0")
}

type MeasurementMetadata_SensorId struct {
	SensorId string `protobuf:"bytes,4,opt,name=sensor_id,json=sensorId,proto3,oneof"` // Sensor identifier (if source_type == "sensor", e.g., "as734x:/dev/i2c-1:0x39")
}

func (*MeasurementMetadata_CameraId) isMeasurementMetadata_SourceId() {}

func (*MeasurementMetadata_SensorId) isMeasurementMetadata_SourceId() {}

// ColorimetryData contains computed colorimetry values
type ColorimetryData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cct           float64                `protobuf:"fixed64,1,opt,name=cct,proto3" json:"cct,omitempty"`     // Correlated Color Temperature (Kelvin)
	Xyz           *math.Vector           `protobuf:"bytes,2,opt,name=xyz,proto3" json:"xyz,omitempty"`       // XYZ color values (3-element vector)
	Lab           *math.Vector           `protobuf:"bytes,3,opt,name=lab,proto3" json:"lab,omitempty"`       // LAB color values (3-element vector)
	Rgb           *math.Vector           `protobuf:"bytes,4,opt,name=rgb,proto3,oneof" json:"rgb,omitempty"` // RGB color values (optional, 3-element vector)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColorimetryData) Reset() {
	*x = ColorimetryData{}
	mi := &file_types_spectrometer_measurement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColorimetryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorimetryData) ProtoMessage() {}

func (x *ColorimetryData) ProtoReflect() protoreflect.Message {
	mi := &file_types_spectrometer_measurement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorimetryData.ProtoReflect.Descriptor instead.
func (*ColorimetryData) Descriptor() ([]byte, []int) {
	return file_types_spectrometer_measurement_proto_rawDescGZIP(), []int{2}
}

func (x *ColorimetryData) GetCct() float64 {
	if x != nil {
		return x.Cct
	}
	return 0
}

func (x *ColorimetryData) GetXyz() *math.Vector {
	if x != nil {
		return x.Xyz
	}
	return nil
}

func (x *ColorimetryData) GetLab() *math.Vector {
	if x != nil {
		return x.Lab
	}
	return nil
}

func (x *ColorimetryData) GetRgb() *math.Vector {
	if x != nil {
		return x.Rgb
	}
	return nil
}

// FluorescenceDecayData contains data for fluorescence decay measurements
type FluorescenceDecayData struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	FlashTime          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=flash_time,json=flashTime,proto3" json:"flash_time,omitempty"`                                       // Flash excitation time
	FlashDurationMs    int64                  `protobuf:"varint,2,opt,name=flash_duration_ms,json=flashDurationMs,proto3" json:"flash_duration_ms,omitempty"`                  // Flash duration in milliseconds
	InitialSpectrum    *math.Matrix           `protobuf:"bytes,3,opt,name=initial_spectrum,json=initialSpectrum,proto3" json:"initial_spectrum,omitempty"`                     // Spectrum immediately after flash (row 0: wavelengths, row 1: intensities)
	DecaySeries        *math.Matrix           `protobuf:"bytes,4,opt,name=decay_series,json=decaySeries,proto3" json:"decay_series,omitempty"`                                 // Time-series of spectra during decay (row 0: wavelengths, row 1+: timepoints)
	DecayTimeConstants []float64              `protobuf:"fixed64,5,rep,packed,name=decay_time_constants,json=decayTimeConstants,proto3" json:"decay_time_constants,omitempty"` // Fitted decay constants (τ values, multiple if multi-exponential)
	DecayAmplitudes    []float64              `protobuf:"fixed64,6,rep,packed,name=decay_amplitudes,json=decayAmplitudes,proto3" json:"decay_amplitudes,omitempty"`            // Amplitudes for each decay component
	FitRSquared        float64                `protobuf:"fixed64,7,opt,name=fit_r_squared,json=fitRSquared,proto3" json:"fit_r_squared,omitempty"`                             // R-squared of decay fit
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FluorescenceDecayData) Reset() {
	*x = FluorescenceDecayData{}
	mi := &file_types_spectrometer_measurement_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FluorescenceDecayData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FluorescenceDecayData) ProtoMessage() {}

func (x *FluorescenceDecayData) ProtoReflect() protoreflect.Message {
	mi := &file_types_spectrometer_measurement_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FluorescenceDecayData.ProtoReflect.Descriptor instead.
func (*FluorescenceDecayData) Descriptor() ([]byte, []int) {
	return file_types_spectrometer_measurement_proto_rawDescGZIP(), []int{3}
}

func (x *FluorescenceDecayData) GetFlashTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FlashTime
	}
	return nil
}

func (x *FluorescenceDecayData) GetFlashDurationMs() int64 {
	if x != nil {
		return x.FlashDurationMs
	}
	return 0
}

func (x *FluorescenceDecayData) GetInitialSpectrum() *math.Matrix {
	if x != nil {
		return x.InitialSpectrum
	}
	return nil
}

func (x *FluorescenceDecayData) GetDecaySeries() *math.Matrix {
	if x != nil {
		return x.DecaySeries
	}
	return nil
}

func (x *FluorescenceDecayData) GetDecayTimeConstants() []float64 {
	if x != nil {
		return x.DecayTimeConstants
	}
	return nil
}

func (x *FluorescenceDecayData) GetDecayAmplitudes() []float64 {
	if x != nil {
		return x.DecayAmplitudes
	}
	return nil
}

func (x *FluorescenceDecayData) GetFitRSquared() float64 {
	if x != nil {
		return x.FitRSquared
	}
	return 0
}

// ColorPatch represents a color patch with reference values for measurement comparison
type ColorPatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                     // Patch name/identifier
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"` // Optional description
	Xyz           *math.Vector           `protobuf:"bytes,3,opt,name=xyz,proto3" json:"xyz,omitempty"`                       // Reference XYZ color values (3-element vector)
	Lab           *math.Vector           `protobuf:"bytes,4,opt,name=lab,proto3" json:"lab,omitempty"`                       // Reference LAB color values (3-element vector)
	Spectrum      *math.Matrix           `protobuf:"bytes,5,opt,name=spectrum,proto3,oneof" json:"spectrum,omitempty"`       // Reference spectrum (row 0: wavelengths, row 1: intensities)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColorPatch) Reset() {
	*x = ColorPatch{}
	mi := &file_types_spectrometer_measurement_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColorPatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorPatch) ProtoMessage() {}

func (x *ColorPatch) ProtoReflect() protoreflect.Message {
	mi := &file_types_spectrometer_measurement_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorPatch.ProtoReflect.Descriptor instead.
func (*ColorPatch) Descriptor() ([]byte, []int) {
	return file_types_spectrometer_measurement_proto_rawDescGZIP(), []int{4}
}

func (x *ColorPatch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColorPatch) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ColorPatch) GetXyz() *math.Vector {
	if x != nil {
		return x.Xyz
	}
	return nil
}

func (x *ColorPatch) GetLab() *math.Vector {
	if x != nil {
		return x.Lab
	}
	return nil
}

func (x *ColorPatch) GetSpectrum() *math.Matrix {
	if x != nil {
		return x.Spectrum
	}
	return nil
}

// ColorPatches contains a collection of color patches for measurement comparison
type ColorPatches struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patches       []*ColorPatch          `protobuf:"bytes,1,rep,name=patches,proto3" json:"patches,omitempty"`                      // List of color patches
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Creation timestamp
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`        // Optional description for the patch set
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColorPatches) Reset() {
	*x = ColorPatches{}
	mi := &file_types_spectrometer_measurement_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColorPatches) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorPatches) ProtoMessage() {}

func (x *ColorPatches) ProtoReflect() protoreflect.Message {
	mi := &file_types_spectrometer_measurement_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorPatches.ProtoReflect.Descriptor instead.
func (*ColorPatches) Descriptor() ([]byte, []int) {
	return file_types_spectrometer_measurement_proto_rawDescGZIP(), []int{5}
}

func (x *ColorPatches) GetPatches() []*ColorPatch {
	if x != nil {
		return x.Patches
	}
	return nil
}

func (x *ColorPatches) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ColorPatches) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

var File_types_spectrometer_measurement_proto protoreflect.FileDescriptor

const file_types_spectrometer_measurement_proto_rawDesc = "" +
	"\n" +
	"$types/spectrometer/measurement.proto\x12\x12types.spectrometer\x1a\x19types/math/matrices.proto\x1a\x18types/math/vectors.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ftypes/spectrometer/config.proto\"\x94\x06\n" +
	"\x13SpectrumMeasurement\x12E\n" +
	"\x06config\x18\x01 \x01(\v2-.types.spectrometer.SpectrometerConfigurationR\x06config\x12C\n" +
	"\bmetadata\x18\x02 \x01(\v2'.types.spectrometer.MeasurementMetadataR\bmetadata\x12.\n" +
	"\bspectrum\x18\x03 \x01(\v2\x12.types.math.MatrixR\bspectrum\x12J\n" +
	"\vcolorimetry\x18\x04 \x01(\v2#.types.spectrometer.ColorimetryDataH\x00R\vcolorimetry\x88\x01\x01\x12S\n" +
	"\x10measurement_type\x18\x05 \x01(\x0e2#.types.spectrometer.MeasurementTypeH\x01R\x0fmeasurementType\x88\x01\x01\x12G\n" +
	"\n" +
	"illuminant\x18\x06 \x01(\x0e2\".types.spectrometer.IlluminantTypeH\x02R\n" +
	"illuminant\x88\x01\x01\x12<\n" +
	"\rdark_spectrum\x18\a \x01(\v2\x12.types.math.MatrixH\x03R\fdarkSpectrum\x88\x01\x01\x12F\n" +
	"\x12reference_spectrum\x18\b \x01(\v2\x12.types.math.MatrixH\x04R\x11referenceSpectrum\x88\x01\x01\x12]\n" +
	"\x12fluorescence_decay\x18\t \x01(\v2).types.spectrometer.FluorescenceDecayDataH\x05R\x11fluorescenceDecay\x88\x01\x01B\x0e\n" +
	"\f_colorimetryB\x13\n" +
	"\x11_measurement_typeB\r\n" +
	"\v_illuminantB\x10\n" +
	"\x0e_dark_spectrumB\x15\n" +
	"\x13_reference_spectrumB\x15\n" +
	"\x13_fluorescence_decay\"\xeb\x02\n" +
	"\x13MeasurementMetadata\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1f\n" +
	"\vsource_type\x18\x02 \x01(\tR\n" +
	"sourceType\x12\x1d\n" +
	"\tcamera_id\x18\x03 \x01(\tH\x00R\bcameraId\x12\x1d\n" +
	"\tsensor_id\x18\x04 \x01(\tH\x00R\bsensorId\x12\x1f\n" +
	"\vconfig_file\x18\x05 \x01(\tR\n" +
	"configFile\x127\n" +
	"\x04mode\x18\x06 \x01(\x0e2#.types.spectrometer.MeasurementModeR\x04mode\x12\x1f\n" +
	"\vframe_count\x18\a \x01(\x05R\n" +
	"frameCount\x12\x1f\n" +
	"\vexposure_us\x18\b \x01(\x01R\n" +
	"exposureUs\x12\x12\n" +
	"\x04gain\x18\t \x01(\x01R\x04gainB\v\n" +
	"\tsource_id\"\xa2\x01\n" +
	"\x0fColorimetryData\x12\x10\n" +
	"\x03cct\x18\x01 \x01(\x01R\x03cct\x12$\n" +
	"\x03xyz\x18\x02 \x01(\v2\x12.types.math.VectorR\x03xyz\x12$\n" +
	"\x03lab\x18\x03 \x01(\v2\x12.types.math.VectorR\x03lab\x12)\n" +
	"\x03rgb\x18\x04 \x01(\v2\x12.types.math.VectorH\x00R\x03rgb\x88\x01\x01B\x06\n" +
	"\x04_rgb\"\xf5\x02\n" +
	"\x15FluorescenceDecayData\x129\n" +
	"\n" +
	"flash_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tflashTime\x12*\n" +
	"\x11flash_duration_ms\x18\x02 \x01(\x03R\x0fflashDurationMs\x12=\n" +
	"\x10initial_spectrum\x18\x03 \x01(\v2\x12.types.math.MatrixR\x0finitialSpectrum\x125\n" +
	"\fdecay_series\x18\x04 \x01(\v2\x12.types.math.MatrixR\vdecaySeries\x120\n" +
	"\x14decay_time_constants\x18\x05 \x03(\x01R\x12decayTimeConstants\x12)\n" +
	"\x10decay_amplitudes\x18\x06 \x03(\x01R\x0fdecayAmplitudes\x12\"\n" +
	"\rfit_r_squared\x18\a \x01(\x01R\vfitRSquared\"\xe5\x01\n" +
	"\n" +
	"ColorPatch\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12$\n" +
	"\x03xyz\x18\x03 \x01(\v2\x12.types.math.VectorR\x03xyz\x12$\n" +
	"\x03lab\x18\x04 \x01(\v2\x12.types.math.VectorR\x03lab\x123\n" +
	"\bspectrum\x18\x05 \x01(\v2\x12.types.math.MatrixH\x01R\bspectrum\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_spectrum\"\xba\x01\n" +
	"\fColorPatches\x128\n" +
	"\apatches\x18\x01 \x03(\v2\x1e.types.spectrometer.ColorPatchR\apatches\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description*t\n" +
	"\x0fMeasurementMode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vMODE_SINGLE\x10\x01\x12\x11\n" +
	"\rMODE_AVERAGED\x10\x02\x12\x12\n" +
	"\x0eMODE_TRANSIENT\x10\x03\x12\x13\n" +
	"\x0fMODE_CONTINUOUS\x10\x04*\xd8\x01\n" +
	"\x0fMeasurementType\x12 \n" +
	"\x1cMEASUREMENT_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bMEASUREMENT_TYPE_EMISSIVITY\x10\x01\x12!\n" +
	"\x1dMEASUREMENT_TYPE_TRANSMISSION\x10\x02\x12 \n" +
	"\x1cMEASUREMENT_TYPE_REFLECTANCE\x10\x03\x12\x1a\n" +
	"\x16MEASUREMENT_TYPE_RAMAN\x10\x04\x12!\n" +
	"\x1dMEASUREMENT_TYPE_FLUORESCENCE\x10\x05B\xc3\x01\n" +
	"\x16com.types.spectrometerB\x10MeasurementProtoP\x01Z.github.com/itohio/EasyRobot/types/spectrometer\xa2\x02\x03TSX\xaa\x02\x12Types.Spectrometer\xca\x02\x12Types\\Spectrometer\xe2\x02\x1eTypes\\Spectrometer\\GPBMetadata\xea\x02\x13Types::Spectrometerb\x06proto3"

var (
	file_types_spectrometer_measurement_proto_rawDescOnce sync.Once
	file_types_spectrometer_measurement_proto_rawDescData []byte
)

func file_types_spectrometer_measurement_proto_rawDescGZIP() []byte {
	file_types_spectrometer_measurement_proto_rawDescOnce.Do(func() {
		file_types_spectrometer_measurement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_spectrometer_measurement_proto_rawDesc), len(file_types_spectrometer_measurement_proto_rawDesc)))
	})
	return file_types_spectrometer_measurement_proto_rawDescData
}

var file_types_spectrometer_measurement_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_types_spectrometer_measurement_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_types_spectrometer_measurement_proto_goTypes = []any{
	(MeasurementMode)(0),              // 0: types.spectrometer.MeasurementMode
	(MeasurementType)(0),              // 1: types.spectrometer.MeasurementType
	(*SpectrumMeasurement)(nil),       // 2: types.spectrometer.SpectrumMeasurement
	(*MeasurementMetadata)(nil),       // 3: types.spectrometer.MeasurementMetadata
	(*ColorimetryData)(nil),           // 4: types.spectrometer.ColorimetryData
	(*FluorescenceDecayData)(nil),     // 5: types.spectrometer.FluorescenceDecayData
	(*ColorPatch)(nil),                // 6: types.spectrometer.ColorPatch
	(*ColorPatches)(nil),              // 7: types.spectrometer.ColorPatches
	(*SpectrometerConfiguration)(nil), // 8: types.spectrometer.SpectrometerConfiguration
	(*math.Matrix)(nil),               // 9: types.math.Matrix
	(IlluminantType)(0),               // 10: types.spectrometer.IlluminantType
	(*timestamppb.Timestamp)(nil),     // 11: google.protobuf.Timestamp
	(*math.Vector)(nil),               // 12: types.math.Vector
}
var file_types_spectrometer_measurement_proto_depIdxs = []int32{
	8,  // 0: types.spectrometer.SpectrumMeasurement.config:type_name -> types.spectrometer.SpectrometerConfiguration
	3,  // 1: types.spectrometer.SpectrumMeasurement.metadata:type_name -> types.spectrometer.MeasurementMetadata
	9,  // 2: types.spectrometer.SpectrumMeasurement.spectrum:type_name -> types.math.Matrix
	4,  // 3: types.spectrometer.SpectrumMeasurement.colorimetry:type_name -> types.spectrometer.ColorimetryData
	1,  // 4: types.spectrometer.SpectrumMeasurement.measurement_type:type_name -> types.spectrometer.MeasurementType
	10, // 5: types.spectrometer.SpectrumMeasurement.illuminant:type_name -> types.spectrometer.IlluminantType
	9,  // 6: types.spectrometer.SpectrumMeasurement.dark_spectrum:type_name -> types.math.Matrix
	9,  // 7: types.spectrometer.SpectrumMeasurement.reference_spectrum:type_name -> types.math.Matrix
	5,  // 8: types.spectrometer.SpectrumMeasurement.fluorescence_decay:type_name -> types.spectrometer.FluorescenceDecayData
	11, // 9: types.spectrometer.MeasurementMetadata.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 10: types.spectrometer.MeasurementMetadata.mode:type_name -> types.spectrometer.MeasurementMode
	12, // 11: types.spectrometer.ColorimetryData.xyz:type_name -> types.math.Vector
	12, // 12: types.spectrometer.ColorimetryData.lab:type_name -> types.math.Vector
	12, // 13: types.spectrometer.ColorimetryData.rgb:type_name -> types.math.Vector
	11, // 14: types.spectrometer.FluorescenceDecayData.flash_time:type_name -> google.protobuf.Timestamp
	9,  // 15: types.spectrometer.FluorescenceDecayData.initial_spectrum:type_name -> types.math.Matrix
	9,  // 16: types.spectrometer.FluorescenceDecayData.decay_series:type_name -> types.math.Matrix
	12, // 17: types.spectrometer.ColorPatch.xyz:type_name -> types.math.Vector
	12, // 18: types.spectrometer.ColorPatch.lab:type_name -> types.math.Vector
	9,  // 19: types.spectrometer.ColorPatch.spectrum:type_name -> types.math.Matrix
	6,  // 20: types.spectrometer.ColorPatches.patches:type_name -> types.spectrometer.ColorPatch
	11, // 21: types.spectrometer.ColorPatches.created_at:type_name -> google.protobuf.Timestamp
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_types_spectrometer_measurement_proto_init() }
func file_types_spectrometer_measurement_proto_init() {
	if File_types_spectrometer_measurement_proto != nil {
		return
	}
	file_types_spectrometer_config_proto_init()
	file_types_spectrometer_measurement_proto_msgTypes[0].OneofWrappers = []any{}
	file_types_spectrometer_measurement_proto_msgTypes[1].OneofWrappers = []any{
		(*MeasurementMetadata_CameraId)(nil),
		(*MeasurementMetadata_SensorId)(nil),
	}
	file_types_spectrometer_measurement_proto_msgTypes[2].OneofWrappers = []any{}
	file_types_spectrometer_measurement_proto_msgTypes[4].OneofWrappers = []any{}
	file_types_spectrometer_measurement_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_spectrometer_measurement_proto_rawDesc), len(file_types_spectrometer_measurement_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_spectrometer_measurement_proto_goTypes,
		DependencyIndexes: file_types_spectrometer_measurement_proto_depIdxs,
		EnumInfos:         file_types_spectrometer_measurement_proto_enumTypes,
		MessageInfos:      file_types_spectrometer_measurement_proto_msgTypes,
	}.Build()
	File_types_spectrometer_measurement_proto = out.File
	file_types_spectrometer_measurement_proto_goTypes = nil
	file_types_spectrometer_measurement_proto_depIdxs = nil
}
