// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: types/devices/sensors.proto

package devices

import (
	math "github.com/itohio/EasyRobot/types/math"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IMUReading represents IMU sensor readings
type IMUReading struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Acceleration    *math.Vector3D         `protobuf:"bytes,1,opt,name=acceleration,proto3" json:"acceleration,omitempty"`                              // Acceleration [ax, ay, az] (m/s²)
	AngularVelocity *math.Vector3D         `protobuf:"bytes,2,opt,name=angular_velocity,json=angularVelocity,proto3" json:"angular_velocity,omitempty"` // Angular velocity [ωx, ωy, ωz] (rad/s)
	MagneticField   *math.Vector3D         `protobuf:"bytes,3,opt,name=magnetic_field,json=magneticField,proto3" json:"magnetic_field,omitempty"`       // Magnetic field [mx, my, mz] (µT)
	Temperature     float32                `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`                              // Temperature (°C)
	Timestamp       int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                   // Timestamp in nanoseconds
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IMUReading) Reset() {
	*x = IMUReading{}
	mi := &file_types_devices_sensors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IMUReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMUReading) ProtoMessage() {}

func (x *IMUReading) ProtoReflect() protoreflect.Message {
	mi := &file_types_devices_sensors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMUReading.ProtoReflect.Descriptor instead.
func (*IMUReading) Descriptor() ([]byte, []int) {
	return file_types_devices_sensors_proto_rawDescGZIP(), []int{0}
}

func (x *IMUReading) GetAcceleration() *math.Vector3D {
	if x != nil {
		return x.Acceleration
	}
	return nil
}

func (x *IMUReading) GetAngularVelocity() *math.Vector3D {
	if x != nil {
		return x.AngularVelocity
	}
	return nil
}

func (x *IMUReading) GetMagneticField() *math.Vector3D {
	if x != nil {
		return x.MagneticField
	}
	return nil
}

func (x *IMUReading) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *IMUReading) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// DistanceReading represents distance sensor readings
type DistanceReading struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DistanceMm    float32                `protobuf:"fixed32,1,opt,name=distance_mm,json=distanceMm,proto3" json:"distance_mm,omitempty"` // Distance in millimeters
	Valid         bool                   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`                              // Whether reading is valid
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                      // Timestamp in nanoseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistanceReading) Reset() {
	*x = DistanceReading{}
	mi := &file_types_devices_sensors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistanceReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistanceReading) ProtoMessage() {}

func (x *DistanceReading) ProtoReflect() protoreflect.Message {
	mi := &file_types_devices_sensors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistanceReading.ProtoReflect.Descriptor instead.
func (*DistanceReading) Descriptor() ([]byte, []int) {
	return file_types_devices_sensors_proto_rawDescGZIP(), []int{1}
}

func (x *DistanceReading) GetDistanceMm() float32 {
	if x != nil {
		return x.DistanceMm
	}
	return 0
}

func (x *DistanceReading) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *DistanceReading) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// TemperatureReading represents temperature sensor readings
type TemperatureReading struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemperatureC  float32                `protobuf:"fixed32,1,opt,name=temperature_c,json=temperatureC,proto3" json:"temperature_c,omitempty"` // Temperature in Celsius
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                            // Timestamp in nanoseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemperatureReading) Reset() {
	*x = TemperatureReading{}
	mi := &file_types_devices_sensors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemperatureReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemperatureReading) ProtoMessage() {}

func (x *TemperatureReading) ProtoReflect() protoreflect.Message {
	mi := &file_types_devices_sensors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemperatureReading.ProtoReflect.Descriptor instead.
func (*TemperatureReading) Descriptor() ([]byte, []int) {
	return file_types_devices_sensors_proto_rawDescGZIP(), []int{2}
}

func (x *TemperatureReading) GetTemperatureC() float32 {
	if x != nil {
		return x.TemperatureC
	}
	return 0
}

func (x *TemperatureReading) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// PressureReading represents pressure sensor readings
type PressureReading struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PressurePa    float32                `protobuf:"fixed32,1,opt,name=pressure_pa,json=pressurePa,proto3" json:"pressure_pa,omitempty"` // Pressure in Pascals
	AltitudeM     float32                `protobuf:"fixed32,2,opt,name=altitude_m,json=altitudeM,proto3" json:"altitude_m,omitempty"`    // Altitude in meters (calculated)
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                      // Timestamp in nanoseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PressureReading) Reset() {
	*x = PressureReading{}
	mi := &file_types_devices_sensors_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PressureReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PressureReading) ProtoMessage() {}

func (x *PressureReading) ProtoReflect() protoreflect.Message {
	mi := &file_types_devices_sensors_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PressureReading.ProtoReflect.Descriptor instead.
func (*PressureReading) Descriptor() ([]byte, []int) {
	return file_types_devices_sensors_proto_rawDescGZIP(), []int{3}
}

func (x *PressureReading) GetPressurePa() float32 {
	if x != nil {
		return x.PressurePa
	}
	return 0
}

func (x *PressureReading) GetAltitudeM() float32 {
	if x != nil {
		return x.AltitudeM
	}
	return 0
}

func (x *PressureReading) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// GPSReading represents GPS sensor readings
type GPSReading struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`                       // Latitude in decimal degrees
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`                     // Longitude in decimal degrees
	AltitudeM     float64                `protobuf:"fixed64,3,opt,name=altitude_m,json=altitudeM,proto3" json:"altitude_m,omitempty"`    // Altitude in meters
	AccuracyM     float32                `protobuf:"fixed32,4,opt,name=accuracy_m,json=accuracyM,proto3" json:"accuracy_m,omitempty"`    // Horizontal position accuracy estimate (meters)
	SpeedMps      float32                `protobuf:"fixed32,5,opt,name=speed_mps,json=speedMps,proto3" json:"speed_mps,omitempty"`       // Speed over ground (m/s)
	BearingDeg    float32                `protobuf:"fixed32,6,opt,name=bearing_deg,json=bearingDeg,proto3" json:"bearing_deg,omitempty"` // Course/bearing (degrees from north)
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                      // Timestamp in nanoseconds
	Satellites    uint32                 `protobuf:"varint,8,opt,name=satellites,proto3" json:"satellites,omitempty"`                    // Number of satellites used
	FixValid      bool                   `protobuf:"varint,9,opt,name=fix_valid,json=fixValid,proto3" json:"fix_valid,omitempty"`        // Fix is valid (true if GPS fix acquired)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPSReading) Reset() {
	*x = GPSReading{}
	mi := &file_types_devices_sensors_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPSReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPSReading) ProtoMessage() {}

func (x *GPSReading) ProtoReflect() protoreflect.Message {
	mi := &file_types_devices_sensors_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPSReading.ProtoReflect.Descriptor instead.
func (*GPSReading) Descriptor() ([]byte, []int) {
	return file_types_devices_sensors_proto_rawDescGZIP(), []int{4}
}

func (x *GPSReading) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GPSReading) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GPSReading) GetAltitudeM() float64 {
	if x != nil {
		return x.AltitudeM
	}
	return 0
}

func (x *GPSReading) GetAccuracyM() float32 {
	if x != nil {
		return x.AccuracyM
	}
	return 0
}

func (x *GPSReading) GetSpeedMps() float32 {
	if x != nil {
		return x.SpeedMps
	}
	return 0
}

func (x *GPSReading) GetBearingDeg() float32 {
	if x != nil {
		return x.BearingDeg
	}
	return 0
}

func (x *GPSReading) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GPSReading) GetSatellites() uint32 {
	if x != nil {
		return x.Satellites
	}
	return 0
}

func (x *GPSReading) GetFixValid() bool {
	if x != nil {
		return x.FixValid
	}
	return false
}

// LIDARReading represents LIDAR sensor readings (single scan)
type LIDARReading struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DistancesMm   []float32              `protobuf:"fixed32,1,rep,packed,name=distances_mm,json=distancesMm,proto3" json:"distances_mm,omitempty"` // Distance readings (mm) for each angle step
	AnglesDeg     []float32              `protobuf:"fixed32,2,rep,packed,name=angles_deg,json=anglesDeg,proto3" json:"angles_deg,omitempty"`       // Corresponding angles (degrees)
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                // Timestamp in nanoseconds
	Valid         bool                   `protobuf:"varint,4,opt,name=valid,proto3" json:"valid,omitempty"`                                        // If reading is valid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LIDARReading) Reset() {
	*x = LIDARReading{}
	mi := &file_types_devices_sensors_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LIDARReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LIDARReading) ProtoMessage() {}

func (x *LIDARReading) ProtoReflect() protoreflect.Message {
	mi := &file_types_devices_sensors_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LIDARReading.ProtoReflect.Descriptor instead.
func (*LIDARReading) Descriptor() ([]byte, []int) {
	return file_types_devices_sensors_proto_rawDescGZIP(), []int{5}
}

func (x *LIDARReading) GetDistancesMm() []float32 {
	if x != nil {
		return x.DistancesMm
	}
	return nil
}

func (x *LIDARReading) GetAnglesDeg() []float32 {
	if x != nil {
		return x.AnglesDeg
	}
	return nil
}

func (x *LIDARReading) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LIDARReading) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// SensorReading represents a generic sensor reading (oneof all sensor types)
type SensorReading struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of sensor reading
	//
	// Types that are valid to be assigned to Reading:
	//
	//	*SensorReading_Encoder
	//	*SensorReading_Imu
	//	*SensorReading_Distance
	//	*SensorReading_Temperature
	//	*SensorReading_Pressure
	//	*SensorReading_Gps
	//	*SensorReading_Lidar
	Reading       isSensorReading_Reading `protobuf_oneof:"reading"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorReading) Reset() {
	*x = SensorReading{}
	mi := &file_types_devices_sensors_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorReading) ProtoMessage() {}

func (x *SensorReading) ProtoReflect() protoreflect.Message {
	mi := &file_types_devices_sensors_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorReading.ProtoReflect.Descriptor instead.
func (*SensorReading) Descriptor() ([]byte, []int) {
	return file_types_devices_sensors_proto_rawDescGZIP(), []int{6}
}

func (x *SensorReading) GetReading() isSensorReading_Reading {
	if x != nil {
		return x.Reading
	}
	return nil
}

func (x *SensorReading) GetEncoder() *EncoderReading {
	if x != nil {
		if x, ok := x.Reading.(*SensorReading_Encoder); ok {
			return x.Encoder
		}
	}
	return nil
}

func (x *SensorReading) GetImu() *IMUReading {
	if x != nil {
		if x, ok := x.Reading.(*SensorReading_Imu); ok {
			return x.Imu
		}
	}
	return nil
}

func (x *SensorReading) GetDistance() *DistanceReading {
	if x != nil {
		if x, ok := x.Reading.(*SensorReading_Distance); ok {
			return x.Distance
		}
	}
	return nil
}

func (x *SensorReading) GetTemperature() *TemperatureReading {
	if x != nil {
		if x, ok := x.Reading.(*SensorReading_Temperature); ok {
			return x.Temperature
		}
	}
	return nil
}

func (x *SensorReading) GetPressure() *PressureReading {
	if x != nil {
		if x, ok := x.Reading.(*SensorReading_Pressure); ok {
			return x.Pressure
		}
	}
	return nil
}

func (x *SensorReading) GetGps() *GPSReading {
	if x != nil {
		if x, ok := x.Reading.(*SensorReading_Gps); ok {
			return x.Gps
		}
	}
	return nil
}

func (x *SensorReading) GetLidar() *LIDARReading {
	if x != nil {
		if x, ok := x.Reading.(*SensorReading_Lidar); ok {
			return x.Lidar
		}
	}
	return nil
}

type isSensorReading_Reading interface {
	isSensorReading_Reading()
}

type SensorReading_Encoder struct {
	Encoder *EncoderReading `protobuf:"bytes,1,opt,name=encoder,proto3,oneof"`
}

type SensorReading_Imu struct {
	Imu *IMUReading `protobuf:"bytes,2,opt,name=imu,proto3,oneof"`
}

type SensorReading_Distance struct {
	Distance *DistanceReading `protobuf:"bytes,3,opt,name=distance,proto3,oneof"`
}

type SensorReading_Temperature struct {
	Temperature *TemperatureReading `protobuf:"bytes,4,opt,name=temperature,proto3,oneof"`
}

type SensorReading_Pressure struct {
	Pressure *PressureReading `protobuf:"bytes,5,opt,name=pressure,proto3,oneof"`
}

type SensorReading_Gps struct {
	Gps *GPSReading `protobuf:"bytes,6,opt,name=gps,proto3,oneof"`
}

type SensorReading_Lidar struct {
	Lidar *LIDARReading `protobuf:"bytes,7,opt,name=lidar,proto3,oneof"`
}

func (*SensorReading_Encoder) isSensorReading_Reading() {}

func (*SensorReading_Imu) isSensorReading_Reading() {}

func (*SensorReading_Distance) isSensorReading_Reading() {}

func (*SensorReading_Temperature) isSensorReading_Reading() {}

func (*SensorReading_Pressure) isSensorReading_Reading() {}

func (*SensorReading_Gps) isSensorReading_Reading() {}

func (*SensorReading_Lidar) isSensorReading_Reading() {}

var File_types_devices_sensors_proto protoreflect.FileDescriptor

const file_types_devices_sensors_proto_rawDesc = "" +
	"\n" +
	"\x1btypes/devices/sensors.proto\x12\rtypes.devices\x1a\x18types/math/vectors.proto\x1a\x1btypes/devices/encoder.proto\"\x84\x02\n" +
	"\n" +
	"IMUReading\x128\n" +
	"\facceleration\x18\x01 \x01(\v2\x14.types.math.Vector3DR\facceleration\x12?\n" +
	"\x10angular_velocity\x18\x02 \x01(\v2\x14.types.math.Vector3DR\x0fangularVelocity\x12;\n" +
	"\x0emagnetic_field\x18\x03 \x01(\v2\x14.types.math.Vector3DR\rmagneticField\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x02R\vtemperature\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"f\n" +
	"\x0fDistanceReading\x12\x1f\n" +
	"\vdistance_mm\x18\x01 \x01(\x02R\n" +
	"distanceMm\x12\x14\n" +
	"\x05valid\x18\x02 \x01(\bR\x05valid\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"W\n" +
	"\x12TemperatureReading\x12#\n" +
	"\rtemperature_c\x18\x01 \x01(\x02R\ftemperatureC\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"o\n" +
	"\x0fPressureReading\x12\x1f\n" +
	"\vpressure_pa\x18\x01 \x01(\x02R\n" +
	"pressurePa\x12\x1d\n" +
	"\n" +
	"altitude_m\x18\x02 \x01(\x02R\taltitudeM\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x9d\x02\n" +
	"\n" +
	"GPSReading\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1d\n" +
	"\n" +
	"altitude_m\x18\x03 \x01(\x01R\taltitudeM\x12\x1d\n" +
	"\n" +
	"accuracy_m\x18\x04 \x01(\x02R\taccuracyM\x12\x1b\n" +
	"\tspeed_mps\x18\x05 \x01(\x02R\bspeedMps\x12\x1f\n" +
	"\vbearing_deg\x18\x06 \x01(\x02R\n" +
	"bearingDeg\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x1e\n" +
	"\n" +
	"satellites\x18\b \x01(\rR\n" +
	"satellites\x12\x1b\n" +
	"\tfix_valid\x18\t \x01(\bR\bfixValid\"\x84\x01\n" +
	"\fLIDARReading\x12!\n" +
	"\fdistances_mm\x18\x01 \x03(\x02R\vdistancesMm\x12\x1d\n" +
	"\n" +
	"angles_deg\x18\x02 \x03(\x02R\tanglesDeg\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05valid\x18\x04 \x01(\bR\x05valid\"\xab\x03\n" +
	"\rSensorReading\x129\n" +
	"\aencoder\x18\x01 \x01(\v2\x1d.types.devices.EncoderReadingH\x00R\aencoder\x12-\n" +
	"\x03imu\x18\x02 \x01(\v2\x19.types.devices.IMUReadingH\x00R\x03imu\x12<\n" +
	"\bdistance\x18\x03 \x01(\v2\x1e.types.devices.DistanceReadingH\x00R\bdistance\x12E\n" +
	"\vtemperature\x18\x04 \x01(\v2!.types.devices.TemperatureReadingH\x00R\vtemperature\x12<\n" +
	"\bpressure\x18\x05 \x01(\v2\x1e.types.devices.PressureReadingH\x00R\bpressure\x12-\n" +
	"\x03gps\x18\x06 \x01(\v2\x19.types.devices.GPSReadingH\x00R\x03gps\x123\n" +
	"\x05lidar\x18\a \x01(\v2\x1b.types.devices.LIDARReadingH\x00R\x05lidarB\t\n" +
	"\areadingB\xa1\x01\n" +
	"\x11com.types.devicesB\fSensorsProtoP\x01Z)github.com/itohio/EasyRobot/types/devices\xa2\x02\x03TDX\xaa\x02\rTypes.Devices\xca\x02\rTypes\\Devices\xe2\x02\x19Types\\Devices\\GPBMetadata\xea\x02\x0eTypes::Devicesb\x06proto3"

var (
	file_types_devices_sensors_proto_rawDescOnce sync.Once
	file_types_devices_sensors_proto_rawDescData []byte
)

func file_types_devices_sensors_proto_rawDescGZIP() []byte {
	file_types_devices_sensors_proto_rawDescOnce.Do(func() {
		file_types_devices_sensors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_devices_sensors_proto_rawDesc), len(file_types_devices_sensors_proto_rawDesc)))
	})
	return file_types_devices_sensors_proto_rawDescData
}

var file_types_devices_sensors_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_types_devices_sensors_proto_goTypes = []any{
	(*IMUReading)(nil),         // 0: types.devices.IMUReading
	(*DistanceReading)(nil),    // 1: types.devices.DistanceReading
	(*TemperatureReading)(nil), // 2: types.devices.TemperatureReading
	(*PressureReading)(nil),    // 3: types.devices.PressureReading
	(*GPSReading)(nil),         // 4: types.devices.GPSReading
	(*LIDARReading)(nil),       // 5: types.devices.LIDARReading
	(*SensorReading)(nil),      // 6: types.devices.SensorReading
	(*math.Vector3D)(nil),      // 7: types.math.Vector3D
	(*EncoderReading)(nil),     // 8: types.devices.EncoderReading
}
var file_types_devices_sensors_proto_depIdxs = []int32{
	7,  // 0: types.devices.IMUReading.acceleration:type_name -> types.math.Vector3D
	7,  // 1: types.devices.IMUReading.angular_velocity:type_name -> types.math.Vector3D
	7,  // 2: types.devices.IMUReading.magnetic_field:type_name -> types.math.Vector3D
	8,  // 3: types.devices.SensorReading.encoder:type_name -> types.devices.EncoderReading
	0,  // 4: types.devices.SensorReading.imu:type_name -> types.devices.IMUReading
	1,  // 5: types.devices.SensorReading.distance:type_name -> types.devices.DistanceReading
	2,  // 6: types.devices.SensorReading.temperature:type_name -> types.devices.TemperatureReading
	3,  // 7: types.devices.SensorReading.pressure:type_name -> types.devices.PressureReading
	4,  // 8: types.devices.SensorReading.gps:type_name -> types.devices.GPSReading
	5,  // 9: types.devices.SensorReading.lidar:type_name -> types.devices.LIDARReading
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_types_devices_sensors_proto_init() }
func file_types_devices_sensors_proto_init() {
	if File_types_devices_sensors_proto != nil {
		return
	}
	file_types_devices_encoder_proto_init()
	file_types_devices_sensors_proto_msgTypes[6].OneofWrappers = []any{
		(*SensorReading_Encoder)(nil),
		(*SensorReading_Imu)(nil),
		(*SensorReading_Distance)(nil),
		(*SensorReading_Temperature)(nil),
		(*SensorReading_Pressure)(nil),
		(*SensorReading_Gps)(nil),
		(*SensorReading_Lidar)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_devices_sensors_proto_rawDesc), len(file_types_devices_sensors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_devices_sensors_proto_goTypes,
		DependencyIndexes: file_types_devices_sensors_proto_depIdxs,
		MessageInfos:      file_types_devices_sensors_proto_msgTypes,
	}.Build()
	File_types_devices_sensors_proto = out.File
	file_types_devices_sensors_proto_goTypes = nil
	file_types_devices_sensors_proto_depIdxs = nil
}
