// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: types/devices/servo.proto

package devices

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServoConfig represents configuration for a single servo motor
type ServoConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pin           uint32                 `protobuf:"varint,1,opt,name=pin,proto3" json:"pin,omitempty"`                                        // GPIO pin number
	MinUs         float32                `protobuf:"fixed32,2,opt,name=min_us,json=minUs,proto3" json:"min_us,omitempty"`                      // Minimum pulse width in microseconds
	MaxUs         float32                `protobuf:"fixed32,3,opt,name=max_us,json=maxUs,proto3" json:"max_us,omitempty"`                      // Maximum pulse width in microseconds
	DefaultUs     float32                `protobuf:"fixed32,4,opt,name=default_us,json=defaultUs,proto3" json:"default_us,omitempty"`          // Default/center pulse width in microseconds
	MaxAngle      float32                `protobuf:"fixed32,5,opt,name=max_angle,json=maxAngle,proto3" json:"max_angle,omitempty"`             // Maximum angle in degrees
	DefaultAngle  float32                `protobuf:"fixed32,6,opt,name=default_angle,json=defaultAngle,proto3" json:"default_angle,omitempty"` // Default angle in degrees
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServoConfig) Reset() {
	*x = ServoConfig{}
	mi := &file_types_devices_servo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServoConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServoConfig) ProtoMessage() {}

func (x *ServoConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_devices_servo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServoConfig.ProtoReflect.Descriptor instead.
func (*ServoConfig) Descriptor() ([]byte, []int) {
	return file_types_devices_servo_proto_rawDescGZIP(), []int{0}
}

func (x *ServoConfig) GetPin() uint32 {
	if x != nil {
		return x.Pin
	}
	return 0
}

func (x *ServoConfig) GetMinUs() float32 {
	if x != nil {
		return x.MinUs
	}
	return 0
}

func (x *ServoConfig) GetMaxUs() float32 {
	if x != nil {
		return x.MaxUs
	}
	return 0
}

func (x *ServoConfig) GetDefaultUs() float32 {
	if x != nil {
		return x.DefaultUs
	}
	return 0
}

func (x *ServoConfig) GetMaxAngle() float32 {
	if x != nil {
		return x.MaxAngle
	}
	return 0
}

func (x *ServoConfig) GetDefaultAngle() float32 {
	if x != nil {
		return x.DefaultAngle
	}
	return 0
}

// ServoState represents current state of a servo motor
type ServoState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentAngle  float32                `protobuf:"fixed32,1,opt,name=current_angle,json=currentAngle,proto3" json:"current_angle,omitempty"`   // Current angle in degrees
	TargetAngle   float32                `protobuf:"fixed32,2,opt,name=target_angle,json=targetAngle,proto3" json:"target_angle,omitempty"`      // Target angle in degrees
	PulseWidthUs  float32                `protobuf:"fixed32,3,opt,name=pulse_width_us,json=pulseWidthUs,proto3" json:"pulse_width_us,omitempty"` // Current pulse width in microseconds
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                              // Timestamp in nanoseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServoState) Reset() {
	*x = ServoState{}
	mi := &file_types_devices_servo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServoState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServoState) ProtoMessage() {}

func (x *ServoState) ProtoReflect() protoreflect.Message {
	mi := &file_types_devices_servo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServoState.ProtoReflect.Descriptor instead.
func (*ServoState) Descriptor() ([]byte, []int) {
	return file_types_devices_servo_proto_rawDescGZIP(), []int{1}
}

func (x *ServoState) GetCurrentAngle() float32 {
	if x != nil {
		return x.CurrentAngle
	}
	return 0
}

func (x *ServoState) GetTargetAngle() float32 {
	if x != nil {
		return x.TargetAngle
	}
	return 0
}

func (x *ServoState) GetPulseWidthUs() float32 {
	if x != nil {
		return x.PulseWidthUs
	}
	return 0
}

func (x *ServoState) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ServoAngleCommand represents an angle command for a servo
type ServoAngleCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Angle         float32                `protobuf:"fixed32,1,opt,name=angle,proto3" json:"angle,omitempty"`        // Target angle in degrees (0 to MaxAngle)
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Timestamp in nanoseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServoAngleCommand) Reset() {
	*x = ServoAngleCommand{}
	mi := &file_types_devices_servo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServoAngleCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServoAngleCommand) ProtoMessage() {}

func (x *ServoAngleCommand) ProtoReflect() protoreflect.Message {
	mi := &file_types_devices_servo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServoAngleCommand.ProtoReflect.Descriptor instead.
func (*ServoAngleCommand) Descriptor() ([]byte, []int) {
	return file_types_devices_servo_proto_rawDescGZIP(), []int{2}
}

func (x *ServoAngleCommand) GetAngle() float32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

func (x *ServoAngleCommand) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ServoArrayConfig represents configuration for an array of servos
type ServoArrayConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servos        []*ServoConfig         `protobuf:"bytes,1,rep,name=servos,proto3" json:"servos,omitempty"` // Servo configurations
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServoArrayConfig) Reset() {
	*x = ServoArrayConfig{}
	mi := &file_types_devices_servo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServoArrayConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServoArrayConfig) ProtoMessage() {}

func (x *ServoArrayConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_devices_servo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServoArrayConfig.ProtoReflect.Descriptor instead.
func (*ServoArrayConfig) Descriptor() ([]byte, []int) {
	return file_types_devices_servo_proto_rawDescGZIP(), []int{3}
}

func (x *ServoArrayConfig) GetServos() []*ServoConfig {
	if x != nil {
		return x.Servos
	}
	return nil
}

// ServoArrayState represents current state of an array of servos
type ServoArrayState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servos        []*ServoState          `protobuf:"bytes,1,rep,name=servos,proto3" json:"servos,omitempty"`        // Servo states
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Timestamp in nanoseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServoArrayState) Reset() {
	*x = ServoArrayState{}
	mi := &file_types_devices_servo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServoArrayState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServoArrayState) ProtoMessage() {}

func (x *ServoArrayState) ProtoReflect() protoreflect.Message {
	mi := &file_types_devices_servo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServoArrayState.ProtoReflect.Descriptor instead.
func (*ServoArrayState) Descriptor() ([]byte, []int) {
	return file_types_devices_servo_proto_rawDescGZIP(), []int{4}
}

func (x *ServoArrayState) GetServos() []*ServoState {
	if x != nil {
		return x.Servos
	}
	return nil
}

func (x *ServoArrayState) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ServoArrayAngleCommand represents angle commands for an array of servos
type ServoArrayAngleCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Angles        []float32              `protobuf:"fixed32,1,rep,packed,name=angles,proto3" json:"angles,omitempty"` // Target angles in degrees (one per servo)
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`   // Timestamp in nanoseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServoArrayAngleCommand) Reset() {
	*x = ServoArrayAngleCommand{}
	mi := &file_types_devices_servo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServoArrayAngleCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServoArrayAngleCommand) ProtoMessage() {}

func (x *ServoArrayAngleCommand) ProtoReflect() protoreflect.Message {
	mi := &file_types_devices_servo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServoArrayAngleCommand.ProtoReflect.Descriptor instead.
func (*ServoArrayAngleCommand) Descriptor() ([]byte, []int) {
	return file_types_devices_servo_proto_rawDescGZIP(), []int{5}
}

func (x *ServoArrayAngleCommand) GetAngles() []float32 {
	if x != nil {
		return x.Angles
	}
	return nil
}

func (x *ServoArrayAngleCommand) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_types_devices_servo_proto protoreflect.FileDescriptor

const file_types_devices_servo_proto_rawDesc = "" +
	"\n" +
	"\x19types/devices/servo.proto\x12\rtypes.devices\"\xae\x01\n" +
	"\vServoConfig\x12\x10\n" +
	"\x03pin\x18\x01 \x01(\rR\x03pin\x12\x15\n" +
	"\x06min_us\x18\x02 \x01(\x02R\x05minUs\x12\x15\n" +
	"\x06max_us\x18\x03 \x01(\x02R\x05maxUs\x12\x1d\n" +
	"\n" +
	"default_us\x18\x04 \x01(\x02R\tdefaultUs\x12\x1b\n" +
	"\tmax_angle\x18\x05 \x01(\x02R\bmaxAngle\x12#\n" +
	"\rdefault_angle\x18\x06 \x01(\x02R\fdefaultAngle\"\x98\x01\n" +
	"\n" +
	"ServoState\x12#\n" +
	"\rcurrent_angle\x18\x01 \x01(\x02R\fcurrentAngle\x12!\n" +
	"\ftarget_angle\x18\x02 \x01(\x02R\vtargetAngle\x12$\n" +
	"\x0epulse_width_us\x18\x03 \x01(\x02R\fpulseWidthUs\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"G\n" +
	"\x11ServoAngleCommand\x12\x14\n" +
	"\x05angle\x18\x01 \x01(\x02R\x05angle\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"F\n" +
	"\x10ServoArrayConfig\x122\n" +
	"\x06servos\x18\x01 \x03(\v2\x1a.types.devices.ServoConfigR\x06servos\"b\n" +
	"\x0fServoArrayState\x121\n" +
	"\x06servos\x18\x01 \x03(\v2\x19.types.devices.ServoStateR\x06servos\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"N\n" +
	"\x16ServoArrayAngleCommand\x12\x16\n" +
	"\x06angles\x18\x01 \x03(\x02R\x06angles\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestampB\x9f\x01\n" +
	"\x11com.types.devicesB\n" +
	"ServoProtoP\x01Z)github.com/itohio/EasyRobot/types/devices\xa2\x02\x03TDX\xaa\x02\rTypes.Devices\xca\x02\rTypes\\Devices\xe2\x02\x19Types\\Devices\\GPBMetadata\xea\x02\x0eTypes::Devicesb\x06proto3"

var (
	file_types_devices_servo_proto_rawDescOnce sync.Once
	file_types_devices_servo_proto_rawDescData []byte
)

func file_types_devices_servo_proto_rawDescGZIP() []byte {
	file_types_devices_servo_proto_rawDescOnce.Do(func() {
		file_types_devices_servo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_devices_servo_proto_rawDesc), len(file_types_devices_servo_proto_rawDesc)))
	})
	return file_types_devices_servo_proto_rawDescData
}

var file_types_devices_servo_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_types_devices_servo_proto_goTypes = []any{
	(*ServoConfig)(nil),            // 0: types.devices.ServoConfig
	(*ServoState)(nil),             // 1: types.devices.ServoState
	(*ServoAngleCommand)(nil),      // 2: types.devices.ServoAngleCommand
	(*ServoArrayConfig)(nil),       // 3: types.devices.ServoArrayConfig
	(*ServoArrayState)(nil),        // 4: types.devices.ServoArrayState
	(*ServoArrayAngleCommand)(nil), // 5: types.devices.ServoArrayAngleCommand
}
var file_types_devices_servo_proto_depIdxs = []int32{
	0, // 0: types.devices.ServoArrayConfig.servos:type_name -> types.devices.ServoConfig
	1, // 1: types.devices.ServoArrayState.servos:type_name -> types.devices.ServoState
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_types_devices_servo_proto_init() }
func file_types_devices_servo_proto_init() {
	if File_types_devices_servo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_devices_servo_proto_rawDesc), len(file_types_devices_servo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_devices_servo_proto_goTypes,
		DependencyIndexes: file_types_devices_servo_proto_depIdxs,
		MessageInfos:      file_types_devices_servo_proto_msgTypes,
	}.Build()
	File_types_devices_servo_proto = out.File
	file_types_devices_servo_proto_goTypes = nil
	file_types_devices_servo_proto_depIdxs = nil
}
