// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: types/interaction/messages.proto

package interaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType represents the type of user message
type MessageType int32

const (
	// Unknown/unspecified message type
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	// Text message/command
	MessageType_MESSAGE_TYPE_TEXT MessageType = 1
	// Command message
	MessageType_MESSAGE_TYPE_COMMAND MessageType = 2
	// Query message
	MessageType_MESSAGE_TYPE_QUERY MessageType = 3
	// Notification message
	MessageType_MESSAGE_TYPE_NOTIFICATION MessageType = 4
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_TEXT",
		2: "MESSAGE_TYPE_COMMAND",
		3: "MESSAGE_TYPE_QUERY",
		4: "MESSAGE_TYPE_NOTIFICATION",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED":  0,
		"MESSAGE_TYPE_TEXT":         1,
		"MESSAGE_TYPE_COMMAND":      2,
		"MESSAGE_TYPE_QUERY":        3,
		"MESSAGE_TYPE_NOTIFICATION": 4,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_types_interaction_messages_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_types_interaction_messages_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_types_interaction_messages_proto_rawDescGZIP(), []int{0}
}

// UserMessage represents a user message or command in text form
type UserMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=types.interaction.MessageType" json:"type,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`                                                                                   // Message text content
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`                                                                             // Command name (if type is COMMAND)
	Arguments     []string               `protobuf:"bytes,4,rep,name=arguments,proto3" json:"arguments,omitempty"`                                                                         // Command arguments
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                        // Timestamp in nanoseconds
	UserId        string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                                 // User identifier
	SessionId     string                 `protobuf:"bytes,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                                        // Session identifier
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMessage) Reset() {
	*x = UserMessage{}
	mi := &file_types_interaction_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMessage) ProtoMessage() {}

func (x *UserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_types_interaction_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMessage.ProtoReflect.Descriptor instead.
func (*UserMessage) Descriptor() ([]byte, []int) {
	return file_types_interaction_messages_proto_rawDescGZIP(), []int{0}
}

func (x *UserMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *UserMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *UserMessage) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *UserMessage) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *UserMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *UserMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UserMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_types_interaction_messages_proto protoreflect.FileDescriptor

const file_types_interaction_messages_proto_rawDesc = "" +
	"\n" +
	" types/interaction/messages.proto\x12\x11types.interaction\"\xea\x02\n" +
	"\vUserMessage\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.types.interaction.MessageTypeR\x04type\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x1c\n" +
	"\targuments\x18\x04 \x03(\tR\targuments\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\a \x01(\tR\tsessionId\x12H\n" +
	"\bmetadata\x18\b \x03(\v2,.types.interaction.UserMessage.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x93\x01\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MESSAGE_TYPE_TEXT\x10\x01\x12\x18\n" +
	"\x14MESSAGE_TYPE_COMMAND\x10\x02\x12\x16\n" +
	"\x12MESSAGE_TYPE_QUERY\x10\x03\x12\x1d\n" +
	"\x19MESSAGE_TYPE_NOTIFICATION\x10\x04B\xba\x01\n" +
	"\x15com.types.interactionB\rMessagesProtoP\x01Z-github.com/itohio/EasyRobot/types/interaction\xa2\x02\x03TIX\xaa\x02\x11Types.Interaction\xca\x02\x11Types\\Interaction\xe2\x02\x1dTypes\\Interaction\\GPBMetadata\xea\x02\x12Types::Interactionb\x06proto3"

var (
	file_types_interaction_messages_proto_rawDescOnce sync.Once
	file_types_interaction_messages_proto_rawDescData []byte
)

func file_types_interaction_messages_proto_rawDescGZIP() []byte {
	file_types_interaction_messages_proto_rawDescOnce.Do(func() {
		file_types_interaction_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_interaction_messages_proto_rawDesc), len(file_types_interaction_messages_proto_rawDesc)))
	})
	return file_types_interaction_messages_proto_rawDescData
}

var file_types_interaction_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_types_interaction_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_types_interaction_messages_proto_goTypes = []any{
	(MessageType)(0),    // 0: types.interaction.MessageType
	(*UserMessage)(nil), // 1: types.interaction.UserMessage
	nil,                 // 2: types.interaction.UserMessage.MetadataEntry
}
var file_types_interaction_messages_proto_depIdxs = []int32{
	0, // 0: types.interaction.UserMessage.type:type_name -> types.interaction.MessageType
	2, // 1: types.interaction.UserMessage.metadata:type_name -> types.interaction.UserMessage.MetadataEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_types_interaction_messages_proto_init() }
func file_types_interaction_messages_proto_init() {
	if File_types_interaction_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_interaction_messages_proto_rawDesc), len(file_types_interaction_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_interaction_messages_proto_goTypes,
		DependencyIndexes: file_types_interaction_messages_proto_depIdxs,
		EnumInfos:         file_types_interaction_messages_proto_enumTypes,
		MessageInfos:      file_types_interaction_messages_proto_msgTypes,
	}.Build()
	File_types_interaction_messages_proto = out.File
	file_types_interaction_messages_proto_goTypes = nil
	file_types_interaction_messages_proto_depIdxs = nil
}
