// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: types/control/kinematics/state.proto

package kinematics

import (
	math "github.com/itohio/EasyRobot/types/math"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IMUData represents IMU sensor data
type IMUData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acceleration  []float32              `protobuf:"fixed32,1,rep,packed,name=acceleration,proto3" json:"acceleration,omitempty"`                        // [ax, ay, az] (m/s²)
	AngularVel    []float32              `protobuf:"fixed32,2,rep,packed,name=angular_vel,json=angularVel,proto3" json:"angular_vel,omitempty"`          // [ωx, ωy, ωz] (rad/s)
	MagneticField []float32              `protobuf:"fixed32,3,rep,packed,name=magnetic_field,json=magneticField,proto3" json:"magnetic_field,omitempty"` // [mx, my, mz] (µT)
	Temperature   float32                `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`                                 // Temperature (°C)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IMUData) Reset() {
	*x = IMUData{}
	mi := &file_types_control_kinematics_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IMUData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMUData) ProtoMessage() {}

func (x *IMUData) ProtoReflect() protoreflect.Message {
	mi := &file_types_control_kinematics_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMUData.ProtoReflect.Descriptor instead.
func (*IMUData) Descriptor() ([]byte, []int) {
	return file_types_control_kinematics_state_proto_rawDescGZIP(), []int{0}
}

func (x *IMUData) GetAcceleration() []float32 {
	if x != nil {
		return x.Acceleration
	}
	return nil
}

func (x *IMUData) GetAngularVel() []float32 {
	if x != nil {
		return x.AngularVel
	}
	return nil
}

func (x *IMUData) GetMagneticField() []float32 {
	if x != nil {
		return x.MagneticField
	}
	return nil
}

func (x *IMUData) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

// BodyPose represents body pose for legged robots
type BodyPose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        float32                `protobuf:"fixed32,1,opt,name=height,proto3" json:"height,omitempty"` // Body height (m)
	Roll          float32                `protobuf:"fixed32,2,opt,name=roll,proto3" json:"roll,omitempty"`     // Roll angle (rad)
	Pitch         float32                `protobuf:"fixed32,3,opt,name=pitch,proto3" json:"pitch,omitempty"`   // Pitch angle (rad)
	Yaw           float32                `protobuf:"fixed32,4,opt,name=yaw,proto3" json:"yaw,omitempty"`       // Yaw angle (rad)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BodyPose) Reset() {
	*x = BodyPose{}
	mi := &file_types_control_kinematics_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BodyPose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyPose) ProtoMessage() {}

func (x *BodyPose) ProtoReflect() protoreflect.Message {
	mi := &file_types_control_kinematics_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyPose.ProtoReflect.Descriptor instead.
func (*BodyPose) Descriptor() ([]byte, []int) {
	return file_types_control_kinematics_state_proto_rawDescGZIP(), []int{1}
}

func (x *BodyPose) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BodyPose) GetRoll() float32 {
	if x != nil {
		return x.Roll
	}
	return 0
}

func (x *BodyPose) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *BodyPose) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

// Target represents a locomotion target
type Target struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LinearVelocity  []float32              `protobuf:"fixed32,1,rep,packed,name=linear_velocity,json=linearVelocity,proto3" json:"linear_velocity,omitempty"`    // [vx, vy, vz] (m/s)
	AngularVelocity []float32              `protobuf:"fixed32,2,rep,packed,name=angular_velocity,json=angularVelocity,proto3" json:"angular_velocity,omitempty"` // [ωx, ωy, ωz] (rad/s)
	Position        []float32              `protobuf:"fixed32,3,rep,packed,name=position,proto3" json:"position,omitempty"`                                      // [x, y, z] (m)
	Orientation     *math.Quaternion       `protobuf:"bytes,4,opt,name=orientation,proto3" json:"orientation,omitempty"`                                         // Quaternion [w, x, y, z]
	BodyPose        *BodyPose              `protobuf:"bytes,5,opt,name=body_pose,json=bodyPose,proto3" json:"body_pose,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_types_control_kinematics_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_types_control_kinematics_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_types_control_kinematics_state_proto_rawDescGZIP(), []int{2}
}

func (x *Target) GetLinearVelocity() []float32 {
	if x != nil {
		return x.LinearVelocity
	}
	return nil
}

func (x *Target) GetAngularVelocity() []float32 {
	if x != nil {
		return x.AngularVelocity
	}
	return nil
}

func (x *Target) GetPosition() []float32 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Target) GetOrientation() *math.Quaternion {
	if x != nil {
		return x.Orientation
	}
	return nil
}

func (x *Target) GetBodyPose() *BodyPose {
	if x != nil {
		return x.BodyPose
	}
	return nil
}

// SensorData represents sensor data for locomotion
type SensorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncoderTicks  []int32                `protobuf:"varint,1,rep,packed,name=encoder_ticks,json=encoderTicks,proto3" json:"encoder_ticks,omitempty"` // Wheel encoder readings
	JointAngles   []float32              `protobuf:"fixed32,2,rep,packed,name=joint_angles,json=jointAngles,proto3" json:"joint_angles,omitempty"`   // Joint angles (radians)
	Imu           *IMUData               `protobuf:"bytes,3,opt,name=imu,proto3" json:"imu,omitempty"`
	TouchSensors  []bool                 `protobuf:"varint,4,rep,packed,name=touch_sensors,json=touchSensors,proto3" json:"touch_sensors,omitempty"`  // Contact sensors
	ForceSensors  []float32              `protobuf:"fixed32,5,rep,packed,name=force_sensors,json=forceSensors,proto3" json:"force_sensors,omitempty"` // Force/torque readings
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorData) Reset() {
	*x = SensorData{}
	mi := &file_types_control_kinematics_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorData) ProtoMessage() {}

func (x *SensorData) ProtoReflect() protoreflect.Message {
	mi := &file_types_control_kinematics_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorData.ProtoReflect.Descriptor instead.
func (*SensorData) Descriptor() ([]byte, []int) {
	return file_types_control_kinematics_state_proto_rawDescGZIP(), []int{3}
}

func (x *SensorData) GetEncoderTicks() []int32 {
	if x != nil {
		return x.EncoderTicks
	}
	return nil
}

func (x *SensorData) GetJointAngles() []float32 {
	if x != nil {
		return x.JointAngles
	}
	return nil
}

func (x *SensorData) GetImu() *IMUData {
	if x != nil {
		return x.Imu
	}
	return nil
}

func (x *SensorData) GetTouchSensors() []bool {
	if x != nil {
		return x.TouchSensors
	}
	return nil
}

func (x *SensorData) GetForceSensors() []float32 {
	if x != nil {
		return x.ForceSensors
	}
	return nil
}

// State represents locomotion state
type State struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      []float32              `protobuf:"fixed32,1,rep,packed,name=position,proto3" json:"position,omitempty"`                            // [x, y, z] (m)
	Orientation   *math.Quaternion       `protobuf:"bytes,2,opt,name=orientation,proto3" json:"orientation,omitempty"`                               // Quaternion [w, x, y, z]
	Velocity      []float32              `protobuf:"fixed32,3,rep,packed,name=velocity,proto3" json:"velocity,omitempty"`                            // [vx, vy, vz] (m/s)
	JointAngles   []float32              `protobuf:"fixed32,4,rep,packed,name=joint_angles,json=jointAngles,proto3" json:"joint_angles,omitempty"`   // Joint angles (radians)
	ContactState  []bool                 `protobuf:"varint,5,rep,packed,name=contact_state,json=contactState,proto3" json:"contact_state,omitempty"` // Contact states
	Stability     float32                `protobuf:"fixed32,6,opt,name=stability,proto3" json:"stability,omitempty"`                                 // Stability metric (0-1)
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`                                           // Error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_types_control_kinematics_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_types_control_kinematics_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_types_control_kinematics_state_proto_rawDescGZIP(), []int{4}
}

func (x *State) GetPosition() []float32 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *State) GetOrientation() *math.Quaternion {
	if x != nil {
		return x.Orientation
	}
	return nil
}

func (x *State) GetVelocity() []float32 {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *State) GetJointAngles() []float32 {
	if x != nil {
		return x.JointAngles
	}
	return nil
}

func (x *State) GetContactState() []bool {
	if x != nil {
		return x.ContactState
	}
	return nil
}

func (x *State) GetStability() float32 {
	if x != nil {
		return x.Stability
	}
	return 0
}

func (x *State) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_types_control_kinematics_state_proto protoreflect.FileDescriptor

const file_types_control_kinematics_state_proto_rawDesc = "" +
	"\n" +
	"$types/control/kinematics/state.proto\x12\x18types.control.kinematics\x1a\x18types/math/vectors.proto\"\x97\x01\n" +
	"\aIMUData\x12\"\n" +
	"\facceleration\x18\x01 \x03(\x02R\facceleration\x12\x1f\n" +
	"\vangular_vel\x18\x02 \x03(\x02R\n" +
	"angularVel\x12%\n" +
	"\x0emagnetic_field\x18\x03 \x03(\x02R\rmagneticField\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x02R\vtemperature\"^\n" +
	"\bBodyPose\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x02R\x06height\x12\x12\n" +
	"\x04roll\x18\x02 \x01(\x02R\x04roll\x12\x14\n" +
	"\x05pitch\x18\x03 \x01(\x02R\x05pitch\x12\x10\n" +
	"\x03yaw\x18\x04 \x01(\x02R\x03yaw\"\xf3\x01\n" +
	"\x06Target\x12'\n" +
	"\x0flinear_velocity\x18\x01 \x03(\x02R\x0elinearVelocity\x12)\n" +
	"\x10angular_velocity\x18\x02 \x03(\x02R\x0fangularVelocity\x12\x1a\n" +
	"\bposition\x18\x03 \x03(\x02R\bposition\x128\n" +
	"\vorientation\x18\x04 \x01(\v2\x16.types.math.QuaternionR\vorientation\x12?\n" +
	"\tbody_pose\x18\x05 \x01(\v2\".types.control.kinematics.BodyPoseR\bbodyPose\"\xd3\x01\n" +
	"\n" +
	"SensorData\x12#\n" +
	"\rencoder_ticks\x18\x01 \x03(\x05R\fencoderTicks\x12!\n" +
	"\fjoint_angles\x18\x02 \x03(\x02R\vjointAngles\x123\n" +
	"\x03imu\x18\x03 \x01(\v2!.types.control.kinematics.IMUDataR\x03imu\x12#\n" +
	"\rtouch_sensors\x18\x04 \x03(\bR\ftouchSensors\x12#\n" +
	"\rforce_sensors\x18\x05 \x03(\x02R\fforceSensors\"\xf5\x01\n" +
	"\x05State\x12\x1a\n" +
	"\bposition\x18\x01 \x03(\x02R\bposition\x128\n" +
	"\vorientation\x18\x02 \x01(\v2\x16.types.math.QuaternionR\vorientation\x12\x1a\n" +
	"\bvelocity\x18\x03 \x03(\x02R\bvelocity\x12!\n" +
	"\fjoint_angles\x18\x04 \x03(\x02R\vjointAngles\x12#\n" +
	"\rcontact_state\x18\x05 \x03(\bR\fcontactState\x12\x1c\n" +
	"\tstability\x18\x06 \x01(\x02R\tstability\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05errorB\xe2\x01\n" +
	"\x1ccom.types.control.kinematicsB\n" +
	"StateProtoP\x01Z4github.com/itohio/EasyRobot/types/control/kinematics\xa2\x02\x03TCK\xaa\x02\x18Types.Control.Kinematics\xca\x02\x18Types\\Control\\Kinematics\xe2\x02$Types\\Control\\Kinematics\\GPBMetadata\xea\x02\x1aTypes::Control::Kinematicsb\x06proto3"

var (
	file_types_control_kinematics_state_proto_rawDescOnce sync.Once
	file_types_control_kinematics_state_proto_rawDescData []byte
)

func file_types_control_kinematics_state_proto_rawDescGZIP() []byte {
	file_types_control_kinematics_state_proto_rawDescOnce.Do(func() {
		file_types_control_kinematics_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_control_kinematics_state_proto_rawDesc), len(file_types_control_kinematics_state_proto_rawDesc)))
	})
	return file_types_control_kinematics_state_proto_rawDescData
}

var file_types_control_kinematics_state_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_types_control_kinematics_state_proto_goTypes = []any{
	(*IMUData)(nil),         // 0: types.control.kinematics.IMUData
	(*BodyPose)(nil),        // 1: types.control.kinematics.BodyPose
	(*Target)(nil),          // 2: types.control.kinematics.Target
	(*SensorData)(nil),      // 3: types.control.kinematics.SensorData
	(*State)(nil),           // 4: types.control.kinematics.State
	(*math.Quaternion)(nil), // 5: types.math.Quaternion
}
var file_types_control_kinematics_state_proto_depIdxs = []int32{
	5, // 0: types.control.kinematics.Target.orientation:type_name -> types.math.Quaternion
	1, // 1: types.control.kinematics.Target.body_pose:type_name -> types.control.kinematics.BodyPose
	0, // 2: types.control.kinematics.SensorData.imu:type_name -> types.control.kinematics.IMUData
	5, // 3: types.control.kinematics.State.orientation:type_name -> types.math.Quaternion
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_types_control_kinematics_state_proto_init() }
func file_types_control_kinematics_state_proto_init() {
	if File_types_control_kinematics_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_control_kinematics_state_proto_rawDesc), len(file_types_control_kinematics_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_control_kinematics_state_proto_goTypes,
		DependencyIndexes: file_types_control_kinematics_state_proto_depIdxs,
		MessageInfos:      file_types_control_kinematics_state_proto_msgTypes,
	}.Build()
	File_types_control_kinematics_state_proto = out.File
	file_types_control_kinematics_state_proto_goTypes = nil
	file_types_control_kinematics_state_proto_depIdxs = nil
}
