// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: types/control/kinematics/wheels.proto

package kinematics

import (
	math "github.com/itohio/EasyRobot/types/math"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DifferentialConfig represents differential drive configuration
type DifferentialConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WheelRadius     float32                `protobuf:"fixed32,1,opt,name=wheel_radius,json=wheelRadius,proto3" json:"wheel_radius,omitempty"`               // Wheel radius in meters
	BaseWidth       float32                `protobuf:"fixed32,2,opt,name=base_width,json=baseWidth,proto3" json:"base_width,omitempty"`                     // Distance between wheels in meters
	MaxLinearVel    float32                `protobuf:"fixed32,3,opt,name=max_linear_vel,json=maxLinearVel,proto3" json:"max_linear_vel,omitempty"`          // Maximum linear velocity (m/s)
	MaxAngularVel   float32                `protobuf:"fixed32,4,opt,name=max_angular_vel,json=maxAngularVel,proto3" json:"max_angular_vel,omitempty"`       // Maximum angular velocity (rad/s)
	EncoderCpr      uint32                 `protobuf:"varint,5,opt,name=encoder_cpr,json=encoderCpr,proto3" json:"encoder_cpr,omitempty"`                   // Encoder counts per revolution
	MaxAcceleration float32                `protobuf:"fixed32,6,opt,name=max_acceleration,json=maxAcceleration,proto3" json:"max_acceleration,omitempty"`   // Maximum linear acceleration (m/s²)
	MaxAngularAccel float32                `protobuf:"fixed32,7,opt,name=max_angular_accel,json=maxAngularAccel,proto3" json:"max_angular_accel,omitempty"` // Maximum angular acceleration (rad/s²)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DifferentialConfig) Reset() {
	*x = DifferentialConfig{}
	mi := &file_types_control_kinematics_wheels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DifferentialConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DifferentialConfig) ProtoMessage() {}

func (x *DifferentialConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_control_kinematics_wheels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DifferentialConfig.ProtoReflect.Descriptor instead.
func (*DifferentialConfig) Descriptor() ([]byte, []int) {
	return file_types_control_kinematics_wheels_proto_rawDescGZIP(), []int{0}
}

func (x *DifferentialConfig) GetWheelRadius() float32 {
	if x != nil {
		return x.WheelRadius
	}
	return 0
}

func (x *DifferentialConfig) GetBaseWidth() float32 {
	if x != nil {
		return x.BaseWidth
	}
	return 0
}

func (x *DifferentialConfig) GetMaxLinearVel() float32 {
	if x != nil {
		return x.MaxLinearVel
	}
	return 0
}

func (x *DifferentialConfig) GetMaxAngularVel() float32 {
	if x != nil {
		return x.MaxAngularVel
	}
	return 0
}

func (x *DifferentialConfig) GetEncoderCpr() uint32 {
	if x != nil {
		return x.EncoderCpr
	}
	return 0
}

func (x *DifferentialConfig) GetMaxAcceleration() float32 {
	if x != nil {
		return x.MaxAcceleration
	}
	return 0
}

func (x *DifferentialConfig) GetMaxAngularAccel() float32 {
	if x != nil {
		return x.MaxAngularAccel
	}
	return 0
}

// Wheel represents wheel configuration
type Wheel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Radius        float32                `protobuf:"fixed32,1,opt,name=radius,proto3" json:"radius,omitempty"`
	Position      *math.Vector2D         `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"` // Wheel position relative to base (x, y)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wheel) Reset() {
	*x = Wheel{}
	mi := &file_types_control_kinematics_wheels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wheel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wheel) ProtoMessage() {}

func (x *Wheel) ProtoReflect() protoreflect.Message {
	mi := &file_types_control_kinematics_wheels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wheel.ProtoReflect.Descriptor instead.
func (*Wheel) Descriptor() ([]byte, []int) {
	return file_types_control_kinematics_wheels_proto_rawDescGZIP(), []int{1}
}

func (x *Wheel) GetRadius() float32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *Wheel) GetPosition() *math.Vector2D {
	if x != nil {
		return x.Position
	}
	return nil
}

// MecanumConfig represents mecanum drive configuration
type MecanumConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wheels        []*Wheel               `protobuf:"bytes,1,rep,name=wheels,proto3" json:"wheels,omitempty"` // 4 wheels: front-left, front-right, rear-left, rear-right
	MaxLinearVel  float32                `protobuf:"fixed32,2,opt,name=max_linear_vel,json=maxLinearVel,proto3" json:"max_linear_vel,omitempty"`
	MaxAngularVel float32                `protobuf:"fixed32,3,opt,name=max_angular_vel,json=maxAngularVel,proto3" json:"max_angular_vel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MecanumConfig) Reset() {
	*x = MecanumConfig{}
	mi := &file_types_control_kinematics_wheels_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MecanumConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MecanumConfig) ProtoMessage() {}

func (x *MecanumConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_control_kinematics_wheels_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MecanumConfig.ProtoReflect.Descriptor instead.
func (*MecanumConfig) Descriptor() ([]byte, []int) {
	return file_types_control_kinematics_wheels_proto_rawDescGZIP(), []int{2}
}

func (x *MecanumConfig) GetWheels() []*Wheel {
	if x != nil {
		return x.Wheels
	}
	return nil
}

func (x *MecanumConfig) GetMaxLinearVel() float32 {
	if x != nil {
		return x.MaxLinearVel
	}
	return 0
}

func (x *MecanumConfig) GetMaxAngularVel() float32 {
	if x != nil {
		return x.MaxAngularVel
	}
	return 0
}

// Steer4Config represents 4-wheel steering configuration
type Steer4Config struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Wheels           []*Wheel               `protobuf:"bytes,1,rep,name=wheels,proto3" json:"wheels,omitempty"`                                                 // 4 wheels
	MaxSteeringAngle float32                `protobuf:"fixed32,2,opt,name=max_steering_angle,json=maxSteeringAngle,proto3" json:"max_steering_angle,omitempty"` // Maximum steering angle (radians)
	MaxLinearVel     float32                `protobuf:"fixed32,3,opt,name=max_linear_vel,json=maxLinearVel,proto3" json:"max_linear_vel,omitempty"`
	MaxAngularVel    float32                `protobuf:"fixed32,4,opt,name=max_angular_vel,json=maxAngularVel,proto3" json:"max_angular_vel,omitempty"`
	FrontSteerOnly   bool                   `protobuf:"varint,5,opt,name=front_steer_only,json=frontSteerOnly,proto3" json:"front_steer_only,omitempty"` // If true, only front wheels steer
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Steer4Config) Reset() {
	*x = Steer4Config{}
	mi := &file_types_control_kinematics_wheels_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Steer4Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Steer4Config) ProtoMessage() {}

func (x *Steer4Config) ProtoReflect() protoreflect.Message {
	mi := &file_types_control_kinematics_wheels_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Steer4Config.ProtoReflect.Descriptor instead.
func (*Steer4Config) Descriptor() ([]byte, []int) {
	return file_types_control_kinematics_wheels_proto_rawDescGZIP(), []int{3}
}

func (x *Steer4Config) GetWheels() []*Wheel {
	if x != nil {
		return x.Wheels
	}
	return nil
}

func (x *Steer4Config) GetMaxSteeringAngle() float32 {
	if x != nil {
		return x.MaxSteeringAngle
	}
	return 0
}

func (x *Steer4Config) GetMaxLinearVel() float32 {
	if x != nil {
		return x.MaxLinearVel
	}
	return 0
}

func (x *Steer4Config) GetMaxAngularVel() float32 {
	if x != nil {
		return x.MaxAngularVel
	}
	return 0
}

func (x *Steer4Config) GetFrontSteerOnly() bool {
	if x != nil {
		return x.FrontSteerOnly
	}
	return false
}

// Steer4DualConfig represents 4-wheel dual steering configuration (front and rear)
type Steer4DualConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Wheels           []*Wheel               `protobuf:"bytes,1,rep,name=wheels,proto3" json:"wheels,omitempty"` // 4 wheels
	MaxSteeringAngle float32                `protobuf:"fixed32,2,opt,name=max_steering_angle,json=maxSteeringAngle,proto3" json:"max_steering_angle,omitempty"`
	MaxLinearVel     float32                `protobuf:"fixed32,3,opt,name=max_linear_vel,json=maxLinearVel,proto3" json:"max_linear_vel,omitempty"`
	MaxAngularVel    float32                `protobuf:"fixed32,4,opt,name=max_angular_vel,json=maxAngularVel,proto3" json:"max_angular_vel,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Steer4DualConfig) Reset() {
	*x = Steer4DualConfig{}
	mi := &file_types_control_kinematics_wheels_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Steer4DualConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Steer4DualConfig) ProtoMessage() {}

func (x *Steer4DualConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_control_kinematics_wheels_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Steer4DualConfig.ProtoReflect.Descriptor instead.
func (*Steer4DualConfig) Descriptor() ([]byte, []int) {
	return file_types_control_kinematics_wheels_proto_rawDescGZIP(), []int{4}
}

func (x *Steer4DualConfig) GetWheels() []*Wheel {
	if x != nil {
		return x.Wheels
	}
	return nil
}

func (x *Steer4DualConfig) GetMaxSteeringAngle() float32 {
	if x != nil {
		return x.MaxSteeringAngle
	}
	return 0
}

func (x *Steer4DualConfig) GetMaxLinearVel() float32 {
	if x != nil {
		return x.MaxLinearVel
	}
	return 0
}

func (x *Steer4DualConfig) GetMaxAngularVel() float32 {
	if x != nil {
		return x.MaxAngularVel
	}
	return 0
}

// Steer6Config represents 6-wheel articulated steering configuration
type Steer6Config struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Wheels           []*Wheel               `protobuf:"bytes,1,rep,name=wheels,proto3" json:"wheels,omitempty"` // 6 wheels: front-left, front-right, mid-left, mid-right, rear-left, rear-right
	MaxSteeringAngle float32                `protobuf:"fixed32,2,opt,name=max_steering_angle,json=maxSteeringAngle,proto3" json:"max_steering_angle,omitempty"`
	MaxLinearVel     float32                `protobuf:"fixed32,3,opt,name=max_linear_vel,json=maxLinearVel,proto3" json:"max_linear_vel,omitempty"`
	MaxAngularVel    float32                `protobuf:"fixed32,4,opt,name=max_angular_vel,json=maxAngularVel,proto3" json:"max_angular_vel,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Steer6Config) Reset() {
	*x = Steer6Config{}
	mi := &file_types_control_kinematics_wheels_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Steer6Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Steer6Config) ProtoMessage() {}

func (x *Steer6Config) ProtoReflect() protoreflect.Message {
	mi := &file_types_control_kinematics_wheels_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Steer6Config.ProtoReflect.Descriptor instead.
func (*Steer6Config) Descriptor() ([]byte, []int) {
	return file_types_control_kinematics_wheels_proto_rawDescGZIP(), []int{5}
}

func (x *Steer6Config) GetWheels() []*Wheel {
	if x != nil {
		return x.Wheels
	}
	return nil
}

func (x *Steer6Config) GetMaxSteeringAngle() float32 {
	if x != nil {
		return x.MaxSteeringAngle
	}
	return 0
}

func (x *Steer6Config) GetMaxLinearVel() float32 {
	if x != nil {
		return x.MaxLinearVel
	}
	return 0
}

func (x *Steer6Config) GetMaxAngularVel() float32 {
	if x != nil {
		return x.MaxAngularVel
	}
	return 0
}

// WheelsConfig is a union type for different wheel configurations.
// Selects one of the supported wheel drive types.
type WheelsConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type selector for the wheel configuration
	//
	// Types that are valid to be assigned to Type:
	//
	//	*WheelsConfig_Differential
	//	*WheelsConfig_Mecanum
	//	*WheelsConfig_Steer4
	//	*WheelsConfig_Steer4Dual
	//	*WheelsConfig_Steer6
	Type          isWheelsConfig_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WheelsConfig) Reset() {
	*x = WheelsConfig{}
	mi := &file_types_control_kinematics_wheels_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WheelsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WheelsConfig) ProtoMessage() {}

func (x *WheelsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_control_kinematics_wheels_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WheelsConfig.ProtoReflect.Descriptor instead.
func (*WheelsConfig) Descriptor() ([]byte, []int) {
	return file_types_control_kinematics_wheels_proto_rawDescGZIP(), []int{6}
}

func (x *WheelsConfig) GetType() isWheelsConfig_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *WheelsConfig) GetDifferential() *DifferentialConfig {
	if x != nil {
		if x, ok := x.Type.(*WheelsConfig_Differential); ok {
			return x.Differential
		}
	}
	return nil
}

func (x *WheelsConfig) GetMecanum() *MecanumConfig {
	if x != nil {
		if x, ok := x.Type.(*WheelsConfig_Mecanum); ok {
			return x.Mecanum
		}
	}
	return nil
}

func (x *WheelsConfig) GetSteer4() *Steer4Config {
	if x != nil {
		if x, ok := x.Type.(*WheelsConfig_Steer4); ok {
			return x.Steer4
		}
	}
	return nil
}

func (x *WheelsConfig) GetSteer4Dual() *Steer4DualConfig {
	if x != nil {
		if x, ok := x.Type.(*WheelsConfig_Steer4Dual); ok {
			return x.Steer4Dual
		}
	}
	return nil
}

func (x *WheelsConfig) GetSteer6() *Steer6Config {
	if x != nil {
		if x, ok := x.Type.(*WheelsConfig_Steer6); ok {
			return x.Steer6
		}
	}
	return nil
}

type isWheelsConfig_Type interface {
	isWheelsConfig_Type()
}

type WheelsConfig_Differential struct {
	// Differential drive configuration
	Differential *DifferentialConfig `protobuf:"bytes,1,opt,name=differential,proto3,oneof"`
}

type WheelsConfig_Mecanum struct {
	// Mecanum drive configuration
	Mecanum *MecanumConfig `protobuf:"bytes,2,opt,name=mecanum,proto3,oneof"`
}

type WheelsConfig_Steer4 struct {
	// 4-wheel steering configuration
	Steer4 *Steer4Config `protobuf:"bytes,3,opt,name=steer4,proto3,oneof"`
}

type WheelsConfig_Steer4Dual struct {
	// 4-wheel dual steering configuration
	Steer4Dual *Steer4DualConfig `protobuf:"bytes,4,opt,name=steer4_dual,json=steer4Dual,proto3,oneof"`
}

type WheelsConfig_Steer6 struct {
	// 6-wheel articulated steering configuration
	Steer6 *Steer6Config `protobuf:"bytes,5,opt,name=steer6,proto3,oneof"`
}

func (*WheelsConfig_Differential) isWheelsConfig_Type() {}

func (*WheelsConfig_Mecanum) isWheelsConfig_Type() {}

func (*WheelsConfig_Steer4) isWheelsConfig_Type() {}

func (*WheelsConfig_Steer4Dual) isWheelsConfig_Type() {}

func (*WheelsConfig_Steer6) isWheelsConfig_Type() {}

var File_types_control_kinematics_wheels_proto protoreflect.FileDescriptor

const file_types_control_kinematics_wheels_proto_rawDesc = "" +
	"\n" +
	"%types/control/kinematics/wheels.proto\x12\x18types.control.kinematics\x1a\x18types/math/vectors.proto\"\x9c\x02\n" +
	"\x12DifferentialConfig\x12!\n" +
	"\fwheel_radius\x18\x01 \x01(\x02R\vwheelRadius\x12\x1d\n" +
	"\n" +
	"base_width\x18\x02 \x01(\x02R\tbaseWidth\x12$\n" +
	"\x0emax_linear_vel\x18\x03 \x01(\x02R\fmaxLinearVel\x12&\n" +
	"\x0fmax_angular_vel\x18\x04 \x01(\x02R\rmaxAngularVel\x12\x1f\n" +
	"\vencoder_cpr\x18\x05 \x01(\rR\n" +
	"encoderCpr\x12)\n" +
	"\x10max_acceleration\x18\x06 \x01(\x02R\x0fmaxAcceleration\x12*\n" +
	"\x11max_angular_accel\x18\a \x01(\x02R\x0fmaxAngularAccel\"Q\n" +
	"\x05Wheel\x12\x16\n" +
	"\x06radius\x18\x01 \x01(\x02R\x06radius\x120\n" +
	"\bposition\x18\x02 \x01(\v2\x14.types.math.Vector2DR\bposition\"\x96\x01\n" +
	"\rMecanumConfig\x127\n" +
	"\x06wheels\x18\x01 \x03(\v2\x1f.types.control.kinematics.WheelR\x06wheels\x12$\n" +
	"\x0emax_linear_vel\x18\x02 \x01(\x02R\fmaxLinearVel\x12&\n" +
	"\x0fmax_angular_vel\x18\x03 \x01(\x02R\rmaxAngularVel\"\xed\x01\n" +
	"\fSteer4Config\x127\n" +
	"\x06wheels\x18\x01 \x03(\v2\x1f.types.control.kinematics.WheelR\x06wheels\x12,\n" +
	"\x12max_steering_angle\x18\x02 \x01(\x02R\x10maxSteeringAngle\x12$\n" +
	"\x0emax_linear_vel\x18\x03 \x01(\x02R\fmaxLinearVel\x12&\n" +
	"\x0fmax_angular_vel\x18\x04 \x01(\x02R\rmaxAngularVel\x12(\n" +
	"\x10front_steer_only\x18\x05 \x01(\bR\x0efrontSteerOnly\"\xc7\x01\n" +
	"\x10Steer4DualConfig\x127\n" +
	"\x06wheels\x18\x01 \x03(\v2\x1f.types.control.kinematics.WheelR\x06wheels\x12,\n" +
	"\x12max_steering_angle\x18\x02 \x01(\x02R\x10maxSteeringAngle\x12$\n" +
	"\x0emax_linear_vel\x18\x03 \x01(\x02R\fmaxLinearVel\x12&\n" +
	"\x0fmax_angular_vel\x18\x04 \x01(\x02R\rmaxAngularVel\"\xc3\x01\n" +
	"\fSteer6Config\x127\n" +
	"\x06wheels\x18\x01 \x03(\v2\x1f.types.control.kinematics.WheelR\x06wheels\x12,\n" +
	"\x12max_steering_angle\x18\x02 \x01(\x02R\x10maxSteeringAngle\x12$\n" +
	"\x0emax_linear_vel\x18\x03 \x01(\x02R\fmaxLinearVel\x12&\n" +
	"\x0fmax_angular_vel\x18\x04 \x01(\x02R\rmaxAngularVel\"\x82\x03\n" +
	"\fWheelsConfig\x12R\n" +
	"\fdifferential\x18\x01 \x01(\v2,.types.control.kinematics.DifferentialConfigH\x00R\fdifferential\x12C\n" +
	"\amecanum\x18\x02 \x01(\v2'.types.control.kinematics.MecanumConfigH\x00R\amecanum\x12@\n" +
	"\x06steer4\x18\x03 \x01(\v2&.types.control.kinematics.Steer4ConfigH\x00R\x06steer4\x12M\n" +
	"\vsteer4_dual\x18\x04 \x01(\v2*.types.control.kinematics.Steer4DualConfigH\x00R\n" +
	"steer4Dual\x12@\n" +
	"\x06steer6\x18\x05 \x01(\v2&.types.control.kinematics.Steer6ConfigH\x00R\x06steer6B\x06\n" +
	"\x04typeB\xe3\x01\n" +
	"\x1ccom.types.control.kinematicsB\vWheelsProtoP\x01Z4github.com/itohio/EasyRobot/types/control/kinematics\xa2\x02\x03TCK\xaa\x02\x18Types.Control.Kinematics\xca\x02\x18Types\\Control\\Kinematics\xe2\x02$Types\\Control\\Kinematics\\GPBMetadata\xea\x02\x1aTypes::Control::Kinematicsb\x06proto3"

var (
	file_types_control_kinematics_wheels_proto_rawDescOnce sync.Once
	file_types_control_kinematics_wheels_proto_rawDescData []byte
)

func file_types_control_kinematics_wheels_proto_rawDescGZIP() []byte {
	file_types_control_kinematics_wheels_proto_rawDescOnce.Do(func() {
		file_types_control_kinematics_wheels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_control_kinematics_wheels_proto_rawDesc), len(file_types_control_kinematics_wheels_proto_rawDesc)))
	})
	return file_types_control_kinematics_wheels_proto_rawDescData
}

var file_types_control_kinematics_wheels_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_types_control_kinematics_wheels_proto_goTypes = []any{
	(*DifferentialConfig)(nil), // 0: types.control.kinematics.DifferentialConfig
	(*Wheel)(nil),              // 1: types.control.kinematics.Wheel
	(*MecanumConfig)(nil),      // 2: types.control.kinematics.MecanumConfig
	(*Steer4Config)(nil),       // 3: types.control.kinematics.Steer4Config
	(*Steer4DualConfig)(nil),   // 4: types.control.kinematics.Steer4DualConfig
	(*Steer6Config)(nil),       // 5: types.control.kinematics.Steer6Config
	(*WheelsConfig)(nil),       // 6: types.control.kinematics.WheelsConfig
	(*math.Vector2D)(nil),      // 7: types.math.Vector2D
}
var file_types_control_kinematics_wheels_proto_depIdxs = []int32{
	7,  // 0: types.control.kinematics.Wheel.position:type_name -> types.math.Vector2D
	1,  // 1: types.control.kinematics.MecanumConfig.wheels:type_name -> types.control.kinematics.Wheel
	1,  // 2: types.control.kinematics.Steer4Config.wheels:type_name -> types.control.kinematics.Wheel
	1,  // 3: types.control.kinematics.Steer4DualConfig.wheels:type_name -> types.control.kinematics.Wheel
	1,  // 4: types.control.kinematics.Steer6Config.wheels:type_name -> types.control.kinematics.Wheel
	0,  // 5: types.control.kinematics.WheelsConfig.differential:type_name -> types.control.kinematics.DifferentialConfig
	2,  // 6: types.control.kinematics.WheelsConfig.mecanum:type_name -> types.control.kinematics.MecanumConfig
	3,  // 7: types.control.kinematics.WheelsConfig.steer4:type_name -> types.control.kinematics.Steer4Config
	4,  // 8: types.control.kinematics.WheelsConfig.steer4_dual:type_name -> types.control.kinematics.Steer4DualConfig
	5,  // 9: types.control.kinematics.WheelsConfig.steer6:type_name -> types.control.kinematics.Steer6Config
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_types_control_kinematics_wheels_proto_init() }
func file_types_control_kinematics_wheels_proto_init() {
	if File_types_control_kinematics_wheels_proto != nil {
		return
	}
	file_types_control_kinematics_wheels_proto_msgTypes[6].OneofWrappers = []any{
		(*WheelsConfig_Differential)(nil),
		(*WheelsConfig_Mecanum)(nil),
		(*WheelsConfig_Steer4)(nil),
		(*WheelsConfig_Steer4Dual)(nil),
		(*WheelsConfig_Steer6)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_control_kinematics_wheels_proto_rawDesc), len(file_types_control_kinematics_wheels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_control_kinematics_wheels_proto_goTypes,
		DependencyIndexes: file_types_control_kinematics_wheels_proto_depIdxs,
		MessageInfos:      file_types_control_kinematics_wheels_proto_msgTypes,
	}.Build()
	File_types_control_kinematics_wheels_proto = out.File
	file_types_control_kinematics_wheels_proto_goTypes = nil
	file_types_control_kinematics_wheels_proto_depIdxs = nil
}
