// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: types/core/arbitrary.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ArbitraryValue encapsulates arbitrary types for local data transfer between modules.
// This is used for zero-copy, no-marshalling scenarios where data is passed
// within the same process or via shared memory.
//
// The actual data is not serialized - only type information and a reference
// is stored. The receiver must have access to the original data structure.
type ArbitraryValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeName      string                 `protobuf:"bytes,1,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`                                                           // Fully qualified type name (e.g., "github.com/itohio/EasyRobot/x/math/vec.Vector3D")
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`                                                                                   // Kind discriminator: "vector", "matrix", "tensor", "layer", "model", "custom"
	Reference     uint64                 `protobuf:"varint,3,opt,name=reference,proto3" json:"reference,omitempty"`                                                                        // Reference/pointer value (platform-specific, not portable)
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata about the value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArbitraryValue) Reset() {
	*x = ArbitraryValue{}
	mi := &file_types_core_arbitrary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArbitraryValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArbitraryValue) ProtoMessage() {}

func (x *ArbitraryValue) ProtoReflect() protoreflect.Message {
	mi := &file_types_core_arbitrary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArbitraryValue.ProtoReflect.Descriptor instead.
func (*ArbitraryValue) Descriptor() ([]byte, []int) {
	return file_types_core_arbitrary_proto_rawDescGZIP(), []int{0}
}

func (x *ArbitraryValue) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *ArbitraryValue) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ArbitraryValue) GetReference() uint64 {
	if x != nil {
		return x.Reference
	}
	return 0
}

func (x *ArbitraryValue) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ArbitraryMessage wraps an ArbitraryValue with context for local transfer
type ArbitraryMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`           // Source module/component name
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"` // Destination module/component name
	Value         *ArbitraryValue        `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`             // The arbitrary value
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`    // Timestamp when value was created
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArbitraryMessage) Reset() {
	*x = ArbitraryMessage{}
	mi := &file_types_core_arbitrary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArbitraryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArbitraryMessage) ProtoMessage() {}

func (x *ArbitraryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_types_core_arbitrary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArbitraryMessage.ProtoReflect.Descriptor instead.
func (*ArbitraryMessage) Descriptor() ([]byte, []int) {
	return file_types_core_arbitrary_proto_rawDescGZIP(), []int{1}
}

func (x *ArbitraryMessage) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ArbitraryMessage) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *ArbitraryMessage) GetValue() *ArbitraryValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ArbitraryMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_types_core_arbitrary_proto protoreflect.FileDescriptor

const file_types_core_arbitrary_proto_rawDesc = "" +
	"\n" +
	"\x1atypes/core/arbitrary.proto\x12\n" +
	"types.core\"\xe2\x01\n" +
	"\x0eArbitraryValue\x12\x1b\n" +
	"\ttype_name\x18\x01 \x01(\tR\btypeName\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1c\n" +
	"\treference\x18\x03 \x01(\x04R\treference\x12D\n" +
	"\bmetadata\x18\x04 \x03(\v2(.types.core.ArbitraryValue.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9c\x01\n" +
	"\x10ArbitraryMessage\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x120\n" +
	"\x05value\x18\x03 \x01(\v2\x1a.types.core.ArbitraryValueR\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestampB\x91\x01\n" +
	"\x0ecom.types.coreB\x0eArbitraryProtoP\x01Z&github.com/itohio/EasyRobot/types/core\xa2\x02\x03TCX\xaa\x02\n" +
	"Types.Core\xca\x02\n" +
	"Types\\Core\xe2\x02\x16Types\\Core\\GPBMetadata\xea\x02\vTypes::Coreb\x06proto3"

var (
	file_types_core_arbitrary_proto_rawDescOnce sync.Once
	file_types_core_arbitrary_proto_rawDescData []byte
)

func file_types_core_arbitrary_proto_rawDescGZIP() []byte {
	file_types_core_arbitrary_proto_rawDescOnce.Do(func() {
		file_types_core_arbitrary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_core_arbitrary_proto_rawDesc), len(file_types_core_arbitrary_proto_rawDesc)))
	})
	return file_types_core_arbitrary_proto_rawDescData
}

var file_types_core_arbitrary_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_types_core_arbitrary_proto_goTypes = []any{
	(*ArbitraryValue)(nil),   // 0: types.core.ArbitraryValue
	(*ArbitraryMessage)(nil), // 1: types.core.ArbitraryMessage
	nil,                      // 2: types.core.ArbitraryValue.MetadataEntry
}
var file_types_core_arbitrary_proto_depIdxs = []int32{
	2, // 0: types.core.ArbitraryValue.metadata:type_name -> types.core.ArbitraryValue.MetadataEntry
	0, // 1: types.core.ArbitraryMessage.value:type_name -> types.core.ArbitraryValue
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_types_core_arbitrary_proto_init() }
func file_types_core_arbitrary_proto_init() {
	if File_types_core_arbitrary_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_core_arbitrary_proto_rawDesc), len(file_types_core_arbitrary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_core_arbitrary_proto_goTypes,
		DependencyIndexes: file_types_core_arbitrary_proto_depIdxs,
		MessageInfos:      file_types_core_arbitrary_proto_msgTypes,
	}.Build()
	File_types_core_arbitrary_proto = out.File
	file_types_core_arbitrary_proto_goTypes = nil
	file_types_core_arbitrary_proto_depIdxs = nil
}
