// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: types/control/manipulator.proto

package control

import (
	kinematics "github.com/itohio/EasyRobot/types/control/kinematics"
	math "github.com/itohio/EasyRobot/types/math"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServoMotorConfig represents configuration for a single servo motor
// Note: This is for servos, not motors. Motor configs are in types/devices/motor.proto
type ServoMotorConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pin           uint32                 `protobuf:"varint,1,opt,name=pin,proto3" json:"pin,omitempty"`                                        // GPIO pin number
	MinUs         float32                `protobuf:"fixed32,2,opt,name=min_us,json=minUs,proto3" json:"min_us,omitempty"`                      // Minimum pulse width in microseconds
	MaxUs         float32                `protobuf:"fixed32,3,opt,name=max_us,json=maxUs,proto3" json:"max_us,omitempty"`                      // Maximum pulse width in microseconds
	DefaultUs     float32                `protobuf:"fixed32,4,opt,name=default_us,json=defaultUs,proto3" json:"default_us,omitempty"`          // Default/center pulse width in microseconds
	MaxAngle      float32                `protobuf:"fixed32,5,opt,name=max_angle,json=maxAngle,proto3" json:"max_angle,omitempty"`             // Maximum angle in degrees
	DefaultAngle  float32                `protobuf:"fixed32,6,opt,name=default_angle,json=defaultAngle,proto3" json:"default_angle,omitempty"` // Default angle in degrees
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServoMotorConfig) Reset() {
	*x = ServoMotorConfig{}
	mi := &file_types_control_manipulator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServoMotorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServoMotorConfig) ProtoMessage() {}

func (x *ServoMotorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_control_manipulator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServoMotorConfig.ProtoReflect.Descriptor instead.
func (*ServoMotorConfig) Descriptor() ([]byte, []int) {
	return file_types_control_manipulator_proto_rawDescGZIP(), []int{0}
}

func (x *ServoMotorConfig) GetPin() uint32 {
	if x != nil {
		return x.Pin
	}
	return 0
}

func (x *ServoMotorConfig) GetMinUs() float32 {
	if x != nil {
		return x.MinUs
	}
	return 0
}

func (x *ServoMotorConfig) GetMaxUs() float32 {
	if x != nil {
		return x.MaxUs
	}
	return 0
}

func (x *ServoMotorConfig) GetDefaultUs() float32 {
	if x != nil {
		return x.DefaultUs
	}
	return 0
}

func (x *ServoMotorConfig) GetMaxAngle() float32 {
	if x != nil {
		return x.MaxAngle
	}
	return 0
}

func (x *ServoMotorConfig) GetDefaultAngle() float32 {
	if x != nil {
		return x.DefaultAngle
	}
	return 0
}

// ManipulatorConfig represents configuration for a manipulator
type ManipulatorConfig struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Motors []*ServoMotorConfig    `protobuf:"bytes,1,rep,name=motors,proto3" json:"motors,omitempty"` // Servo motor configurations (always required)
	// For kinematics modes (planar/DH): kinematics configuration
	// For raw mode: this should be empty or ignored
	Joints *kinematics.JointsConfig `protobuf:"bytes,2,opt,name=joints,proto3" json:"joints,omitempty"`
	// Motion constraints per joint (velocity, acceleration, jerk limits)
	Motion        []*Constraints `protobuf:"bytes,3,rep,name=motion,proto3" json:"motion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManipulatorConfig) Reset() {
	*x = ManipulatorConfig{}
	mi := &file_types_control_manipulator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManipulatorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManipulatorConfig) ProtoMessage() {}

func (x *ManipulatorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_control_manipulator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManipulatorConfig.ProtoReflect.Descriptor instead.
func (*ManipulatorConfig) Descriptor() ([]byte, []int) {
	return file_types_control_manipulator_proto_rawDescGZIP(), []int{1}
}

func (x *ManipulatorConfig) GetMotors() []*ServoMotorConfig {
	if x != nil {
		return x.Motors
	}
	return nil
}

func (x *ManipulatorConfig) GetJoints() *kinematics.JointsConfig {
	if x != nil {
		return x.Joints
	}
	return nil
}

func (x *ManipulatorConfig) GetMotion() []*Constraints {
	if x != nil {
		return x.Motion
	}
	return nil
}

// ManipulatorTarget represents target for the manipulator
// Depending on build mode:
// - Raw mode: uses joint_angles (direct servo control)
// - Planar/DH mode: uses end_effector_position (kinematics calculates joint angles)
type ManipulatorTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// For raw mode: direct joint angle targets in degrees
	JointAngles []float32 `protobuf:"fixed32,1,rep,packed,name=joint_angles,json=jointAngles,proto3" json:"joint_angles,omitempty"`
	// For kinematics modes (planar/DH): end effector position target
	// Position in 3D space (meters)
	EndEffectorPosition *math.Vector3D `protobuf:"bytes,2,opt,name=end_effector_position,json=endEffectorPosition,proto3" json:"end_effector_position,omitempty"`
	// Orientation as quaternion [w, x, y, z] (optional for planar)
	EndEffectorOrientation *math.Quaternion `protobuf:"bytes,3,opt,name=end_effector_orientation,json=endEffectorOrientation,proto3" json:"end_effector_orientation,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ManipulatorTarget) Reset() {
	*x = ManipulatorTarget{}
	mi := &file_types_control_manipulator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManipulatorTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManipulatorTarget) ProtoMessage() {}

func (x *ManipulatorTarget) ProtoReflect() protoreflect.Message {
	mi := &file_types_control_manipulator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManipulatorTarget.ProtoReflect.Descriptor instead.
func (*ManipulatorTarget) Descriptor() ([]byte, []int) {
	return file_types_control_manipulator_proto_rawDescGZIP(), []int{2}
}

func (x *ManipulatorTarget) GetJointAngles() []float32 {
	if x != nil {
		return x.JointAngles
	}
	return nil
}

func (x *ManipulatorTarget) GetEndEffectorPosition() *math.Vector3D {
	if x != nil {
		return x.EndEffectorPosition
	}
	return nil
}

func (x *ManipulatorTarget) GetEndEffectorOrientation() *math.Quaternion {
	if x != nil {
		return x.EndEffectorOrientation
	}
	return nil
}

// ManipulatorState represents current state of the manipulator
type ManipulatorState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JointAngles     []float32              `protobuf:"fixed32,1,rep,packed,name=joint_angles,json=jointAngles,proto3" json:"joint_angles,omitempty"`             // Current joint angles in degrees
	JointVelocities []float32              `protobuf:"fixed32,2,rep,packed,name=joint_velocities,json=jointVelocities,proto3" json:"joint_velocities,omitempty"` // Current joint velocities (degrees/sec)
	Timestamp       int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                            // Timestamp in nanoseconds
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ManipulatorState) Reset() {
	*x = ManipulatorState{}
	mi := &file_types_control_manipulator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManipulatorState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManipulatorState) ProtoMessage() {}

func (x *ManipulatorState) ProtoReflect() protoreflect.Message {
	mi := &file_types_control_manipulator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManipulatorState.ProtoReflect.Descriptor instead.
func (*ManipulatorState) Descriptor() ([]byte, []int) {
	return file_types_control_manipulator_proto_rawDescGZIP(), []int{3}
}

func (x *ManipulatorState) GetJointAngles() []float32 {
	if x != nil {
		return x.JointAngles
	}
	return nil
}

func (x *ManipulatorState) GetJointVelocities() []float32 {
	if x != nil {
		return x.JointVelocities
	}
	return nil
}

func (x *ManipulatorState) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_types_control_manipulator_proto protoreflect.FileDescriptor

const file_types_control_manipulator_proto_rawDesc = "" +
	"\n" +
	"\x1ftypes/control/manipulator.proto\x12\rtypes.control\x1a%types/control/kinematics/joints.proto\x1a\x1atypes/control/motion.proto\x1a\x18types/math/vectors.proto\"\xb3\x01\n" +
	"\x10ServoMotorConfig\x12\x10\n" +
	"\x03pin\x18\x01 \x01(\rR\x03pin\x12\x15\n" +
	"\x06min_us\x18\x02 \x01(\x02R\x05minUs\x12\x15\n" +
	"\x06max_us\x18\x03 \x01(\x02R\x05maxUs\x12\x1d\n" +
	"\n" +
	"default_us\x18\x04 \x01(\x02R\tdefaultUs\x12\x1b\n" +
	"\tmax_angle\x18\x05 \x01(\x02R\bmaxAngle\x12#\n" +
	"\rdefault_angle\x18\x06 \x01(\x02R\fdefaultAngle\"\xc0\x01\n" +
	"\x11ManipulatorConfig\x127\n" +
	"\x06motors\x18\x01 \x03(\v2\x1f.types.control.ServoMotorConfigR\x06motors\x12>\n" +
	"\x06joints\x18\x02 \x01(\v2&.types.control.kinematics.JointsConfigR\x06joints\x122\n" +
	"\x06motion\x18\x03 \x03(\v2\x1a.types.control.ConstraintsR\x06motion\"\xd2\x01\n" +
	"\x11ManipulatorTarget\x12!\n" +
	"\fjoint_angles\x18\x01 \x03(\x02R\vjointAngles\x12H\n" +
	"\x15end_effector_position\x18\x02 \x01(\v2\x14.types.math.Vector3DR\x13endEffectorPosition\x12P\n" +
	"\x18end_effector_orientation\x18\x03 \x01(\v2\x16.types.math.QuaternionR\x16endEffectorOrientation\"~\n" +
	"\x10ManipulatorState\x12!\n" +
	"\fjoint_angles\x18\x01 \x03(\x02R\vjointAngles\x12)\n" +
	"\x10joint_velocities\x18\x02 \x03(\x02R\x0fjointVelocities\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestampB\xa5\x01\n" +
	"\x11com.types.controlB\x10ManipulatorProtoP\x01Z)github.com/itohio/EasyRobot/types/control\xa2\x02\x03TCX\xaa\x02\rTypes.Control\xca\x02\rTypes\\Control\xe2\x02\x19Types\\Control\\GPBMetadata\xea\x02\x0eTypes::Controlb\x06proto3"

var (
	file_types_control_manipulator_proto_rawDescOnce sync.Once
	file_types_control_manipulator_proto_rawDescData []byte
)

func file_types_control_manipulator_proto_rawDescGZIP() []byte {
	file_types_control_manipulator_proto_rawDescOnce.Do(func() {
		file_types_control_manipulator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_control_manipulator_proto_rawDesc), len(file_types_control_manipulator_proto_rawDesc)))
	})
	return file_types_control_manipulator_proto_rawDescData
}

var file_types_control_manipulator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_types_control_manipulator_proto_goTypes = []any{
	(*ServoMotorConfig)(nil),        // 0: types.control.ServoMotorConfig
	(*ManipulatorConfig)(nil),       // 1: types.control.ManipulatorConfig
	(*ManipulatorTarget)(nil),       // 2: types.control.ManipulatorTarget
	(*ManipulatorState)(nil),        // 3: types.control.ManipulatorState
	(*kinematics.JointsConfig)(nil), // 4: types.control.kinematics.JointsConfig
	(*Constraints)(nil),             // 5: types.control.Constraints
	(*math.Vector3D)(nil),           // 6: types.math.Vector3D
	(*math.Quaternion)(nil),         // 7: types.math.Quaternion
}
var file_types_control_manipulator_proto_depIdxs = []int32{
	0, // 0: types.control.ManipulatorConfig.motors:type_name -> types.control.ServoMotorConfig
	4, // 1: types.control.ManipulatorConfig.joints:type_name -> types.control.kinematics.JointsConfig
	5, // 2: types.control.ManipulatorConfig.motion:type_name -> types.control.Constraints
	6, // 3: types.control.ManipulatorTarget.end_effector_position:type_name -> types.math.Vector3D
	7, // 4: types.control.ManipulatorTarget.end_effector_orientation:type_name -> types.math.Quaternion
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_types_control_manipulator_proto_init() }
func file_types_control_manipulator_proto_init() {
	if File_types_control_manipulator_proto != nil {
		return
	}
	file_types_control_motion_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_control_manipulator_proto_rawDesc), len(file_types_control_manipulator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_control_manipulator_proto_goTypes,
		DependencyIndexes: file_types_control_manipulator_proto_depIdxs,
		MessageInfos:      file_types_control_manipulator_proto_msgTypes,
	}.Build()
	File_types_control_manipulator_proto = out.File
	file_types_control_manipulator_proto_goTypes = nil
	file_types_control_manipulator_proto_depIdxs = nil
}
