// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: types/control/motion.proto

package control

import (
	math "github.com/itohio/EasyRobot/types/math"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State represents the robot pose and velocity at a specific timestamp
type State struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *math.Vector3D         `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Yaw           float32                `protobuf:"fixed32,2,opt,name=yaw,proto3" json:"yaw,omitempty"`             // Yaw angle in radians
	Speed         float32                `protobuf:"fixed32,3,opt,name=speed,proto3" json:"speed,omitempty"`         // Speed in m/s
	Timestamp     float32                `protobuf:"fixed32,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Timestamp in seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_types_control_motion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_types_control_motion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_types_control_motion_proto_rawDescGZIP(), []int{0}
}

func (x *State) GetPosition() *math.Vector3D {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *State) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *State) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *State) GetTimestamp() float32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Controls represents aggregate control commands issued to the robot
type Controls struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Linear        float32                `protobuf:"fixed32,1,opt,name=linear,proto3" json:"linear,omitempty"`   // Linear velocity command
	Angular       float32                `protobuf:"fixed32,2,opt,name=angular,proto3" json:"angular,omitempty"` // Angular velocity command
	Effort        *math.Vector           `protobuf:"bytes,3,opt,name=effort,proto3" json:"effort,omitempty"`     // Additional effort vector
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Controls) Reset() {
	*x = Controls{}
	mi := &file_types_control_motion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Controls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Controls) ProtoMessage() {}

func (x *Controls) ProtoReflect() protoreflect.Message {
	mi := &file_types_control_motion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Controls.ProtoReflect.Descriptor instead.
func (*Controls) Descriptor() ([]byte, []int) {
	return file_types_control_motion_proto_rawDescGZIP(), []int{1}
}

func (x *Controls) GetLinear() float32 {
	if x != nil {
		return x.Linear
	}
	return 0
}

func (x *Controls) GetAngular() float32 {
	if x != nil {
		return x.Angular
	}
	return 0
}

func (x *Controls) GetEffort() *math.Vector {
	if x != nil {
		return x.Effort
	}
	return nil
}

// Trajectory encapsulates future states the robot should follow and corresponding nominal controls
type Trajectory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	States        []*State               `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
	Controls      []*Controls            `protobuf:"bytes,2,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trajectory) Reset() {
	*x = Trajectory{}
	mi := &file_types_control_motion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trajectory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trajectory) ProtoMessage() {}

func (x *Trajectory) ProtoReflect() protoreflect.Message {
	mi := &file_types_control_motion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trajectory.ProtoReflect.Descriptor instead.
func (*Trajectory) Descriptor() ([]byte, []int) {
	return file_types_control_motion_proto_rawDescGZIP(), []int{2}
}

func (x *Trajectory) GetStates() []*State {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *Trajectory) GetControls() []*Controls {
	if x != nil {
		return x.Controls
	}
	return nil
}

// Constraints defines the physical limits the planner must respect
type Constraints struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	MaxSpeed               float32                `protobuf:"fixed32,1,opt,name=max_speed,json=maxSpeed,proto3" json:"max_speed,omitempty"`
	MaxAcceleration        float32                `protobuf:"fixed32,2,opt,name=max_acceleration,json=maxAcceleration,proto3" json:"max_acceleration,omitempty"`
	MaxDeceleration        float32                `protobuf:"fixed32,3,opt,name=max_deceleration,json=maxDeceleration,proto3" json:"max_deceleration,omitempty"`
	MaxJerk                float32                `protobuf:"fixed32,4,opt,name=max_jerk,json=maxJerk,proto3" json:"max_jerk,omitempty"`
	MaxTurnRate            float32                `protobuf:"fixed32,5,opt,name=max_turn_rate,json=maxTurnRate,proto3" json:"max_turn_rate,omitempty"`
	MaxTurnAcceleration    float32                `protobuf:"fixed32,6,opt,name=max_turn_acceleration,json=maxTurnAcceleration,proto3" json:"max_turn_acceleration,omitempty"`
	MaxLateralAcceleration float32                `protobuf:"fixed32,7,opt,name=max_lateral_acceleration,json=maxLateralAcceleration,proto3" json:"max_lateral_acceleration,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Constraints) Reset() {
	*x = Constraints{}
	mi := &file_types_control_motion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Constraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Constraints) ProtoMessage() {}

func (x *Constraints) ProtoReflect() protoreflect.Message {
	mi := &file_types_control_motion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Constraints.ProtoReflect.Descriptor instead.
func (*Constraints) Descriptor() ([]byte, []int) {
	return file_types_control_motion_proto_rawDescGZIP(), []int{3}
}

func (x *Constraints) GetMaxSpeed() float32 {
	if x != nil {
		return x.MaxSpeed
	}
	return 0
}

func (x *Constraints) GetMaxAcceleration() float32 {
	if x != nil {
		return x.MaxAcceleration
	}
	return 0
}

func (x *Constraints) GetMaxDeceleration() float32 {
	if x != nil {
		return x.MaxDeceleration
	}
	return 0
}

func (x *Constraints) GetMaxJerk() float32 {
	if x != nil {
		return x.MaxJerk
	}
	return 0
}

func (x *Constraints) GetMaxTurnRate() float32 {
	if x != nil {
		return x.MaxTurnRate
	}
	return 0
}

func (x *Constraints) GetMaxTurnAcceleration() float32 {
	if x != nil {
		return x.MaxTurnAcceleration
	}
	return 0
}

func (x *Constraints) GetMaxLateralAcceleration() float32 {
	if x != nil {
		return x.MaxLateralAcceleration
	}
	return 0
}

// PIDGains holds proportional-integral-derivative coefficients
type PIDGains struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	P             float32                `protobuf:"fixed32,1,opt,name=p,proto3" json:"p,omitempty"`
	I             float32                `protobuf:"fixed32,2,opt,name=i,proto3" json:"i,omitempty"`
	D             float32                `protobuf:"fixed32,3,opt,name=d,proto3" json:"d,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PIDGains) Reset() {
	*x = PIDGains{}
	mi := &file_types_control_motion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PIDGains) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PIDGains) ProtoMessage() {}

func (x *PIDGains) ProtoReflect() protoreflect.Message {
	mi := &file_types_control_motion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PIDGains.ProtoReflect.Descriptor instead.
func (*PIDGains) Descriptor() ([]byte, []int) {
	return file_types_control_motion_proto_rawDescGZIP(), []int{4}
}

func (x *PIDGains) GetP() float32 {
	if x != nil {
		return x.P
	}
	return 0
}

func (x *PIDGains) GetI() float32 {
	if x != nil {
		return x.I
	}
	return 0
}

func (x *PIDGains) GetD() float32 {
	if x != nil {
		return x.D
	}
	return 0
}

// Parameters configures the planner tuning knobs
type Parameters struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SamplePeriod      float32                `protobuf:"fixed32,1,opt,name=sample_period,json=samplePeriod,proto3" json:"sample_period,omitempty"`
	LookaheadDistance float32                `protobuf:"fixed32,2,opt,name=lookahead_distance,json=lookaheadDistance,proto3" json:"lookahead_distance,omitempty"`
	SpeedPid          *PIDGains              `protobuf:"bytes,3,opt,name=speed_pid,json=speedPid,proto3" json:"speed_pid,omitempty"`
	HeadingPid        *PIDGains              `protobuf:"bytes,4,opt,name=heading_pid,json=headingPid,proto3" json:"heading_pid,omitempty"`
	LateralPid        *PIDGains              `protobuf:"bytes,5,opt,name=lateral_pid,json=lateralPid,proto3" json:"lateral_pid,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Parameters) Reset() {
	*x = Parameters{}
	mi := &file_types_control_motion_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameters) ProtoMessage() {}

func (x *Parameters) ProtoReflect() protoreflect.Message {
	mi := &file_types_control_motion_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameters.ProtoReflect.Descriptor instead.
func (*Parameters) Descriptor() ([]byte, []int) {
	return file_types_control_motion_proto_rawDescGZIP(), []int{5}
}

func (x *Parameters) GetSamplePeriod() float32 {
	if x != nil {
		return x.SamplePeriod
	}
	return 0
}

func (x *Parameters) GetLookaheadDistance() float32 {
	if x != nil {
		return x.LookaheadDistance
	}
	return 0
}

func (x *Parameters) GetSpeedPid() *PIDGains {
	if x != nil {
		return x.SpeedPid
	}
	return nil
}

func (x *Parameters) GetHeadingPid() *PIDGains {
	if x != nil {
		return x.HeadingPid
	}
	return nil
}

func (x *Parameters) GetLateralPid() *PIDGains {
	if x != nil {
		return x.LateralPid
	}
	return nil
}

var File_types_control_motion_proto protoreflect.FileDescriptor

const file_types_control_motion_proto_rawDesc = "" +
	"\n" +
	"\x1atypes/control/motion.proto\x12\rtypes.control\x1a\x18types/math/vectors.proto\"\x7f\n" +
	"\x05State\x120\n" +
	"\bposition\x18\x01 \x01(\v2\x14.types.math.Vector3DR\bposition\x12\x10\n" +
	"\x03yaw\x18\x02 \x01(\x02R\x03yaw\x12\x14\n" +
	"\x05speed\x18\x03 \x01(\x02R\x05speed\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x02R\ttimestamp\"h\n" +
	"\bControls\x12\x16\n" +
	"\x06linear\x18\x01 \x01(\x02R\x06linear\x12\x18\n" +
	"\aangular\x18\x02 \x01(\x02R\aangular\x12*\n" +
	"\x06effort\x18\x03 \x01(\v2\x12.types.math.VectorR\x06effort\"o\n" +
	"\n" +
	"Trajectory\x12,\n" +
	"\x06states\x18\x01 \x03(\v2\x14.types.control.StateR\x06states\x123\n" +
	"\bcontrols\x18\x02 \x03(\v2\x17.types.control.ControlsR\bcontrols\"\xad\x02\n" +
	"\vConstraints\x12\x1b\n" +
	"\tmax_speed\x18\x01 \x01(\x02R\bmaxSpeed\x12)\n" +
	"\x10max_acceleration\x18\x02 \x01(\x02R\x0fmaxAcceleration\x12)\n" +
	"\x10max_deceleration\x18\x03 \x01(\x02R\x0fmaxDeceleration\x12\x19\n" +
	"\bmax_jerk\x18\x04 \x01(\x02R\amaxJerk\x12\"\n" +
	"\rmax_turn_rate\x18\x05 \x01(\x02R\vmaxTurnRate\x122\n" +
	"\x15max_turn_acceleration\x18\x06 \x01(\x02R\x13maxTurnAcceleration\x128\n" +
	"\x18max_lateral_acceleration\x18\a \x01(\x02R\x16maxLateralAcceleration\"4\n" +
	"\bPIDGains\x12\f\n" +
	"\x01p\x18\x01 \x01(\x02R\x01p\x12\f\n" +
	"\x01i\x18\x02 \x01(\x02R\x01i\x12\f\n" +
	"\x01d\x18\x03 \x01(\x02R\x01d\"\x8a\x02\n" +
	"\n" +
	"Parameters\x12#\n" +
	"\rsample_period\x18\x01 \x01(\x02R\fsamplePeriod\x12-\n" +
	"\x12lookahead_distance\x18\x02 \x01(\x02R\x11lookaheadDistance\x124\n" +
	"\tspeed_pid\x18\x03 \x01(\v2\x17.types.control.PIDGainsR\bspeedPid\x128\n" +
	"\vheading_pid\x18\x04 \x01(\v2\x17.types.control.PIDGainsR\n" +
	"headingPid\x128\n" +
	"\vlateral_pid\x18\x05 \x01(\v2\x17.types.control.PIDGainsR\n" +
	"lateralPidB\xa0\x01\n" +
	"\x11com.types.controlB\vMotionProtoP\x01Z)github.com/itohio/EasyRobot/types/control\xa2\x02\x03TCX\xaa\x02\rTypes.Control\xca\x02\rTypes\\Control\xe2\x02\x19Types\\Control\\GPBMetadata\xea\x02\x0eTypes::Controlb\x06proto3"

var (
	file_types_control_motion_proto_rawDescOnce sync.Once
	file_types_control_motion_proto_rawDescData []byte
)

func file_types_control_motion_proto_rawDescGZIP() []byte {
	file_types_control_motion_proto_rawDescOnce.Do(func() {
		file_types_control_motion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_control_motion_proto_rawDesc), len(file_types_control_motion_proto_rawDesc)))
	})
	return file_types_control_motion_proto_rawDescData
}

var file_types_control_motion_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_types_control_motion_proto_goTypes = []any{
	(*State)(nil),         // 0: types.control.State
	(*Controls)(nil),      // 1: types.control.Controls
	(*Trajectory)(nil),    // 2: types.control.Trajectory
	(*Constraints)(nil),   // 3: types.control.Constraints
	(*PIDGains)(nil),      // 4: types.control.PIDGains
	(*Parameters)(nil),    // 5: types.control.Parameters
	(*math.Vector3D)(nil), // 6: types.math.Vector3D
	(*math.Vector)(nil),   // 7: types.math.Vector
}
var file_types_control_motion_proto_depIdxs = []int32{
	6, // 0: types.control.State.position:type_name -> types.math.Vector3D
	7, // 1: types.control.Controls.effort:type_name -> types.math.Vector
	0, // 2: types.control.Trajectory.states:type_name -> types.control.State
	1, // 3: types.control.Trajectory.controls:type_name -> types.control.Controls
	4, // 4: types.control.Parameters.speed_pid:type_name -> types.control.PIDGains
	4, // 5: types.control.Parameters.heading_pid:type_name -> types.control.PIDGains
	4, // 6: types.control.Parameters.lateral_pid:type_name -> types.control.PIDGains
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_types_control_motion_proto_init() }
func file_types_control_motion_proto_init() {
	if File_types_control_motion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_control_motion_proto_rawDesc), len(file_types_control_motion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_control_motion_proto_goTypes,
		DependencyIndexes: file_types_control_motion_proto_depIdxs,
		MessageInfos:      file_types_control_motion_proto_msgTypes,
	}.Build()
	File_types_control_motion_proto = out.File
	file_types_control_motion_proto_goTypes = nil
	file_types_control_motion_proto_depIdxs = nil
}
