// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: types/control/motor.proto

package control

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MotorType represents the motor driver type
type MotorType int32

const (
	MotorType_MOTOR_TYPE_UNSPECIFIED MotorType = 0
	MotorType_MOTOR_TYPE_DIR_PWM     MotorType = 1 // One direction pin + one PWM pin
	MotorType_MOTOR_TYPE_AB_PWM      MotorType = 2 // Two pins (A and B) both with PWM
	MotorType_MOTOR_TYPE_AB_DIR_PWM  MotorType = 3 // Two direction pins (A, B) + one PWM pin
)

// Enum value maps for MotorType.
var (
	MotorType_name = map[int32]string{
		0: "MOTOR_TYPE_UNSPECIFIED",
		1: "MOTOR_TYPE_DIR_PWM",
		2: "MOTOR_TYPE_AB_PWM",
		3: "MOTOR_TYPE_AB_DIR_PWM",
	}
	MotorType_value = map[string]int32{
		"MOTOR_TYPE_UNSPECIFIED": 0,
		"MOTOR_TYPE_DIR_PWM":     1,
		"MOTOR_TYPE_AB_PWM":      2,
		"MOTOR_TYPE_AB_DIR_PWM":  3,
	}
)

func (x MotorType) Enum() *MotorType {
	p := new(MotorType)
	*p = x
	return p
}

func (x MotorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MotorType) Descriptor() protoreflect.EnumDescriptor {
	return file_types_control_motor_proto_enumTypes[0].Descriptor()
}

func (MotorType) Type() protoreflect.EnumType {
	return &file_types_control_motor_proto_enumTypes[0]
}

func (x MotorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MotorType.Descriptor instead.
func (MotorType) EnumDescriptor() ([]byte, []int) {
	return file_types_control_motor_proto_rawDescGZIP(), []int{0}
}

// MotorConfig represents configuration for a single motor
type MotorConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  MotorType              `protobuf:"varint,1,opt,name=type,proto3,enum=types.control.MotorType" json:"type,omitempty"` // Motor driver type
	// Pin configuration (depends on type)
	DirPin uint32 `protobuf:"varint,2,opt,name=dir_pin,json=dirPin,proto3" json:"dir_pin,omitempty"` // Direction pin (TypeDirPWM)
	PwmPin uint32 `protobuf:"varint,3,opt,name=pwm_pin,json=pwmPin,proto3" json:"pwm_pin,omitempty"` // PWM pin (TypeDirPWM, TypeABDirPWM)
	PinA   uint32 `protobuf:"varint,4,opt,name=pin_a,json=pinA,proto3" json:"pin_a,omitempty"`       // Pin A (TypeABPWM, TypeABDirPWM)
	PinB   uint32 `protobuf:"varint,5,opt,name=pin_b,json=pinB,proto3" json:"pin_b,omitempty"`       // Pin B (TypeABPWM, TypeABDirPWM)
	// Encoder pins
	EncoderPinA uint32 `protobuf:"varint,6,opt,name=encoder_pin_a,json=encoderPinA,proto3" json:"encoder_pin_a,omitempty"` // Encoder pin A
	EncoderPinB uint32 `protobuf:"varint,7,opt,name=encoder_pin_b,json=encoderPinB,proto3" json:"encoder_pin_b,omitempty"` // Encoder pin B
	// PID configuration
	PidGains *PIDGains `protobuf:"bytes,8,opt,name=pid_gains,json=pidGains,proto3" json:"pid_gains,omitempty"` // PID gains for speed control
	// Control parameters
	MaxOutput    float32 `protobuf:"fixed32,9,opt,name=max_output,json=maxOutput,proto3" json:"max_output,omitempty"`           // Maximum PID output (default: 1.0)
	SamplePeriod float32 `protobuf:"fixed32,10,opt,name=sample_period,json=samplePeriod,proto3" json:"sample_period,omitempty"` // PID update period in seconds (default: 0.01)
	MaxRpm       float32 `protobuf:"fixed32,11,opt,name=max_rpm,json=maxRpm,proto3" json:"max_rpm,omitempty"`                   // Maximum motor speed in RPM
	// Encoder configuration
	CountsPerRevolution int64 `protobuf:"varint,12,opt,name=counts_per_revolution,json=countsPerRevolution,proto3" json:"counts_per_revolution,omitempty"` // Encoder counts per revolution (default: 2048)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MotorConfig) Reset() {
	*x = MotorConfig{}
	mi := &file_types_control_motor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MotorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MotorConfig) ProtoMessage() {}

func (x *MotorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_control_motor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MotorConfig.ProtoReflect.Descriptor instead.
func (*MotorConfig) Descriptor() ([]byte, []int) {
	return file_types_control_motor_proto_rawDescGZIP(), []int{0}
}

func (x *MotorConfig) GetType() MotorType {
	if x != nil {
		return x.Type
	}
	return MotorType_MOTOR_TYPE_UNSPECIFIED
}

func (x *MotorConfig) GetDirPin() uint32 {
	if x != nil {
		return x.DirPin
	}
	return 0
}

func (x *MotorConfig) GetPwmPin() uint32 {
	if x != nil {
		return x.PwmPin
	}
	return 0
}

func (x *MotorConfig) GetPinA() uint32 {
	if x != nil {
		return x.PinA
	}
	return 0
}

func (x *MotorConfig) GetPinB() uint32 {
	if x != nil {
		return x.PinB
	}
	return 0
}

func (x *MotorConfig) GetEncoderPinA() uint32 {
	if x != nil {
		return x.EncoderPinA
	}
	return 0
}

func (x *MotorConfig) GetEncoderPinB() uint32 {
	if x != nil {
		return x.EncoderPinB
	}
	return 0
}

func (x *MotorConfig) GetPidGains() *PIDGains {
	if x != nil {
		return x.PidGains
	}
	return nil
}

func (x *MotorConfig) GetMaxOutput() float32 {
	if x != nil {
		return x.MaxOutput
	}
	return 0
}

func (x *MotorConfig) GetSamplePeriod() float32 {
	if x != nil {
		return x.SamplePeriod
	}
	return 0
}

func (x *MotorConfig) GetMaxRpm() float32 {
	if x != nil {
		return x.MaxRpm
	}
	return 0
}

func (x *MotorConfig) GetCountsPerRevolution() int64 {
	if x != nil {
		return x.CountsPerRevolution
	}
	return 0
}

// MotorState represents current state of a motor
type MotorState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentSpeed  float32                `protobuf:"fixed32,1,opt,name=current_speed,json=currentSpeed,proto3" json:"current_speed,omitempty"` // Current speed in RPM (from encoder)
	TargetSpeed   float32                `protobuf:"fixed32,2,opt,name=target_speed,json=targetSpeed,proto3" json:"target_speed,omitempty"`    // Target speed in RPM
	PidOutput     float32                `protobuf:"fixed32,3,opt,name=pid_output,json=pidOutput,proto3" json:"pid_output,omitempty"`          // Current PID controller output
	Position      int64                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`                              // Encoder position in counts
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                            // Timestamp in nanoseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MotorState) Reset() {
	*x = MotorState{}
	mi := &file_types_control_motor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MotorState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MotorState) ProtoMessage() {}

func (x *MotorState) ProtoReflect() protoreflect.Message {
	mi := &file_types_control_motor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MotorState.ProtoReflect.Descriptor instead.
func (*MotorState) Descriptor() ([]byte, []int) {
	return file_types_control_motor_proto_rawDescGZIP(), []int{1}
}

func (x *MotorState) GetCurrentSpeed() float32 {
	if x != nil {
		return x.CurrentSpeed
	}
	return 0
}

func (x *MotorState) GetTargetSpeed() float32 {
	if x != nil {
		return x.TargetSpeed
	}
	return 0
}

func (x *MotorState) GetPidOutput() float32 {
	if x != nil {
		return x.PidOutput
	}
	return 0
}

func (x *MotorState) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *MotorState) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// MotorArrayConfig represents configuration for an array of motors
type MotorArrayConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Motors        []*MotorConfig         `protobuf:"bytes,1,rep,name=motors,proto3" json:"motors,omitempty"` // Motor configurations
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MotorArrayConfig) Reset() {
	*x = MotorArrayConfig{}
	mi := &file_types_control_motor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MotorArrayConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MotorArrayConfig) ProtoMessage() {}

func (x *MotorArrayConfig) ProtoReflect() protoreflect.Message {
	mi := &file_types_control_motor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MotorArrayConfig.ProtoReflect.Descriptor instead.
func (*MotorArrayConfig) Descriptor() ([]byte, []int) {
	return file_types_control_motor_proto_rawDescGZIP(), []int{2}
}

func (x *MotorArrayConfig) GetMotors() []*MotorConfig {
	if x != nil {
		return x.Motors
	}
	return nil
}

// MotorArrayState represents current state of an array of motors
type MotorArrayState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Motors        []*MotorState          `protobuf:"bytes,1,rep,name=motors,proto3" json:"motors,omitempty"`        // Motor states
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Timestamp in nanoseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MotorArrayState) Reset() {
	*x = MotorArrayState{}
	mi := &file_types_control_motor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MotorArrayState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MotorArrayState) ProtoMessage() {}

func (x *MotorArrayState) ProtoReflect() protoreflect.Message {
	mi := &file_types_control_motor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MotorArrayState.ProtoReflect.Descriptor instead.
func (*MotorArrayState) Descriptor() ([]byte, []int) {
	return file_types_control_motor_proto_rawDescGZIP(), []int{3}
}

func (x *MotorArrayState) GetMotors() []*MotorState {
	if x != nil {
		return x.Motors
	}
	return nil
}

func (x *MotorArrayState) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_types_control_motor_proto protoreflect.FileDescriptor

const file_types_control_motor_proto_rawDesc = "" +
	"\n" +
	"\x19types/control/motor.proto\x12\rtypes.control\x1a\x1atypes/control/motion.proto\"\xa6\x03\n" +
	"\vMotorConfig\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.types.control.MotorTypeR\x04type\x12\x17\n" +
	"\adir_pin\x18\x02 \x01(\rR\x06dirPin\x12\x17\n" +
	"\apwm_pin\x18\x03 \x01(\rR\x06pwmPin\x12\x13\n" +
	"\x05pin_a\x18\x04 \x01(\rR\x04pinA\x12\x13\n" +
	"\x05pin_b\x18\x05 \x01(\rR\x04pinB\x12\"\n" +
	"\rencoder_pin_a\x18\x06 \x01(\rR\vencoderPinA\x12\"\n" +
	"\rencoder_pin_b\x18\a \x01(\rR\vencoderPinB\x124\n" +
	"\tpid_gains\x18\b \x01(\v2\x17.types.control.PIDGainsR\bpidGains\x12\x1d\n" +
	"\n" +
	"max_output\x18\t \x01(\x02R\tmaxOutput\x12#\n" +
	"\rsample_period\x18\n" +
	" \x01(\x02R\fsamplePeriod\x12\x17\n" +
	"\amax_rpm\x18\v \x01(\x02R\x06maxRpm\x122\n" +
	"\x15counts_per_revolution\x18\f \x01(\x03R\x13countsPerRevolution\"\xad\x01\n" +
	"\n" +
	"MotorState\x12#\n" +
	"\rcurrent_speed\x18\x01 \x01(\x02R\fcurrentSpeed\x12!\n" +
	"\ftarget_speed\x18\x02 \x01(\x02R\vtargetSpeed\x12\x1d\n" +
	"\n" +
	"pid_output\x18\x03 \x01(\x02R\tpidOutput\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x03R\bposition\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"F\n" +
	"\x10MotorArrayConfig\x122\n" +
	"\x06motors\x18\x01 \x03(\v2\x1a.types.control.MotorConfigR\x06motors\"b\n" +
	"\x0fMotorArrayState\x121\n" +
	"\x06motors\x18\x01 \x03(\v2\x19.types.control.MotorStateR\x06motors\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp*q\n" +
	"\tMotorType\x12\x1a\n" +
	"\x16MOTOR_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12MOTOR_TYPE_DIR_PWM\x10\x01\x12\x15\n" +
	"\x11MOTOR_TYPE_AB_PWM\x10\x02\x12\x19\n" +
	"\x15MOTOR_TYPE_AB_DIR_PWM\x10\x03B\x9f\x01\n" +
	"\x11com.types.controlB\n" +
	"MotorProtoP\x01Z)github.com/itohio/EasyRobot/types/control\xa2\x02\x03TCX\xaa\x02\rTypes.Control\xca\x02\rTypes\\Control\xe2\x02\x19Types\\Control\\GPBMetadata\xea\x02\x0eTypes::Controlb\x06proto3"

var (
	file_types_control_motor_proto_rawDescOnce sync.Once
	file_types_control_motor_proto_rawDescData []byte
)

func file_types_control_motor_proto_rawDescGZIP() []byte {
	file_types_control_motor_proto_rawDescOnce.Do(func() {
		file_types_control_motor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_control_motor_proto_rawDesc), len(file_types_control_motor_proto_rawDesc)))
	})
	return file_types_control_motor_proto_rawDescData
}

var file_types_control_motor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_types_control_motor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_types_control_motor_proto_goTypes = []any{
	(MotorType)(0),           // 0: types.control.MotorType
	(*MotorConfig)(nil),      // 1: types.control.MotorConfig
	(*MotorState)(nil),       // 2: types.control.MotorState
	(*MotorArrayConfig)(nil), // 3: types.control.MotorArrayConfig
	(*MotorArrayState)(nil),  // 4: types.control.MotorArrayState
	(*PIDGains)(nil),         // 5: types.control.PIDGains
}
var file_types_control_motor_proto_depIdxs = []int32{
	0, // 0: types.control.MotorConfig.type:type_name -> types.control.MotorType
	5, // 1: types.control.MotorConfig.pid_gains:type_name -> types.control.PIDGains
	1, // 2: types.control.MotorArrayConfig.motors:type_name -> types.control.MotorConfig
	2, // 3: types.control.MotorArrayState.motors:type_name -> types.control.MotorState
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_types_control_motor_proto_init() }
func file_types_control_motor_proto_init() {
	if File_types_control_motor_proto != nil {
		return
	}
	file_types_control_motion_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_control_motor_proto_rawDesc), len(file_types_control_motor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_control_motor_proto_goTypes,
		DependencyIndexes: file_types_control_motor_proto_depIdxs,
		EnumInfos:         file_types_control_motor_proto_enumTypes,
		MessageInfos:      file_types_control_motor_proto_msgTypes,
	}.Build()
	File_types_control_motor_proto = out.File
	file_types_control_motor_proto_goTypes = nil
	file_types_control_motor_proto_depIdxs = nil
}
