// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: types/math/matrices.proto

package math

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Matrix2x2 represents a 2x2 matrix (row-major order)
type Matrix2X2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	M00           float32                `protobuf:"fixed32,1,opt,name=m00,proto3" json:"m00,omitempty"`
	M01           float32                `protobuf:"fixed32,2,opt,name=m01,proto3" json:"m01,omitempty"`
	M10           float32                `protobuf:"fixed32,3,opt,name=m10,proto3" json:"m10,omitempty"`
	M11           float32                `protobuf:"fixed32,4,opt,name=m11,proto3" json:"m11,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Matrix2X2) Reset() {
	*x = Matrix2X2{}
	mi := &file_types_math_matrices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Matrix2X2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matrix2X2) ProtoMessage() {}

func (x *Matrix2X2) ProtoReflect() protoreflect.Message {
	mi := &file_types_math_matrices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matrix2X2.ProtoReflect.Descriptor instead.
func (*Matrix2X2) Descriptor() ([]byte, []int) {
	return file_types_math_matrices_proto_rawDescGZIP(), []int{0}
}

func (x *Matrix2X2) GetM00() float32 {
	if x != nil {
		return x.M00
	}
	return 0
}

func (x *Matrix2X2) GetM01() float32 {
	if x != nil {
		return x.M01
	}
	return 0
}

func (x *Matrix2X2) GetM10() float32 {
	if x != nil {
		return x.M10
	}
	return 0
}

func (x *Matrix2X2) GetM11() float32 {
	if x != nil {
		return x.M11
	}
	return 0
}

// Matrix3x3 represents a 3x3 matrix (row-major order)
type Matrix3X3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	M00           float32                `protobuf:"fixed32,1,opt,name=m00,proto3" json:"m00,omitempty"`
	M01           float32                `protobuf:"fixed32,2,opt,name=m01,proto3" json:"m01,omitempty"`
	M02           float32                `protobuf:"fixed32,3,opt,name=m02,proto3" json:"m02,omitempty"`
	M10           float32                `protobuf:"fixed32,4,opt,name=m10,proto3" json:"m10,omitempty"`
	M11           float32                `protobuf:"fixed32,5,opt,name=m11,proto3" json:"m11,omitempty"`
	M12           float32                `protobuf:"fixed32,6,opt,name=m12,proto3" json:"m12,omitempty"`
	M20           float32                `protobuf:"fixed32,7,opt,name=m20,proto3" json:"m20,omitempty"`
	M21           float32                `protobuf:"fixed32,8,opt,name=m21,proto3" json:"m21,omitempty"`
	M22           float32                `protobuf:"fixed32,9,opt,name=m22,proto3" json:"m22,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Matrix3X3) Reset() {
	*x = Matrix3X3{}
	mi := &file_types_math_matrices_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Matrix3X3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matrix3X3) ProtoMessage() {}

func (x *Matrix3X3) ProtoReflect() protoreflect.Message {
	mi := &file_types_math_matrices_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matrix3X3.ProtoReflect.Descriptor instead.
func (*Matrix3X3) Descriptor() ([]byte, []int) {
	return file_types_math_matrices_proto_rawDescGZIP(), []int{1}
}

func (x *Matrix3X3) GetM00() float32 {
	if x != nil {
		return x.M00
	}
	return 0
}

func (x *Matrix3X3) GetM01() float32 {
	if x != nil {
		return x.M01
	}
	return 0
}

func (x *Matrix3X3) GetM02() float32 {
	if x != nil {
		return x.M02
	}
	return 0
}

func (x *Matrix3X3) GetM10() float32 {
	if x != nil {
		return x.M10
	}
	return 0
}

func (x *Matrix3X3) GetM11() float32 {
	if x != nil {
		return x.M11
	}
	return 0
}

func (x *Matrix3X3) GetM12() float32 {
	if x != nil {
		return x.M12
	}
	return 0
}

func (x *Matrix3X3) GetM20() float32 {
	if x != nil {
		return x.M20
	}
	return 0
}

func (x *Matrix3X3) GetM21() float32 {
	if x != nil {
		return x.M21
	}
	return 0
}

func (x *Matrix3X3) GetM22() float32 {
	if x != nil {
		return x.M22
	}
	return 0
}

// Matrix4x4 represents a 4x4 matrix (row-major order)
type Matrix4X4 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	M00           float32                `protobuf:"fixed32,1,opt,name=m00,proto3" json:"m00,omitempty"`
	M01           float32                `protobuf:"fixed32,2,opt,name=m01,proto3" json:"m01,omitempty"`
	M02           float32                `protobuf:"fixed32,3,opt,name=m02,proto3" json:"m02,omitempty"`
	M03           float32                `protobuf:"fixed32,4,opt,name=m03,proto3" json:"m03,omitempty"`
	M10           float32                `protobuf:"fixed32,5,opt,name=m10,proto3" json:"m10,omitempty"`
	M11           float32                `protobuf:"fixed32,6,opt,name=m11,proto3" json:"m11,omitempty"`
	M12           float32                `protobuf:"fixed32,7,opt,name=m12,proto3" json:"m12,omitempty"`
	M13           float32                `protobuf:"fixed32,8,opt,name=m13,proto3" json:"m13,omitempty"`
	M20           float32                `protobuf:"fixed32,9,opt,name=m20,proto3" json:"m20,omitempty"`
	M21           float32                `protobuf:"fixed32,10,opt,name=m21,proto3" json:"m21,omitempty"`
	M22           float32                `protobuf:"fixed32,11,opt,name=m22,proto3" json:"m22,omitempty"`
	M23           float32                `protobuf:"fixed32,12,opt,name=m23,proto3" json:"m23,omitempty"`
	M30           float32                `protobuf:"fixed32,13,opt,name=m30,proto3" json:"m30,omitempty"`
	M31           float32                `protobuf:"fixed32,14,opt,name=m31,proto3" json:"m31,omitempty"`
	M32           float32                `protobuf:"fixed32,15,opt,name=m32,proto3" json:"m32,omitempty"`
	M33           float32                `protobuf:"fixed32,16,opt,name=m33,proto3" json:"m33,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Matrix4X4) Reset() {
	*x = Matrix4X4{}
	mi := &file_types_math_matrices_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Matrix4X4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matrix4X4) ProtoMessage() {}

func (x *Matrix4X4) ProtoReflect() protoreflect.Message {
	mi := &file_types_math_matrices_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matrix4X4.ProtoReflect.Descriptor instead.
func (*Matrix4X4) Descriptor() ([]byte, []int) {
	return file_types_math_matrices_proto_rawDescGZIP(), []int{2}
}

func (x *Matrix4X4) GetM00() float32 {
	if x != nil {
		return x.M00
	}
	return 0
}

func (x *Matrix4X4) GetM01() float32 {
	if x != nil {
		return x.M01
	}
	return 0
}

func (x *Matrix4X4) GetM02() float32 {
	if x != nil {
		return x.M02
	}
	return 0
}

func (x *Matrix4X4) GetM03() float32 {
	if x != nil {
		return x.M03
	}
	return 0
}

func (x *Matrix4X4) GetM10() float32 {
	if x != nil {
		return x.M10
	}
	return 0
}

func (x *Matrix4X4) GetM11() float32 {
	if x != nil {
		return x.M11
	}
	return 0
}

func (x *Matrix4X4) GetM12() float32 {
	if x != nil {
		return x.M12
	}
	return 0
}

func (x *Matrix4X4) GetM13() float32 {
	if x != nil {
		return x.M13
	}
	return 0
}

func (x *Matrix4X4) GetM20() float32 {
	if x != nil {
		return x.M20
	}
	return 0
}

func (x *Matrix4X4) GetM21() float32 {
	if x != nil {
		return x.M21
	}
	return 0
}

func (x *Matrix4X4) GetM22() float32 {
	if x != nil {
		return x.M22
	}
	return 0
}

func (x *Matrix4X4) GetM23() float32 {
	if x != nil {
		return x.M23
	}
	return 0
}

func (x *Matrix4X4) GetM30() float32 {
	if x != nil {
		return x.M30
	}
	return 0
}

func (x *Matrix4X4) GetM31() float32 {
	if x != nil {
		return x.M31
	}
	return 0
}

func (x *Matrix4X4) GetM32() float32 {
	if x != nil {
		return x.M32
	}
	return 0
}

func (x *Matrix4X4) GetM33() float32 {
	if x != nil {
		return x.M33
	}
	return 0
}

// Matrix3x4 represents a 3x4 matrix (row-major order)
type Matrix3X4 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	M00           float32                `protobuf:"fixed32,1,opt,name=m00,proto3" json:"m00,omitempty"`
	M01           float32                `protobuf:"fixed32,2,opt,name=m01,proto3" json:"m01,omitempty"`
	M02           float32                `protobuf:"fixed32,3,opt,name=m02,proto3" json:"m02,omitempty"`
	M03           float32                `protobuf:"fixed32,4,opt,name=m03,proto3" json:"m03,omitempty"`
	M10           float32                `protobuf:"fixed32,5,opt,name=m10,proto3" json:"m10,omitempty"`
	M11           float32                `protobuf:"fixed32,6,opt,name=m11,proto3" json:"m11,omitempty"`
	M12           float32                `protobuf:"fixed32,7,opt,name=m12,proto3" json:"m12,omitempty"`
	M13           float32                `protobuf:"fixed32,8,opt,name=m13,proto3" json:"m13,omitempty"`
	M20           float32                `protobuf:"fixed32,9,opt,name=m20,proto3" json:"m20,omitempty"`
	M21           float32                `protobuf:"fixed32,10,opt,name=m21,proto3" json:"m21,omitempty"`
	M22           float32                `protobuf:"fixed32,11,opt,name=m22,proto3" json:"m22,omitempty"`
	M23           float32                `protobuf:"fixed32,12,opt,name=m23,proto3" json:"m23,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Matrix3X4) Reset() {
	*x = Matrix3X4{}
	mi := &file_types_math_matrices_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Matrix3X4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matrix3X4) ProtoMessage() {}

func (x *Matrix3X4) ProtoReflect() protoreflect.Message {
	mi := &file_types_math_matrices_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matrix3X4.ProtoReflect.Descriptor instead.
func (*Matrix3X4) Descriptor() ([]byte, []int) {
	return file_types_math_matrices_proto_rawDescGZIP(), []int{3}
}

func (x *Matrix3X4) GetM00() float32 {
	if x != nil {
		return x.M00
	}
	return 0
}

func (x *Matrix3X4) GetM01() float32 {
	if x != nil {
		return x.M01
	}
	return 0
}

func (x *Matrix3X4) GetM02() float32 {
	if x != nil {
		return x.M02
	}
	return 0
}

func (x *Matrix3X4) GetM03() float32 {
	if x != nil {
		return x.M03
	}
	return 0
}

func (x *Matrix3X4) GetM10() float32 {
	if x != nil {
		return x.M10
	}
	return 0
}

func (x *Matrix3X4) GetM11() float32 {
	if x != nil {
		return x.M11
	}
	return 0
}

func (x *Matrix3X4) GetM12() float32 {
	if x != nil {
		return x.M12
	}
	return 0
}

func (x *Matrix3X4) GetM13() float32 {
	if x != nil {
		return x.M13
	}
	return 0
}

func (x *Matrix3X4) GetM20() float32 {
	if x != nil {
		return x.M20
	}
	return 0
}

func (x *Matrix3X4) GetM21() float32 {
	if x != nil {
		return x.M21
	}
	return 0
}

func (x *Matrix3X4) GetM22() float32 {
	if x != nil {
		return x.M22
	}
	return 0
}

func (x *Matrix3X4) GetM23() float32 {
	if x != nil {
		return x.M23
	}
	return 0
}

// Matrix4x3 represents a 4x3 matrix (row-major order)
type Matrix4X3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	M00           float32                `protobuf:"fixed32,1,opt,name=m00,proto3" json:"m00,omitempty"`
	M01           float32                `protobuf:"fixed32,2,opt,name=m01,proto3" json:"m01,omitempty"`
	M02           float32                `protobuf:"fixed32,3,opt,name=m02,proto3" json:"m02,omitempty"`
	M10           float32                `protobuf:"fixed32,4,opt,name=m10,proto3" json:"m10,omitempty"`
	M11           float32                `protobuf:"fixed32,5,opt,name=m11,proto3" json:"m11,omitempty"`
	M12           float32                `protobuf:"fixed32,6,opt,name=m12,proto3" json:"m12,omitempty"`
	M20           float32                `protobuf:"fixed32,7,opt,name=m20,proto3" json:"m20,omitempty"`
	M21           float32                `protobuf:"fixed32,8,opt,name=m21,proto3" json:"m21,omitempty"`
	M22           float32                `protobuf:"fixed32,9,opt,name=m22,proto3" json:"m22,omitempty"`
	M30           float32                `protobuf:"fixed32,10,opt,name=m30,proto3" json:"m30,omitempty"`
	M31           float32                `protobuf:"fixed32,11,opt,name=m31,proto3" json:"m31,omitempty"`
	M32           float32                `protobuf:"fixed32,12,opt,name=m32,proto3" json:"m32,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Matrix4X3) Reset() {
	*x = Matrix4X3{}
	mi := &file_types_math_matrices_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Matrix4X3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matrix4X3) ProtoMessage() {}

func (x *Matrix4X3) ProtoReflect() protoreflect.Message {
	mi := &file_types_math_matrices_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matrix4X3.ProtoReflect.Descriptor instead.
func (*Matrix4X3) Descriptor() ([]byte, []int) {
	return file_types_math_matrices_proto_rawDescGZIP(), []int{4}
}

func (x *Matrix4X3) GetM00() float32 {
	if x != nil {
		return x.M00
	}
	return 0
}

func (x *Matrix4X3) GetM01() float32 {
	if x != nil {
		return x.M01
	}
	return 0
}

func (x *Matrix4X3) GetM02() float32 {
	if x != nil {
		return x.M02
	}
	return 0
}

func (x *Matrix4X3) GetM10() float32 {
	if x != nil {
		return x.M10
	}
	return 0
}

func (x *Matrix4X3) GetM11() float32 {
	if x != nil {
		return x.M11
	}
	return 0
}

func (x *Matrix4X3) GetM12() float32 {
	if x != nil {
		return x.M12
	}
	return 0
}

func (x *Matrix4X3) GetM20() float32 {
	if x != nil {
		return x.M20
	}
	return 0
}

func (x *Matrix4X3) GetM21() float32 {
	if x != nil {
		return x.M21
	}
	return 0
}

func (x *Matrix4X3) GetM22() float32 {
	if x != nil {
		return x.M22
	}
	return 0
}

func (x *Matrix4X3) GetM30() float32 {
	if x != nil {
		return x.M30
	}
	return 0
}

func (x *Matrix4X3) GetM31() float32 {
	if x != nil {
		return x.M31
	}
	return 0
}

func (x *Matrix4X3) GetM32() float32 {
	if x != nil {
		return x.M32
	}
	return 0
}

// Matrix represents a generic variable-size matrix (row-major order)
type Matrix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          int32                  `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          int32                  `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Data          []float32              `protobuf:"fixed32,3,rep,packed,name=data,proto3" json:"data,omitempty"` // Flattened row-major data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Matrix) Reset() {
	*x = Matrix{}
	mi := &file_types_math_matrices_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Matrix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matrix) ProtoMessage() {}

func (x *Matrix) ProtoReflect() protoreflect.Message {
	mi := &file_types_math_matrices_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matrix.ProtoReflect.Descriptor instead.
func (*Matrix) Descriptor() ([]byte, []int) {
	return file_types_math_matrices_proto_rawDescGZIP(), []int{5}
}

func (x *Matrix) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Matrix) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Matrix) GetData() []float32 {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_types_math_matrices_proto protoreflect.FileDescriptor

const file_types_math_matrices_proto_rawDesc = "" +
	"\n" +
	"\x19types/math/matrices.proto\x12\n" +
	"types.math\"S\n" +
	"\tMatrix2x2\x12\x10\n" +
	"\x03m00\x18\x01 \x01(\x02R\x03m00\x12\x10\n" +
	"\x03m01\x18\x02 \x01(\x02R\x03m01\x12\x10\n" +
	"\x03m10\x18\x03 \x01(\x02R\x03m10\x12\x10\n" +
	"\x03m11\x18\x04 \x01(\x02R\x03m11\"\xad\x01\n" +
	"\tMatrix3x3\x12\x10\n" +
	"\x03m00\x18\x01 \x01(\x02R\x03m00\x12\x10\n" +
	"\x03m01\x18\x02 \x01(\x02R\x03m01\x12\x10\n" +
	"\x03m02\x18\x03 \x01(\x02R\x03m02\x12\x10\n" +
	"\x03m10\x18\x04 \x01(\x02R\x03m10\x12\x10\n" +
	"\x03m11\x18\x05 \x01(\x02R\x03m11\x12\x10\n" +
	"\x03m12\x18\x06 \x01(\x02R\x03m12\x12\x10\n" +
	"\x03m20\x18\a \x01(\x02R\x03m20\x12\x10\n" +
	"\x03m21\x18\b \x01(\x02R\x03m21\x12\x10\n" +
	"\x03m22\x18\t \x01(\x02R\x03m22\"\xab\x02\n" +
	"\tMatrix4x4\x12\x10\n" +
	"\x03m00\x18\x01 \x01(\x02R\x03m00\x12\x10\n" +
	"\x03m01\x18\x02 \x01(\x02R\x03m01\x12\x10\n" +
	"\x03m02\x18\x03 \x01(\x02R\x03m02\x12\x10\n" +
	"\x03m03\x18\x04 \x01(\x02R\x03m03\x12\x10\n" +
	"\x03m10\x18\x05 \x01(\x02R\x03m10\x12\x10\n" +
	"\x03m11\x18\x06 \x01(\x02R\x03m11\x12\x10\n" +
	"\x03m12\x18\a \x01(\x02R\x03m12\x12\x10\n" +
	"\x03m13\x18\b \x01(\x02R\x03m13\x12\x10\n" +
	"\x03m20\x18\t \x01(\x02R\x03m20\x12\x10\n" +
	"\x03m21\x18\n" +
	" \x01(\x02R\x03m21\x12\x10\n" +
	"\x03m22\x18\v \x01(\x02R\x03m22\x12\x10\n" +
	"\x03m23\x18\f \x01(\x02R\x03m23\x12\x10\n" +
	"\x03m30\x18\r \x01(\x02R\x03m30\x12\x10\n" +
	"\x03m31\x18\x0e \x01(\x02R\x03m31\x12\x10\n" +
	"\x03m32\x18\x0f \x01(\x02R\x03m32\x12\x10\n" +
	"\x03m33\x18\x10 \x01(\x02R\x03m33\"\xe3\x01\n" +
	"\tMatrix3x4\x12\x10\n" +
	"\x03m00\x18\x01 \x01(\x02R\x03m00\x12\x10\n" +
	"\x03m01\x18\x02 \x01(\x02R\x03m01\x12\x10\n" +
	"\x03m02\x18\x03 \x01(\x02R\x03m02\x12\x10\n" +
	"\x03m03\x18\x04 \x01(\x02R\x03m03\x12\x10\n" +
	"\x03m10\x18\x05 \x01(\x02R\x03m10\x12\x10\n" +
	"\x03m11\x18\x06 \x01(\x02R\x03m11\x12\x10\n" +
	"\x03m12\x18\a \x01(\x02R\x03m12\x12\x10\n" +
	"\x03m13\x18\b \x01(\x02R\x03m13\x12\x10\n" +
	"\x03m20\x18\t \x01(\x02R\x03m20\x12\x10\n" +
	"\x03m21\x18\n" +
	" \x01(\x02R\x03m21\x12\x10\n" +
	"\x03m22\x18\v \x01(\x02R\x03m22\x12\x10\n" +
	"\x03m23\x18\f \x01(\x02R\x03m23\"\xe3\x01\n" +
	"\tMatrix4x3\x12\x10\n" +
	"\x03m00\x18\x01 \x01(\x02R\x03m00\x12\x10\n" +
	"\x03m01\x18\x02 \x01(\x02R\x03m01\x12\x10\n" +
	"\x03m02\x18\x03 \x01(\x02R\x03m02\x12\x10\n" +
	"\x03m10\x18\x04 \x01(\x02R\x03m10\x12\x10\n" +
	"\x03m11\x18\x05 \x01(\x02R\x03m11\x12\x10\n" +
	"\x03m12\x18\x06 \x01(\x02R\x03m12\x12\x10\n" +
	"\x03m20\x18\a \x01(\x02R\x03m20\x12\x10\n" +
	"\x03m21\x18\b \x01(\x02R\x03m21\x12\x10\n" +
	"\x03m22\x18\t \x01(\x02R\x03m22\x12\x10\n" +
	"\x03m30\x18\n" +
	" \x01(\x02R\x03m30\x12\x10\n" +
	"\x03m31\x18\v \x01(\x02R\x03m31\x12\x10\n" +
	"\x03m32\x18\f \x01(\x02R\x03m32\"D\n" +
	"\x06Matrix\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\x05R\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04data\x18\x03 \x03(\x02R\x04dataB\x90\x01\n" +
	"\x0ecom.types.mathB\rMatricesProtoP\x01Z&github.com/itohio/EasyRobot/types/math\xa2\x02\x03TMX\xaa\x02\n" +
	"Types.Math\xca\x02\n" +
	"Types\\Math\xe2\x02\x16Types\\Math\\GPBMetadata\xea\x02\vTypes::Mathb\x06proto3"

var (
	file_types_math_matrices_proto_rawDescOnce sync.Once
	file_types_math_matrices_proto_rawDescData []byte
)

func file_types_math_matrices_proto_rawDescGZIP() []byte {
	file_types_math_matrices_proto_rawDescOnce.Do(func() {
		file_types_math_matrices_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_math_matrices_proto_rawDesc), len(file_types_math_matrices_proto_rawDesc)))
	})
	return file_types_math_matrices_proto_rawDescData
}

var file_types_math_matrices_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_types_math_matrices_proto_goTypes = []any{
	(*Matrix2X2)(nil), // 0: types.math.Matrix2x2
	(*Matrix3X3)(nil), // 1: types.math.Matrix3x3
	(*Matrix4X4)(nil), // 2: types.math.Matrix4x4
	(*Matrix3X4)(nil), // 3: types.math.Matrix3x4
	(*Matrix4X3)(nil), // 4: types.math.Matrix4x3
	(*Matrix)(nil),    // 5: types.math.Matrix
}
var file_types_math_matrices_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_types_math_matrices_proto_init() }
func file_types_math_matrices_proto_init() {
	if File_types_math_matrices_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_math_matrices_proto_rawDesc), len(file_types_math_matrices_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_math_matrices_proto_goTypes,
		DependencyIndexes: file_types_math_matrices_proto_depIdxs,
		MessageInfos:      file_types_math_matrices_proto_msgTypes,
	}.Build()
	File_types_math_matrices_proto = out.File
	file_types_math_matrices_proto_goTypes = nil
	file_types_math_matrices_proto_depIdxs = nil
}
