// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: types/math/matrices.proto

package math

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Matrix2x2 represents a 2x2 matrix (row-major order)
type Matrix2X2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	M00           float32                `protobuf:"fixed32,1,opt,name=m00,proto3" json:"m00,omitempty"`
	M01           float32                `protobuf:"fixed32,2,opt,name=m01,proto3" json:"m01,omitempty"`
	M10           float32                `protobuf:"fixed32,3,opt,name=m10,proto3" json:"m10,omitempty"`
	M11           float32                `protobuf:"fixed32,4,opt,name=m11,proto3" json:"m11,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Matrix2X2) Reset() {
	*x = Matrix2X2{}
	mi := &file_types_math_matrices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Matrix2X2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matrix2X2) ProtoMessage() {}

func (x *Matrix2X2) ProtoReflect() protoreflect.Message {
	mi := &file_types_math_matrices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matrix2X2.ProtoReflect.Descriptor instead.
func (*Matrix2X2) Descriptor() ([]byte, []int) {
	return file_types_math_matrices_proto_rawDescGZIP(), []int{0}
}

func (x *Matrix2X2) GetM00() float32 {
	if x != nil {
		return x.M00
	}
	return 0
}

func (x *Matrix2X2) GetM01() float32 {
	if x != nil {
		return x.M01
	}
	return 0
}

func (x *Matrix2X2) GetM10() float32 {
	if x != nil {
		return x.M10
	}
	return 0
}

func (x *Matrix2X2) GetM11() float32 {
	if x != nil {
		return x.M11
	}
	return 0
}

// Matrix3x3 represents a 3x3 matrix (row-major order)
type Matrix3X3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	M00           float32                `protobuf:"fixed32,1,opt,name=m00,proto3" json:"m00,omitempty"`
	M01           float32                `protobuf:"fixed32,2,opt,name=m01,proto3" json:"m01,omitempty"`
	M02           float32                `protobuf:"fixed32,3,opt,name=m02,proto3" json:"m02,omitempty"`
	M10           float32                `protobuf:"fixed32,4,opt,name=m10,proto3" json:"m10,omitempty"`
	M11           float32                `protobuf:"fixed32,5,opt,name=m11,proto3" json:"m11,omitempty"`
	M12           float32                `protobuf:"fixed32,6,opt,name=m12,proto3" json:"m12,omitempty"`
	M20           float32                `protobuf:"fixed32,7,opt,name=m20,proto3" json:"m20,omitempty"`
	M21           float32                `protobuf:"fixed32,8,opt,name=m21,proto3" json:"m21,omitempty"`
	M22           float32                `protobuf:"fixed32,9,opt,name=m22,proto3" json:"m22,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Matrix3X3) Reset() {
	*x = Matrix3X3{}
	mi := &file_types_math_matrices_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Matrix3X3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matrix3X3) ProtoMessage() {}

func (x *Matrix3X3) ProtoReflect() protoreflect.Message {
	mi := &file_types_math_matrices_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matrix3X3.ProtoReflect.Descriptor instead.
func (*Matrix3X3) Descriptor() ([]byte, []int) {
	return file_types_math_matrices_proto_rawDescGZIP(), []int{1}
}

func (x *Matrix3X3) GetM00() float32 {
	if x != nil {
		return x.M00
	}
	return 0
}

func (x *Matrix3X3) GetM01() float32 {
	if x != nil {
		return x.M01
	}
	return 0
}

func (x *Matrix3X3) GetM02() float32 {
	if x != nil {
		return x.M02
	}
	return 0
}

func (x *Matrix3X3) GetM10() float32 {
	if x != nil {
		return x.M10
	}
	return 0
}

func (x *Matrix3X3) GetM11() float32 {
	if x != nil {
		return x.M11
	}
	return 0
}

func (x *Matrix3X3) GetM12() float32 {
	if x != nil {
		return x.M12
	}
	return 0
}

func (x *Matrix3X3) GetM20() float32 {
	if x != nil {
		return x.M20
	}
	return 0
}

func (x *Matrix3X3) GetM21() float32 {
	if x != nil {
		return x.M21
	}
	return 0
}

func (x *Matrix3X3) GetM22() float32 {
	if x != nil {
		return x.M22
	}
	return 0
}

// Matrix4x4 represents a 4x4 matrix (row-major order)
type Matrix4X4 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	M00           float32                `protobuf:"fixed32,1,opt,name=m00,proto3" json:"m00,omitempty"`
	M01           float32                `protobuf:"fixed32,2,opt,name=m01,proto3" json:"m01,omitempty"`
	M02           float32                `protobuf:"fixed32,3,opt,name=m02,proto3" json:"m02,omitempty"`
	M03           float32                `protobuf:"fixed32,4,opt,name=m03,proto3" json:"m03,omitempty"`
	M10           float32                `protobuf:"fixed32,5,opt,name=m10,proto3" json:"m10,omitempty"`
	M11           float32                `protobuf:"fixed32,6,opt,name=m11,proto3" json:"m11,omitempty"`
	M12           float32                `protobuf:"fixed32,7,opt,name=m12,proto3" json:"m12,omitempty"`
	M13           float32                `protobuf:"fixed32,8,opt,name=m13,proto3" json:"m13,omitempty"`
	M20           float32                `protobuf:"fixed32,9,opt,name=m20,proto3" json:"m20,omitempty"`
	M21           float32                `protobuf:"fixed32,10,opt,name=m21,proto3" json:"m21,omitempty"`
	M22           float32                `protobuf:"fixed32,11,opt,name=m22,proto3" json:"m22,omitempty"`
	M23           float32                `protobuf:"fixed32,12,opt,name=m23,proto3" json:"m23,omitempty"`
	M30           float32                `protobuf:"fixed32,13,opt,name=m30,proto3" json:"m30,omitempty"`
	M31           float32                `protobuf:"fixed32,14,opt,name=m31,proto3" json:"m31,omitempty"`
	M32           float32                `protobuf:"fixed32,15,opt,name=m32,proto3" json:"m32,omitempty"`
	M33           float32                `protobuf:"fixed32,16,opt,name=m33,proto3" json:"m33,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Matrix4X4) Reset() {
	*x = Matrix4X4{}
	mi := &file_types_math_matrices_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Matrix4X4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matrix4X4) ProtoMessage() {}

func (x *Matrix4X4) ProtoReflect() protoreflect.Message {
	mi := &file_types_math_matrices_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matrix4X4.ProtoReflect.Descriptor instead.
func (*Matrix4X4) Descriptor() ([]byte, []int) {
	return file_types_math_matrices_proto_rawDescGZIP(), []int{2}
}

func (x *Matrix4X4) GetM00() float32 {
	if x != nil {
		return x.M00
	}
	return 0
}

func (x *Matrix4X4) GetM01() float32 {
	if x != nil {
		return x.M01
	}
	return 0
}

func (x *Matrix4X4) GetM02() float32 {
	if x != nil {
		return x.M02
	}
	return 0
}

func (x *Matrix4X4) GetM03() float32 {
	if x != nil {
		return x.M03
	}
	return 0
}

func (x *Matrix4X4) GetM10() float32 {
	if x != nil {
		return x.M10
	}
	return 0
}

func (x *Matrix4X4) GetM11() float32 {
	if x != nil {
		return x.M11
	}
	return 0
}

func (x *Matrix4X4) GetM12() float32 {
	if x != nil {
		return x.M12
	}
	return 0
}

func (x *Matrix4X4) GetM13() float32 {
	if x != nil {
		return x.M13
	}
	return 0
}

func (x *Matrix4X4) GetM20() float32 {
	if x != nil {
		return x.M20
	}
	return 0
}

func (x *Matrix4X4) GetM21() float32 {
	if x != nil {
		return x.M21
	}
	return 0
}

func (x *Matrix4X4) GetM22() float32 {
	if x != nil {
		return x.M22
	}
	return 0
}

func (x *Matrix4X4) GetM23() float32 {
	if x != nil {
		return x.M23
	}
	return 0
}

func (x *Matrix4X4) GetM30() float32 {
	if x != nil {
		return x.M30
	}
	return 0
}

func (x *Matrix4X4) GetM31() float32 {
	if x != nil {
		return x.M31
	}
	return 0
}

func (x *Matrix4X4) GetM32() float32 {
	if x != nil {
		return x.M32
	}
	return 0
}

func (x *Matrix4X4) GetM33() float32 {
	if x != nil {
		return x.M33
	}
	return 0
}

// Matrix3x4 represents a 3x4 matrix (row-major order)
type Matrix3X4 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	M00           float32                `protobuf:"fixed32,1,opt,name=m00,proto3" json:"m00,omitempty"`
	M01           float32                `protobuf:"fixed32,2,opt,name=m01,proto3" json:"m01,omitempty"`
	M02           float32                `protobuf:"fixed32,3,opt,name=m02,proto3" json:"m02,omitempty"`
	M03           float32                `protobuf:"fixed32,4,opt,name=m03,proto3" json:"m03,omitempty"`
	M10           float32                `protobuf:"fixed32,5,opt,name=m10,proto3" json:"m10,omitempty"`
	M11           float32                `protobuf:"fixed32,6,opt,name=m11,proto3" json:"m11,omitempty"`
	M12           float32                `protobuf:"fixed32,7,opt,name=m12,proto3" json:"m12,omitempty"`
	M13           float32                `protobuf:"fixed32,8,opt,name=m13,proto3" json:"m13,omitempty"`
	M20           float32                `protobuf:"fixed32,9,opt,name=m20,proto3" json:"m20,omitempty"`
	M21           float32                `protobuf:"fixed32,10,opt,name=m21,proto3" json:"m21,omitempty"`
	M22           float32                `protobuf:"fixed32,11,opt,name=m22,proto3" json:"m22,omitempty"`
	M23           float32                `protobuf:"fixed32,12,opt,name=m23,proto3" json:"m23,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Matrix3X4) Reset() {
	*x = Matrix3X4{}
	mi := &file_types_math_matrices_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Matrix3X4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matrix3X4) ProtoMessage() {}

func (x *Matrix3X4) ProtoReflect() protoreflect.Message {
	mi := &file_types_math_matrices_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matrix3X4.ProtoReflect.Descriptor instead.
func (*Matrix3X4) Descriptor() ([]byte, []int) {
	return file_types_math_matrices_proto_rawDescGZIP(), []int{3}
}

func (x *Matrix3X4) GetM00() float32 {
	if x != nil {
		return x.M00
	}
	return 0
}

func (x *Matrix3X4) GetM01() float32 {
	if x != nil {
		return x.M01
	}
	return 0
}

func (x *Matrix3X4) GetM02() float32 {
	if x != nil {
		return x.M02
	}
	return 0
}

func (x *Matrix3X4) GetM03() float32 {
	if x != nil {
		return x.M03
	}
	return 0
}

func (x *Matrix3X4) GetM10() float32 {
	if x != nil {
		return x.M10
	}
	return 0
}

func (x *Matrix3X4) GetM11() float32 {
	if x != nil {
		return x.M11
	}
	return 0
}

func (x *Matrix3X4) GetM12() float32 {
	if x != nil {
		return x.M12
	}
	return 0
}

func (x *Matrix3X4) GetM13() float32 {
	if x != nil {
		return x.M13
	}
	return 0
}

func (x *Matrix3X4) GetM20() float32 {
	if x != nil {
		return x.M20
	}
	return 0
}

func (x *Matrix3X4) GetM21() float32 {
	if x != nil {
		return x.M21
	}
	return 0
}

func (x *Matrix3X4) GetM22() float32 {
	if x != nil {
		return x.M22
	}
	return 0
}

func (x *Matrix3X4) GetM23() float32 {
	if x != nil {
		return x.M23
	}
	return 0
}

// Matrix4x3 represents a 4x3 matrix (row-major order)
type Matrix4X3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	M00           float32                `protobuf:"fixed32,1,opt,name=m00,proto3" json:"m00,omitempty"`
	M01           float32                `protobuf:"fixed32,2,opt,name=m01,proto3" json:"m01,omitempty"`
	M02           float32                `protobuf:"fixed32,3,opt,name=m02,proto3" json:"m02,omitempty"`
	M10           float32                `protobuf:"fixed32,4,opt,name=m10,proto3" json:"m10,omitempty"`
	M11           float32                `protobuf:"fixed32,5,opt,name=m11,proto3" json:"m11,omitempty"`
	M12           float32                `protobuf:"fixed32,6,opt,name=m12,proto3" json:"m12,omitempty"`
	M20           float32                `protobuf:"fixed32,7,opt,name=m20,proto3" json:"m20,omitempty"`
	M21           float32                `protobuf:"fixed32,8,opt,name=m21,proto3" json:"m21,omitempty"`
	M22           float32                `protobuf:"fixed32,9,opt,name=m22,proto3" json:"m22,omitempty"`
	M30           float32                `protobuf:"fixed32,10,opt,name=m30,proto3" json:"m30,omitempty"`
	M31           float32                `protobuf:"fixed32,11,opt,name=m31,proto3" json:"m31,omitempty"`
	M32           float32                `protobuf:"fixed32,12,opt,name=m32,proto3" json:"m32,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Matrix4X3) Reset() {
	*x = Matrix4X3{}
	mi := &file_types_math_matrices_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Matrix4X3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matrix4X3) ProtoMessage() {}

func (x *Matrix4X3) ProtoReflect() protoreflect.Message {
	mi := &file_types_math_matrices_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matrix4X3.ProtoReflect.Descriptor instead.
func (*Matrix4X3) Descriptor() ([]byte, []int) {
	return file_types_math_matrices_proto_rawDescGZIP(), []int{4}
}

func (x *Matrix4X3) GetM00() float32 {
	if x != nil {
		return x.M00
	}
	return 0
}

func (x *Matrix4X3) GetM01() float32 {
	if x != nil {
		return x.M01
	}
	return 0
}

func (x *Matrix4X3) GetM02() float32 {
	if x != nil {
		return x.M02
	}
	return 0
}

func (x *Matrix4X3) GetM10() float32 {
	if x != nil {
		return x.M10
	}
	return 0
}

func (x *Matrix4X3) GetM11() float32 {
	if x != nil {
		return x.M11
	}
	return 0
}

func (x *Matrix4X3) GetM12() float32 {
	if x != nil {
		return x.M12
	}
	return 0
}

func (x *Matrix4X3) GetM20() float32 {
	if x != nil {
		return x.M20
	}
	return 0
}

func (x *Matrix4X3) GetM21() float32 {
	if x != nil {
		return x.M21
	}
	return 0
}

func (x *Matrix4X3) GetM22() float32 {
	if x != nil {
		return x.M22
	}
	return 0
}

func (x *Matrix4X3) GetM30() float32 {
	if x != nil {
		return x.M30
	}
	return 0
}

func (x *Matrix4X3) GetM31() float32 {
	if x != nil {
		return x.M31
	}
	return 0
}

func (x *Matrix4X3) GetM32() float32 {
	if x != nil {
		return x.M32
	}
	return 0
}

// Matrix represents a generic variable-size matrix (row-major order)
type Matrix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          int32                  `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          int32                  `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Data          []float32              `protobuf:"fixed32,3,rep,packed,name=data,proto3" json:"data,omitempty"` // Flattened row-major data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Matrix) Reset() {
	*x = Matrix{}
	mi := &file_types_math_matrices_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Matrix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matrix) ProtoMessage() {}

func (x *Matrix) ProtoReflect() protoreflect.Message {
	mi := &file_types_math_matrices_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matrix.ProtoReflect.Descriptor instead.
func (*Matrix) Descriptor() ([]byte, []int) {
	return file_types_math_matrices_proto_rawDescGZIP(), []int{5}
}

func (x *Matrix) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Matrix) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Matrix) GetData() []float32 {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_types_math_matrices_proto protoreflect.FileDescriptor

var file_types_math_matrices_proto_rawDesc = string([]byte{
	0x0a, 0x19, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x2f, 0x6d, 0x61, 0x74,
	0x72, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x6d, 0x61, 0x74, 0x68, 0x22, 0x53, 0x0a, 0x09, 0x4d, 0x61, 0x74, 0x72, 0x69,
	0x78, 0x32, 0x78, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x30, 0x30, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x03, 0x6d, 0x30, 0x30, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x30, 0x31, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x30, 0x31, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x31, 0x30, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x31, 0x30, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x31,
	0x31, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x31, 0x31, 0x22, 0xad, 0x01, 0x0a,
	0x09, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x33, 0x78, 0x33, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x30,
	0x30, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x30, 0x30, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x30, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x30, 0x31, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x30, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x30, 0x32,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x31, 0x30, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d,
	0x31, 0x30, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x31, 0x31, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x03, 0x6d, 0x31, 0x31, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x31, 0x32, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x03, 0x6d, 0x31, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x32, 0x30, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x32, 0x30, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x32, 0x31, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x32, 0x31, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x32,
	0x32, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x32, 0x32, 0x22, 0xab, 0x02, 0x0a,
	0x09, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x34, 0x78, 0x34, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x30,
	0x30, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x30, 0x30, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x30, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x30, 0x31, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x30, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x30, 0x32,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x30, 0x33, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d,
	0x30, 0x33, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x31, 0x30, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x03, 0x6d, 0x31, 0x30, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x31, 0x31, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x03, 0x6d, 0x31, 0x31, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x31, 0x32, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x31, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x31, 0x33, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x31, 0x33, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x32,
	0x30, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x32, 0x30, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x32, 0x31, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x32, 0x31, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x32, 0x32, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x32, 0x32,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x32, 0x33, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d,
	0x32, 0x33, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x33, 0x30, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x03, 0x6d, 0x33, 0x30, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x33, 0x31, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x03, 0x6d, 0x33, 0x31, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x33, 0x32, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x33, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x33, 0x33, 0x18,
	0x10, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x33, 0x33, 0x22, 0xe3, 0x01, 0x0a, 0x09, 0x4d,
	0x61, 0x74, 0x72, 0x69, 0x78, 0x33, 0x78, 0x34, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x30, 0x30, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x30, 0x30, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x30,
	0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x30, 0x31, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x30, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x30, 0x32, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x30, 0x33, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x30, 0x33,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x31, 0x30, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d,
	0x31, 0x30, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x31, 0x31, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x03, 0x6d, 0x31, 0x31, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x31, 0x32, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x03, 0x6d, 0x31, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x31, 0x33, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x31, 0x33, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x32, 0x30, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x32, 0x30, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x32,
	0x31, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x32, 0x31, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x32, 0x32, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x32, 0x32, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x32, 0x33, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x32, 0x33,
	0x22, 0xe3, 0x01, 0x0a, 0x09, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x34, 0x78, 0x33, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x30, 0x30, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x30, 0x30,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x30, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d,
	0x30, 0x31, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x30, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x03, 0x6d, 0x30, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x31, 0x30, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x03, 0x6d, 0x31, 0x30, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x31, 0x31, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x31, 0x31, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x31, 0x32, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x31, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x32,
	0x30, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x32, 0x30, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x32, 0x31, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x32, 0x31, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x32, 0x32, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x32, 0x32,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x33, 0x30, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d,
	0x33, 0x30, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x33, 0x31, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x03, 0x6d, 0x33, 0x31, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x33, 0x32, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x03, 0x6d, 0x33, 0x32, 0x22, 0x44, 0x0a, 0x06, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78,
	0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x72, 0x6f, 0x77, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x02, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x90, 0x01, 0x0a,
	0x0e, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x6d, 0x61, 0x74, 0x68, 0x42,
	0x0d, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x63, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x74, 0x6f,
	0x68, 0x69, 0x6f, 0x2f, 0x45, 0x61, 0x73, 0x79, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x2f, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0xa2, 0x02, 0x03, 0x54, 0x4d, 0x58, 0xaa, 0x02,
	0x0a, 0x54, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x4d, 0x61, 0x74, 0x68, 0xca, 0x02, 0x0a, 0x54, 0x79,
	0x70, 0x65, 0x73, 0x5c, 0x4d, 0x61, 0x74, 0x68, 0xe2, 0x02, 0x16, 0x54, 0x79, 0x70, 0x65, 0x73,
	0x5c, 0x4d, 0x61, 0x74, 0x68, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0xea, 0x02, 0x0b, 0x54, 0x79, 0x70, 0x65, 0x73, 0x3a, 0x3a, 0x4d, 0x61, 0x74, 0x68, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_types_math_matrices_proto_rawDescOnce sync.Once
	file_types_math_matrices_proto_rawDescData []byte
)

func file_types_math_matrices_proto_rawDescGZIP() []byte {
	file_types_math_matrices_proto_rawDescOnce.Do(func() {
		file_types_math_matrices_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_math_matrices_proto_rawDesc), len(file_types_math_matrices_proto_rawDesc)))
	})
	return file_types_math_matrices_proto_rawDescData
}

var file_types_math_matrices_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_types_math_matrices_proto_goTypes = []any{
	(*Matrix2X2)(nil), // 0: types.math.Matrix2x2
	(*Matrix3X3)(nil), // 1: types.math.Matrix3x3
	(*Matrix4X4)(nil), // 2: types.math.Matrix4x4
	(*Matrix3X4)(nil), // 3: types.math.Matrix3x4
	(*Matrix4X3)(nil), // 4: types.math.Matrix4x3
	(*Matrix)(nil),    // 5: types.math.Matrix
}
var file_types_math_matrices_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_types_math_matrices_proto_init() }
func file_types_math_matrices_proto_init() {
	if File_types_math_matrices_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_math_matrices_proto_rawDesc), len(file_types_math_matrices_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_math_matrices_proto_goTypes,
		DependencyIndexes: file_types_math_matrices_proto_depIdxs,
		MessageInfos:      file_types_math_matrices_proto_msgTypes,
	}.Build()
	File_types_math_matrices_proto = out.File
	file_types_math_matrices_proto_goTypes = nil
	file_types_math_matrices_proto_depIdxs = nil
}
