// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: types/math/vectors.proto

package math

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Vector2D represents a 2D vector [x, y]
type Vector2D struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector2D) Reset() {
	*x = Vector2D{}
	mi := &file_types_math_vectors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector2D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector2D) ProtoMessage() {}

func (x *Vector2D) ProtoReflect() protoreflect.Message {
	mi := &file_types_math_vectors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector2D.ProtoReflect.Descriptor instead.
func (*Vector2D) Descriptor() ([]byte, []int) {
	return file_types_math_vectors_proto_rawDescGZIP(), []int{0}
}

func (x *Vector2D) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector2D) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Vector3D represents a 3D vector [x, y, z]
type Vector3D struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector3D) Reset() {
	*x = Vector3D{}
	mi := &file_types_math_vectors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector3D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3D) ProtoMessage() {}

func (x *Vector3D) ProtoReflect() protoreflect.Message {
	mi := &file_types_math_vectors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3D.ProtoReflect.Descriptor instead.
func (*Vector3D) Descriptor() ([]byte, []int) {
	return file_types_math_vectors_proto_rawDescGZIP(), []int{1}
}

func (x *Vector3D) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector3D) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector3D) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

// Vector4D represents a 4D vector [x, y, z, w]
type Vector4D struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	W             float32                `protobuf:"fixed32,4,opt,name=w,proto3" json:"w,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector4D) Reset() {
	*x = Vector4D{}
	mi := &file_types_math_vectors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector4D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector4D) ProtoMessage() {}

func (x *Vector4D) ProtoReflect() protoreflect.Message {
	mi := &file_types_math_vectors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector4D.ProtoReflect.Descriptor instead.
func (*Vector4D) Descriptor() ([]byte, []int) {
	return file_types_math_vectors_proto_rawDescGZIP(), []int{2}
}

func (x *Vector4D) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector4D) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector4D) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *Vector4D) GetW() float32 {
	if x != nil {
		return x.W
	}
	return 0
}

// Quaternion represents a quaternion [w, x, y, z] for rotations
type Quaternion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	W             float32                `protobuf:"fixed32,1,opt,name=w,proto3" json:"w,omitempty"`
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,4,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quaternion) Reset() {
	*x = Quaternion{}
	mi := &file_types_math_vectors_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quaternion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quaternion) ProtoMessage() {}

func (x *Quaternion) ProtoReflect() protoreflect.Message {
	mi := &file_types_math_vectors_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quaternion.ProtoReflect.Descriptor instead.
func (*Quaternion) Descriptor() ([]byte, []int) {
	return file_types_math_vectors_proto_rawDescGZIP(), []int{3}
}

func (x *Quaternion) GetW() float32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *Quaternion) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Quaternion) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Quaternion) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

// Vector represents a generic variable-length vector
type Vector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []float32              `protobuf:"fixed32,1,rep,packed,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_types_math_vectors_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_types_math_vectors_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_types_math_vectors_proto_rawDescGZIP(), []int{4}
}

func (x *Vector) GetData() []float32 {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_types_math_vectors_proto protoreflect.FileDescriptor

const file_types_math_vectors_proto_rawDesc = "" +
	"\n" +
	"\x18types/math/vectors.proto\x12\n" +
	"types.math\"&\n" +
	"\bVector2D\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\"4\n" +
	"\bVector3D\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\"B\n" +
	"\bVector4D\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\x12\f\n" +
	"\x01w\x18\x04 \x01(\x02R\x01w\"D\n" +
	"\n" +
	"Quaternion\x12\f\n" +
	"\x01w\x18\x01 \x01(\x02R\x01w\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x04 \x01(\x02R\x01z\"\x1c\n" +
	"\x06Vector\x12\x12\n" +
	"\x04data\x18\x01 \x03(\x02R\x04dataB\x8f\x01\n" +
	"\x0ecom.types.mathB\fVectorsProtoP\x01Z&github.com/itohio/EasyRobot/types/math\xa2\x02\x03TMX\xaa\x02\n" +
	"Types.Math\xca\x02\n" +
	"Types\\Math\xe2\x02\x16Types\\Math\\GPBMetadata\xea\x02\vTypes::Mathb\x06proto3"

var (
	file_types_math_vectors_proto_rawDescOnce sync.Once
	file_types_math_vectors_proto_rawDescData []byte
)

func file_types_math_vectors_proto_rawDescGZIP() []byte {
	file_types_math_vectors_proto_rawDescOnce.Do(func() {
		file_types_math_vectors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_math_vectors_proto_rawDesc), len(file_types_math_vectors_proto_rawDesc)))
	})
	return file_types_math_vectors_proto_rawDescData
}

var file_types_math_vectors_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_types_math_vectors_proto_goTypes = []any{
	(*Vector2D)(nil),   // 0: types.math.Vector2D
	(*Vector3D)(nil),   // 1: types.math.Vector3D
	(*Vector4D)(nil),   // 2: types.math.Vector4D
	(*Quaternion)(nil), // 3: types.math.Quaternion
	(*Vector)(nil),     // 4: types.math.Vector
}
var file_types_math_vectors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_types_math_vectors_proto_init() }
func file_types_math_vectors_proto_init() {
	if File_types_math_vectors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_math_vectors_proto_rawDesc), len(file_types_math_vectors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_math_vectors_proto_goTypes,
		DependencyIndexes: file_types_math_vectors_proto_depIdxs,
		MessageInfos:      file_types_math_vectors_proto_msgTypes,
	}.Build()
	File_types_math_vectors_proto = out.File
	file_types_math_vectors_proto_goTypes = nil
	file_types_math_vectors_proto_depIdxs = nil
}
